### ISSUE TITLE
mAh, not mV - wrong units

### ISSUE THREAD

**Issue by BloodyIron** [pwr-Solaar/Solaar#1388] opened 2021-12-22 18:37 UTC
I can't speak for other devices, but my Logitech G915 TKL reports the battery in mV (millivolts) which is not the correct unit of measurement representing battery level, which would be mAh (milliamp-hours). Can we please get this adjusted to the appropriate unit of measurement?

**Comment by pfps** [comment] 2021-12-22 18:52
Are you sure?  The information I have from Logitech is that some of their batteries are 240mAh batteries, so numbers around 4000, which is what I see for my G502, would be a very large battery if this is in mAh.  Further, there is a table for this battery showing reported voltages between 4.2 and 3.5 V and a nonlinear conversion to battery percentage.

**Comment by BloodyIron** [comment] 2021-12-22 19:46
It's the units that are the issue, not value. mV are not how a battery's capacity is measured.

**Comment by pfps** [comment] 2021-12-22 19:55
The point is that mV is what is being measured and reported by the battery.   I believe that this is true even for the batteries in laptops.  
Solaar now converts this to an estimate of remaining capacity using the table supplied by Logitech but still also reports mV.

**Comment by BloodyIron** [comment] 2021-12-22 20:06
Laptops report watt-hours remaining, not millivolts, as laptop batteries are typically measured in watt-hour capacity to conform with FAA regulations. Otherwise batteries are measured in milliamp-hours, not millivolts.

**Comment by BloodyIron** [comment] 2021-12-22 20:10
Battery capacity | 1500 mAh

source: https://www.lasystems.be/en/logitech-g-g915-tkl-gl-tactile-keyboard-rf-wireless-bluetooth-qwertz-german-white-qwertz-920-009661

**Comment by pfps** [comment] 2021-12-22 20:19
My understanding is that laptop battery capacity is measured in watt-hours, but the battery reports mV when operating.  Looking in /sys/class/power_supply/hidpp_battery_1/uevent, where the Linux information for my 502 battery is, on sees:
```
POWER_SUPPLY_NAME=hidpp_battery_1
POWER_SUPPLY_TYPE=Battery
POWER_SUPPLY_ONLINE=1
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_SCOPE=Device
POWER_SUPPLY_MODEL_NAME=G502 LIGHTSPEED Wireless Gaming Mouse
POWER_SUPPLY_MANUFACTURER=Logitech
POWER_SUPPLY_SERIAL_NUMBER=407f-1f-2d-bc-7e
POWER_SUPPLY_CAPACITY=88
POWER_SUPPLY_VOLTAGE_NOW=4056000
```
Remaining capacity is calculated from the voltage.

As Solaar is correctly reported what the battery provides, I'm closing this issue.

**Closed by pfps** 2021-12-22 20:19 UTC
Labels: enhancement

**Comment by BloodyIron** [comment] 2021-12-23 15:49
Voltage will never reach 0 before the battery "fails" due to zero charge. This is still a misleading unit of measurement as it gives no actual mAh measurement remaining for the user. It's more likely the battery is to "fail" in the 2000-3000mV range (ish) which gives the user a false sense of battery capacity security. Er-go, wrong units of measurement. While the device might be raw providing mV, the user needs mAh. Please re-open as this inaccurately represents the battery level from an absolute and percentage perspective.

**Comment by SlySven** [comment] 2021-12-27 10:49
To be honest, both of you have valid points, the battery level gauges used on Laptops for their battery/ies do report a percentage of what is available, which they can do because there is usually some sophisticated circuitry and software which measures the amount of charge (current X time) that has been put in/taken out of the device that can then calculate the effect given the capacity (Ah) of the battery. However this is not an exact figure as the component cells lose capacity over time, however it can be mitigated by also considering the expected voltage at various charge levels. For one or more AA or AAA cell(s) in a HID device the arrangement is going to be somewhat simpler and that is likely to only be reporting the voltage (like a hand-held) "battery-checker`. It seems to me that is what the Logitech API exposes over the USB interface - and Solaar is reporting that and trying to convert those (maybe only a few discrete) levels to a representative gauge

**Comment by PixlRainbow** [comment] 2022-09-06 04:00
The problem is that Logitech devices have highly variable battery sizes, and some even use different battery technologies. If the device doesn't declare what battery it's using, it's not possible to identify how much charge is left.

The only way this could be fixed is for Solaar to manage a database of every single device Logitech has ever manufactured and their associated battery configurations. This is an enormous undertaking that would be difficult for an individual non-commercial developer to achieve. If a device has replaceable batteries (e.g. AA or AAA batteries), it might not even be possible to calculate the remaining charge of the battery as the user might insert either alkaline, carbon-zinc, nickel metal-hydride or even lithium batteries.
