### ISSUE TITLE
Random changes of the icon for the shell integration in Ubuntu 23.04

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#2061] opened 2023-05-02 08:49 UTC
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 
  - solaar 1.1.8+dfsg-2
- Distribution:
  - Ubuntu 23.04, Gnome 44.0, X11
- Kernel version (ex. `uname -srmo`):
  - Linux 6.2.0-20-generic x86_64 GNU/Linux
- Output of `solaar show`:
  - Does not make sense. the log would be pretty enormous

**Describe the bug**
The icon used by the shell sometimes changes from the solaar icon (or battery) and into a triple dot (an hellip). I have no clue when or why it happens.

**To Reproduce**
Except sit and wait, I have no idea.

**Screenshots**

![Screenshot showing the triple dots](https://user-images.githubusercontent.com/4649804/235621363-2ec90fb8-6b19-4e39-86e9-ae85192e96f2.png)

The situation after the bug (?) appear.

Because the icon moves to the left side I wonder whether there are something going on that respawns the shell integration.

![Screenshot showing the usual solaar icon](https://user-images.githubusercontent.com/4649804/235623360-7e69d043-76c1-40b2-b560-0ebfa186343d.png)

The expected situation after a reboot. The icon reappears. 

On another machine, a Ubuntu 22.10, the battery icon is shown instead of the solaar icon.

The machine that show this behaviour was upgraded before the official roll-out, so it might be a bug that only hits this machine. I.e. a missing/failed update of some library.

**Comment by pfps** [comment] 2023-05-02 10:49
Solaar shows different icons at different times - the Solaar icon sometimes but usually a battery icon for the device with the lowest battery.  Most of these icons are standard icons that Solaar only knows by name.  Solaar also uses a standard library to show an icon in the system tray.   This library has had bugs that have had to be worked around.

It is most likely that the problem is either a bug in the library or some standard icon that Solaar is using.  

One thing to do is to check that the standard icons whose names start with 'battery' are all present and all look reasonable.

**Comment by jeblad** [comment] 2023-05-02 13:38
As far as I can tell, all the expected svg's are there. Not sure the locations are as expected though. 

Seems like there are some changes for how fallbacks for icons are handled in Gnome. Perhaps something is changed that impacts solaar.

This is the old entry in the doc, which fails on the fragment identifier

- <https://docs.gtk.org/gio/#g-themed-icon-new-with-default-fallbacks>

It seems like this is about the class `ThemedIcon`, which now has a method `new_with_default_fallbacks()`

- [Gio](https://docs.gtk.org/gio/index.html) – [ThemedIcon](https://docs.gtk.org/gio/class.ThemedIcon.html) – [new_with_default_fallbacks](https://docs.gtk.org/gio/ctor.ThemedIcon.new_with_default_fallbacks.html)

**Comment by jeblad** [comment] 2023-05-02 14:11
Seems like there are new symbolic icons in ubuntu-mon-dark/light, like `unity-gpm-battery-empty.svg`. There is also `gpm-mouse-*.svg`, they might be a hint on how these kind of symbols should look like. Colour is used as an additional hint.

![gpm-mouse](https://user-images.githubusercontent.com/4649804/235689808-ea728786-2788-4c0b-83b4-248c6bdfb440.png)

I changed the format to png, as Github doesn't like svg.

Something like this could perhaps be used if the single battery icon was replaced with icons for each of the attached devices, or  perhaps just a single icon for the most drained device. That would be pretty close to what the code does now.

There are a few variants of devices. One is a keyboard, but then it has a battery beside it for showing the charge status. I believe it is inconsistent to show the charge status inside the symbol in one case, and outside with an additional battery in another case. It should be without an outside battery to avoid confusion with the mobile/tablett/laptops own battery.

**Comment by jeblad** [comment] 2023-05-03 15:31
Not quite sure, but I wonder whether it always happen when I'm away from the machine.

Also not sure, but it might not happen with some previous version. I'm now running solaar 1.1.8 on the dev machine, and the previous version (could have been 1.1.5) did not have this behaviour. That machine has Ubuntu 22.10.

The machine that has the weird behaviour use solaar 1.1.8+dfsg-2 on Ubuntu 23.04.

Perhaps the difference can explain what's going on?

**Comment by pfps** [comment] 2023-05-03 15:39
The only change that I remember happening that might be relevant is that Solaar might not be showing anything in the tray when there are no devices.  I don't remember when this change happened.

It may be that the ... is Gnome showing a system tray with no items.  But this is out of the hands of Solaar.

**Comment by janvlug** [comment] 2023-05-16 14:26
See also: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/283

**Comment by heynnema** [comment] 2023-05-22 05:04
Use this parameter... --tray-icon-size=32 and see if that helps.

**Comment by Aqua1ung** [comment] 2023-06-10 22:51
Got this issue too: upon reboot the icon shows up just fine, only to turn to "..." later on, no idea when.

**Comment by heynnema** [comment] 2023-06-10 22:55
@Aqua1ung Did you try my fix?

**Comment by Aqua1ung** [comment] 2023-06-10 23:03
> @Aqua1ung Did you try my fix?

I did not, and that's because I do not usually start Solaar from CLI, but it starts automatically upon reboot (see below), and I'd have to do some digging to find out where exactly to add that parameter. For now, it doesn't bother me too much, but if you could guide me as to where exactly to make the change, I'd really appreciate it.
![Screenshot from 2023-06-10 19-02-41](https://github.com/pwr-Solaar/Solaar/assets/12104779/9f16a2cb-61b1-4359-8cc9-c87275975dcd)

**Comment by heynnema** [comment] 2023-06-10 23:10
@Aqua1ung If you start "Startup Applications" app, does Solaar show up there? If so, click the Edit button and edit the CLI command there. I have "solaar --window=hide --tray-icon-size=32" in mine.

**Comment by Aqua1ung** [comment] 2023-06-11 03:09
> @Aqua1ung If you start "Startup Applications" app, does Solaar show up there?
Thanks, I do not have a "Startup Applications" app. Like I said, I will have to do some digging to figure out how to do that, and I don't really have the time for that right now.

**Comment by Aqua1ung** [comment] 2023-06-13 03:13
@heynnema: my distro uses the `~/.config/autostart` folder for startup apps. I made the change you recommended to the `solaar.desktop` file (see below) in that folder, and ended up with this:
![Screenshot from 2023-06-12 23-05-58](https://github.com/pwr-Solaar/Solaar/assets/12104779/037bae3c-094a-4813-b972-872d3dbced84)
which is not exactly what I was aiming at. So I guess it is safe to say that your trick is not the solution, at least not for me.

Here's my `solaar.desktop` as promised:
```
[Desktop Entry]
Name=Solaar
Comment=Logitech Unifying Receiver peripherals manager
Comment[fr]=Gestionnaire de périphériques pour les récepteurs Logitech Unifying
Comment[hr]=Upravitelj Logitechovih uređaja povezanih putem Unifying i Nano prijemnika
Comment[ru]=Управление приёмником Logitech Unifying Receiver
Comment[es]=Administrador de periféricos de Logitech Receptor Unifying
Exec=solaar --tray-icon-size=32
Icon=solaar
StartupNotify=true
Terminal=false
Type=Application
Keywords=logitech;unifying;receiver;mouse;keyboard;
Categories=Utility;GTK;
#Categories=Utility;GTK;Settings;HardwareSettings;
X-GNOME-UsesNotifications=true
```

**Comment by heynnema** [comment] 2023-06-13 12:35
@Aqua1ung The Solaar icon looks fine to me. What's not right about your screenshot?

**Comment by Aqua1ung** [comment] 2023-06-15 21:08
@heynnema, yes, you've convinced me that your fix works, nevertheless, we should not have to do that to get Solaar to function as it should. In this regard, here below is an extract from my log that may constitute a clue as to why things are not working as they should, and I am posting this in the hopes that the Solaar devs could find it useful:
```
Jun 15 16:40:07 DadsGram gnome-shell[753]: Could not find the icon 'battery-good-ltr'. The 'hicolor' theme
                                           was not found either, perhaps you need to install it.
                                           You can get a copy from:
                                                   http://icon-theme.freedesktop.org/releases
```

**Comment by pfps** [comment] 2023-06-15 21:44
Solaar should not be using battery-good-ltr, unless there is some new icon naming in Wayland/Gnome.  But even so, this does not appear to be a bug in Solaar.

The other messages are just as mysterious.  Again, maybe Wayland/Gnome has changed some interface.  Someone else will have to figure out what is going wrong as I use neither Wayland nor Gnome.

**Comment by heynnema** [comment] 2023-06-15 23:34
@Aqua1ung The problem started in Ubuntu 23.04. Gnome 44.0 is used there, and that's probably where the problem is.

**Comment by Aqua1ung** [comment] 2023-06-17 15:15
> I use neither Wayland nor Gnome.

Are you still on Xorg?

**Comment by pfps** [comment] 2023-06-17 16:01
Yes.  I use XFCE which uses X11.

**Comment by Spurlos** [comment] 2023-06-28 15:39
Im on ubuntu 23.04, using X11, also getting similar messages and icon changes to 3 dots
```
Jun 28 18:36:41 spurlos-ThinkPad-E580 ubuntu-appindicators@ubuntu.com[3610]: indicator-solaar, Impossible to lookup icon for 'battery-full' in /usr/share/solaar/icons
```

**Comment by jeblad** [comment] 2023-06-29 10:01
I was sitting by my machine while the icon suddenly was reposition to the left. Usually this means the hellip shows up instead of the icon, but not this time. I had changed from the symbolic style and to the 32px fix.

Strange thing; it seems like it follows the Mech Mini that is at 70%, and not the MX Anywhere at 45%.

**Comment by pfps** [comment] 2023-07-24 10:39
There doesn't seem to be anything more to do here on the Solaar side, so I'm closing this issue.

**Closed by pfps** 2023-07-24 10:39 UTC
