### ISSUE TITLE
Can not pair G915 with its receiver

### ISSUE THREAD

**Issue by Maor545** [pwr-Solaar/Solaar#930] opened 2020-08-26 21:08 UTC
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.0.3-44-gf5c00a5
- Distribution: Debian 10 next
- Kernel version (ex. `uname -srmo`): `Linux 5.7.0-2-amd64 x86_64 GNU/Linux
- Output of `solaar show`:
```
Lightspeed Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c541
  Serial       : <censored>
    Firmware   : 01.01.B0027
    Bootloader : 01.27
    Other      : E6.6B
  Has 0 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)
```
- Output:
```
bin/solaar -d -d -d  
22:27:31,331     INFO [MainThread] root: language en_GB (UTF-8), translations path None
22:27:31,399    DEBUG [MainThread] solaar.ui.tray: using Ayatana AppIndicator3
22:27:31,405     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
22:27:31,431    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
22:27:31,432    DEBUG [AsyncUI] solaar.tasks: started
22:27:31,432     INFO [MainThread] solaar.ui.notify: starting desktop notifications
22:27:31,440    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /home/user/Downloads/Solaar/lib
22:27:31,440    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/user/Downloads/Solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/user/Downloads/Solaar/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/user/.local/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/user/Downloads/Solaar/lib/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/user/Downloads/Solaar/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
22:27:31,441    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/user/Downloads/Solaar/share/solaar/icons', '/home/user/Downloads/Solaar/share/solaar/icons', '/home/user/.local/share/icons', '/home/user/.icons', '/usr/share/icons', '/usr/share/icons', '/usr/local/share/icons', '/usr/share/pixmaps', '/usr/share/pixmaps', '/usr/local/share/pixmaps']
22:27:31,500     INFO [MainThread] solaar.listener: starting receiver listening threads
22:27:31,566     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw5', vendor_id='046d', product_id='c541', serial='', release=b'0101', manufacturer=b'Logitech', product=b'USB Receiver', interface=2, driver='hid-generic')
22:27:31,623    DEBUG [MainThread] logitech_receiver.base: (16) <= w[10 FF 83B5 030000]
22:27:31,625    DEBUG [MainThread] logitech_receiver.base: (16) => r[11 FF 83B5 0332B4B14B0101070000000000000000]
22:27:31,626    DEBUG [MainThread] logitech_receiver.base: (16) <= w[10 FF 80B2 000000]
22:27:31,627    DEBUG [MainThread] logitech_receiver.base: (16) => r[10 FF 8F80 B20300]
22:27:31,627    DEBUG [MainThread] logitech_receiver.base: (16) device 0xFF error on request {80B2}: 3 = invalid value
22:27:31,628     INFO [ReceiverListener:hidraw5] logitech_receiver.listener: started with <LightspeedReceiver(/dev/hidraw5,16)> (16)
22:27:31,629     INFO [ReceiverListener:hidraw5] solaar.listener: <LightspeedReceiver(/dev/hidraw5,16)>: notifications listener has started (16)
22:27:31,629    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) <= w[10 FF 8000 100900]
22:27:31,630    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 8000 000000]
22:27:31,630    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) <= w[10 FF 8100 000000]
22:27:31,632    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 8100 000900]
22:27:31,632     INFO [ReceiverListener:hidraw5] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw5,16)>: receiver notifications enabled => ('wireless', 'software present')
22:27:31,632    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) <= w[10 FF 8002 020000]
22:27:31,634    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 8002 000000]
22:27:31,634     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,16)>: present, No paired devices. (0) 
22:27:31,639    DEBUG [MainThread] solaar.ui: activate
22:27:31,644    DEBUG [MainThre
ad] solaar.ui: status changed: <LightspeedReceiver(/dev/hidraw5,16)> (NONE) None
22:27:31,648    DEBUG [MainThread] solaar.ui.window: new receiver row ('/dev/hidraw5', 0, True, 'Lightspeed Receiver', 'preferences-desktop-peripherals', None, None, <LightspeedReceiver(/dev/hidraw5,16)>)
22:27:33,826    DEBUG [MainThread] logitech_receiver.base: (17) <= w[10 FF 8102 000000]
22:27:33,828    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 8102 000000]
22:27:33,829    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 8102 000000]
22:27:35,017    DEBUG [MainThread] solaar.ui.pair_window: prepare <Gtk.Assistant object at 0x7efe6c036e40 (GtkAssistant at 0x27fe720)> 0 <Gtk.VBox object at 0x7efe6c031a00 (GtkVBox at 0x280c9c0)>
22:27:35,017    DEBUG [MainThread] logitech_receiver.base: (17) <= w[10 FF 80B2 01001E]
22:27:35,019    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 4A01 000000]
22:27:35,019    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 4A01 000000]
22:27:35,019     INFO [ReceiverListener:hidraw5] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw5,16)>: pairing lock is open
22:27:35,019     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,16)>: present, No paired devices. (1) pairing lock is open
22:27:35,020    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 80B2 000000]
22:27:35,020    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 80B2 000000]
22:27:35,022    DEBUG [MainThread] solaar.ui: status changed: <LightspeedReceiver(/dev/hidraw5,16)> (NOTIFICATION) pairing lock is open
22:27:35,023    DEBUG [MainThread] logitech_receiver.base: (17) <= w[10 FF 8102 000000]
22:27:35,024    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 8102 000000]
22:27:35,024    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 8102 000000]
22:28:04,217    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 4A00 010000]
22:28:04,218     INFO [ReceiverListener:hidraw5] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw5,16)>: pairing lock is closed
22:28:04,218  WARNING [ReceiverListener:hidraw5] logitech_receiver.notifications: pairing error 1: device timeout
22:28:04,218     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw5,16)>: present, No paired devices. (1) pairing lock is closed
22:28:04,219    DEBUG [MainThread] solaar.ui: status changed: <LightspeedReceiver(/dev/hidraw5,16)> (NOTIFICATION) pairing lock is closed
22:28:04,222    DEBUG [MainThread] logitech_receiver.base: (17) <= w[10 FF 8102 000000]
22:28:04,223    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 8102 000000]
22:28:04,223    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 FF 8102 000000]
22:28:04,555    DEBUG [MainThread] solaar.ui.pair_window: <LightspeedReceiver(/dev/hidraw5,16)> fail: device timeout
22:28:04,559    DEBUG [MainThread] solaar.ui.pair_window: prepare <Gtk.Assistant object at 0x7efe6c036e40 (GtkAssistant at 0x27fe720)> 1 <Gtk.VBox object at 0x7efe7d8bbd40 (GtkVBox at 0x280cde0)>
22:28:08,364    DEBUG [MainThread] solaar.ui.pair_window: finish <Gtk.Assistant object at 0x7efe7d8bbd40 (GtkAssistant at 0x27fe720)>
```

**Describe the bug**
Can not pair G915 keyboard with it's receiver.

**To Reproduce**
0. unpair G915 and receiver
1. pair new device
2. restart the G915 keyboard
3. wait for timeout

**Additional context**
I was hoping to pair a G604 mouse with the G915's receiver, so i unpaired the keyboard. Now I cannot get it to pair.
Logitech Connection utility 2.30.9 on windows does not work either, here is the only log I could get on windows machine
```
Re-Connect Software Version : 2.30.9
Dj Api Version : 2, 60, 158

Receiver
Name : wireless receiver
ModelId : 0x46dc541
Serial Number : <censored>
Handle : 0xff000001
Wireless Status : 0x3
Firmware version : 001.001.00027
Bootloader version : BL.001.027
Dfu Status : 0x1
Is Dfu Cancellable : Yes
Max Device Capacity : 6
```
Does the Max Device Capacity means, that in theory we could connect up to 6 lightspeed compatible devices to this dongle?

**Comment by pfps** [comment] 2020-08-26 21:47
If it doesn't work using Logitech's software it's very unlikely that Solaar can do it.  Lightspeed receivers might only be able to pair with particular mice.

The output of `solaar show` might help to see what might be going on.  Please provide that.

**Comment by Maor545** [comment] 2020-08-26 23:13
I have updated the log of `solar show` in the intial post.

I would appreciate suggestions what to debug next.

**Comment by pfps** [comment] 2020-08-27 00:31
I would try `solaar -dd pair` and switch your mouse on (after off if necessary).  If that doesn't work then you are almost certainly out of luck unless you get some help from Logitech.

**Comment by Maor545** [comment] 2020-08-27 16:49
I have tried pairing from CLI with no success

`11:12:14,354    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
11:12:14,354    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 0332B4B14B0101070000000000000000]
11:12:14,354    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
11:12:14,355    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F80 B20300]
11:12:14,355    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {80B2}: 3 = invalid value
11:12:14,355    DEBUG [MainThread] solaar.cli: [/dev/hidraw3] => <LightspeedReceiver(/dev/hidraw3,3)>
11:12:14,357    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8100 000000]
11:12:14,358    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8100 000900]
11:12:14,358    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 200000]
11:12:14,359    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
11:12:14,359    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
11:12:14,359    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
11:12:14,360    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
11:12:14,360    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
11:12:14,360    ERROR [MainThread] logitech_receiver.device: failed to read Nano wpid for device 1 of <LightspeedReceiver(/dev/hidraw3,3)>
11:12:14,361    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/home/mkostal/Downloads/Solaar/lib/logitech_receiver/receiver.py", line 150, in register_new_device
    dev = Device(self, number, notification)
  File "/home/mkostal/Downloads/Solaar/lib/logitech_receiver/device.py", line 121, in init
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='read Nano wpid')
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <LightspeedReceiver(/dev/hidraw3,3)>, 'error': 'read Nano wpid'}
11:12:14,361  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,3)>: looked for device 1, not found
11:12:14,362    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 010014]
11:12:14,363    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 4A01 000000]
11:12:14,364     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw3,3)>: pairing lock is open
11:12:14,365    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 80B2 000000]
Pairing: turn your new device on (timing out in 20 seconds).
11:12:34,335    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 4A00 010000]
11:12:34,336     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw3,3)>: pairing lock is closed
11:12:34,336  WARNING [MainThread] logitech_receiver.notifications: pairing error 1: device timeout
solaar: error: Traceback (most recent call last):
  File "/home/mkostal/Downloads/Solaar/lib/solaar/cli/__init__.py", line 196, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/mkostal/Downloads/Solaar/lib/solaar/cli/pair.py", line 92, in run
    raise Exception('pairing failed: %s' % error)
Exception: pairing failed: device timeout`

**Comment by pfps** [comment] 2020-08-27 18:18
The second error is just saying that no device was paired before pairing timed out.
I'll have to check into what the problem is that is causing the first error.

**Comment by pfps** [comment] 2020-08-27 18:29
It looks as if you cut off the initial few lines of debug output.  I don't think it matters but having full output would be better.  Also can you provide output of `bin/solaar probe`?

**Comment by pfps** [comment] 2020-08-27 19:02
The first error should also be benign - Solaar is checking every possible slot on the receiver to see whether there is a device there - if there is no device in the position (only one for your receiver) then an internal exception is signalled that is caught elsewhere.

So the debugging output looks completely normal for pairing where the receiver didn't see a device turning on (remember that pairing requires turning the device on, and off if was on) that it was wiling to pair with.   There are three possible reasons for this: 1/ the device isn't compatible with the receiver - Lightspeed receivers only pair with certain device models; 2/ the device didn't turn on - perhaps because of low battery; and 3/ the receiver is out of pairing attempts.  (This last is not likely, I think.)

**Comment by Maor545** [comment] 2020-08-28 19:43
will do the `bin/solaar probe` output tomorrow, in the meanwhile:

> 1/ the device isn't compatible with the receiver - Lightspeed receivers only pair with certain device models;
Since is was paired before I unpaired it with Solaar, is must be compatible.
>2/ the device didn't turn on - perhaps because of low battery; and
The keyboard G915 turns on and the lightspeed button slowly blinks - this means that the keyboard is trying to connect to a receiver. Same goes for the G604 mouse. The battery should be OK, since both can work via bluetooth.
>3/ the receiver is out of pairing attempts. (This last is not likely, I think.)
I would assume, that the receiver is somewhat broken, or does the keyboard itself need some unpairing procedure before it can be paired again?

**Comment by pfps** [comment] 2020-08-28 21:22
Some devices to remember the receiver they were last paired with, but when turned on they should pair with any suitable receiver.  I'm not aware of any unpairing procedure for a device.  About the only thing left to try would be to remove the batteries from the device so that it really turns off.

Other than that I'm out of ideas, then.  It appears that something is going wrong between the receiver and the device.  If the Logitech software can't pair either then there is almost certainly nothing that Solaar can do.  I suggest opening a ticket with Logitech.

**Comment by Maor545** [comment] 2020-08-31 16:36
`bin/solaar probe`
```
Lightspeed Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c541
  Serial       : 32B4B14B
    Firmware   : 01.01.B0027
    Bootloader : 01.27
    Other      : E6.6B
  Has 0 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)
  Register Dump
    Notification Register 0x00: 0x000900
    Connection State      0x02: 0x000000
    Device Activity       0xb3: 0x00000000000000000000000000000000
    Pairing Register 0xb5 0x00: None
    Pairing Register 0xb5 0x10: None
    Pairing Register 0xb5 0x20: None
    Pairing Register 0xb5 0x30: None
    Pairing Name     0xb5 0x40: None
    Pairing Register 0xb5 0x01: None
    Pairing Register 0xb5 0x11: None
    Pairing Register 0xb5 0x21: None
    Pairing Register 0xb5 0x31: None
    Pairing Name     0xb5 0x41: None
    Pairing Register 0xb5 0x02: 0x020101002780140D00C7F1A384000000
    Pairing Register 0xb5 0x12: None
    Pairing Register 0xb5 0x22: None
    Pairing Register 0xb5 0x32: None
    Pairing Name     0xb5 0x42: None
    Pairing Register 0xb5 0x03: 0x0332B4B14B0101070000000000000000
    Pairing Register 0xb5 0x13: None
    Pairing Register 0xb5 0x23: None
    Pairing Register 0xb5 0x33: None
    Pairing Name     0xb5 0x43: None
    Pairing Register 0xb5 0x04: None
    Pairing Register 0xb5 0x14: None
    Pairing Register 0xb5 0x24: None
    Pairing Register 0xb5 0x34: None
    Pairing Name     0xb5 0x44: None
    Pairing Register 0xb5 0x05: None
    Pairing Register 0xb5 0x15: None
    Pairing Register 0xb5 0x25: None
    Pairing Register 0xb5 0x35: None
    Pairing Name     0xb5 0x45: None
    Firmware         0xf1 0x00: None
    Firmware         0xf1 0x01: 0x010101
    Firmware         0xf1 0x02: 0x020027
    Firmware         0xf1 0x03: 0x03E66B
    Firmware         0xf1 0x04: 0x040127
```

**Comment by pfps** [comment] 2020-08-31 19:14
Thanks for the extra information.  I'll try to see if I can obtain documentation on the receiver registers.

I took a bit closer look at the log for pairing.  The receiver leaves its lock open for 20 seconds, so it looks as if it can accept new pairings, it is just that it doesn't see a device turning on that it likes (maybe because the pairing command is not correct).  I'll try to see if can obtain better documentation on how these receivers pair.

**Comment by pfps** [comment] 2020-08-31 19:28
One thing to try is to send a slightly different pairing command.  Solaar sends 
```
10 FF 80B2 010014
```
Try sending a slightly different command using ./tools/hidconsole  (<n> is the node number for your receiver, run `ls /dev/hidraw*` and look for the line with a + after the permission bits)
```
./tools/hidconsole /dev/hidraw<n>
10 FF 80B2 010114
```
Then turn your mouse off and on.

I view this as having a low probability of working but it is worth a try.

**Comment by Maor545** [comment] 2020-08-31 20:47
I will try that. I really appreciate the help.
Is there any possibility to get debugging info through the usb port of the G915 keyboard? i.e. Checking whether any pairing requests are being send. The G915 KB can work also in a wired mode, so I guess it could be using a similar ser of HID+ commands as the receivers.

**Comment by pfps** [comment] 2020-08-31 23:34
Solaar should now partially support wired devices.  If the G915 connects through USB it will be easy to add support for this device as well.

What you have to do is to download Solaar from this repository and edit lib/logitech_receiver/base_usb.py to include the USB ID for the G915 in the Wired devices section and to WIRED_DEVICES, just like the other devices.   Then you try out the CLI for Solaar as `sudo bin/solaar <command>`.  Your device should show in the command `show`.  However, this is unlikely to help with pairing as the interface should work the same as when connected wirelessly.

GUI support for wired devices should be available soon.  Let me know if you want to test that out.

**Comment by pfps** [comment] 2020-09-01 22:05
I added some code to `bin/solaar probe` to dump the entire register state, just in case your receiver has other registers can you download the current version of Solaar and run this version of probe?

**Comment by Maor545** [comment] 2020-09-02 19:08
> I added some code to `bin/solaar probe` to dump the entire register state, just in case your receiver has other registers can you download the current version of Solaar and run this version of probe?

```
?? Input: 10ff80b2010114
<< (  64.703) [10 FF 80B2 010114] b'\x10\xff\x80\xb2\x01\x01\x14'
>> (  64.704) [10 FF 4A01 000000] b'\x10\xffJ\x01\x00\x00\x00'
>> (  64.705) [10 FF 80B2 000000] b'\x10\xff\x80\xb2\x00\x00\x00'
>> (  84.592) [10 FF 4A00 010000] b'\x10\xffJ\x00\x01\x00\x00'
```

**Comment by Maor545** [comment] 2020-09-02 19:10
> One thing to try is to send a slightly different pairing command. Solaar sends
> 
> ```
> 10 FF 80B2 010014
> ```
> 
> Try sending a slightly different command using ./tools/hidconsole ( is the node number for your receiver, run `ls /dev/hidraw*` and look for the line with a + after the permission bits)
> 
> ```
> ./tools/hidconsole /dev/hidraw<n>
> 10 FF 80B2 010114
> ```
> 
> Then turn your mouse off and on.
> 
> I view this as having a low probability of working but it is worth a try.

```
?? Input: 10ff80b2010114
<< (  64.703) [10 FF 80B2 010114] b'\x10\xff\x80\xb2\x01\x01\x14'
>> (  64.704) [10 FF 4A01 000000] b'\x10\xffJ\x01\x00\x00\x00'
>> (  64.705) [10 FF 80B2 000000] b'\x10\xff\x80\xb2\x00\x00\x00'
>> (  84.592) [10 FF 4A00 010000] b'\x10\xffJ\x00\x01\x00\x00'
```

**Comment by pfps** [comment] 2020-09-02 19:25
So the pairing lock opened.  Did you manage to pair?

**Comment by pfps** [comment] 2020-09-02 19:26
The output of probe doesn't show anything new that looks useful.  I'm still trying to get information on how lightspeed receivers work.

**Comment by pfps** [comment] 2020-09-08 13:31
I have some more information on how Lightspeed receivers work.  The information is not very encouraging - your receiver may not be able to pair again.  :-(   Why Lightspeed receivers can unpair when they have this limit is unclear to me.

There is a possibility that might work (but I don't think it very likely).   If you clone this repository and change line 163 of lib/logitech_receiver/receiver.py to
```
            action = 0x02 if lock_closed else 0x06
```
You might be able to "force" a last pairing in the Solaar UI.
If that doesn't work you might try also changing line 164 to 
```
            reply = self.write_register(_R.receiver_pairing, action, 0x01, timeout)
```

If neither of these work, then I think you are out of luck.

**Comment by Maor545** [comment] 2020-09-08 18:08
> I have some more information on how Lightspeed receivers work. The information is not very encouraging - your receiver may not be able to pair again. :-( Why Lightspeed receivers can unpair when they have this limit is unclear to me.
> 
> There is a possibility that might work (but I don't think it very likely). If you clone this repository and change line 163 of lib/logitech_receiver/receiver.py to
> 
> ```
>             action = 0x02 if lock_closed else 0x06
> ```
> 
> You might be able to "force" a last pairing in the Solaar UI.
> If that doesn't work you might try also changing line 164 to
> 
> ```
>             reply = self.write_register(_R.receiver_pairing, action, 0x01, timeout)
> ```
> 
> If neither of these work, then I think you are out of luck.
This did not work.

I have tested a receiver with ID046d:c539 which is the original G502 Lightspeed receiver.
This receiver can be paired together with G604 mouse and all my attempts with pairing the G915 KB failed.
I conclude, that lightspeed keyboards are using different protocol from mouses.

**Comment by pfps** [comment] 2020-09-08 19:31
Lightspeed mice and keyboards should be using the same protocol, but lightspeed receivers will only pair with certain mice or keyboards, probably only the same model that they came with.

It would be useful to have output from `bin/solaar probe` for the 046d:c539 receiver to check that it matches the output for your other receiver.

**Comment by pfps** [comment] 2020-09-16 12:11
I now have a G502 and its associated receiver.  I can unpair and pair fine.

I see two possible reasons that you cannot pair.
Maybe the receiver is no longer unable to pair (very unlikely because the pairing lock is stays open for the 20 seconds or so).
Maybe the receiver is not seeing a valid pairing message.  This can happen if the wrong kind of device is sending the message (but you appear to be trying the correct pairing so this is unlikely).  This can also happen if the device has weak batteries and doesn't send a strong signal.  This can also happen if the device doesn't actually turn on (perhaps because the switch is not working.)   In any case this is outside the purview of Solaar.

So I'm closing this issue (for now).  If you have any new information, feel free to reopen the issue.

**Comment by pfps** [comment] 2020-09-18 12:55
See the message at the end of issue #949.  
Your problem may be that Lightspeed keyboards pair differently than Unifying devices.

**Comment by pfps** [comment] 2020-10-21 16:02
I'm closing this issue (for now) as there doesn't seem to be anything more that can be done at this point.  If more information is provided then the issue can be reopened.

**Closed by pfps** 2020-10-21 16:02 UTC
