### ISSUE TITLE
Scroll becomes slow

### ISSUE THREAD

**Issue by msdobrescu** [pwr-Solaar/Solaar#707] opened 2020-03-10 09:53 UTC
**Information**
- Solaar version (`git describe --tags` if cloned from Solaar repository): 1.0.1-r1, https://packages.sabayon.org/show/solaar,243891,sabayonlinux.org,amd64,5,standard
- Distribution: Sabayon Linux fully up to date
Operating System: Gentoo Linux 
KDE Plasma Version: 5.18.1
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.4.0-sabayon
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7 CPU 920 @ 2.67GHz
Memory: 23,5 GiB of RAM
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 77099BBB
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=168, 2=166

  1: Marathon Mouse M705 (M-R0009)
     Codename     : M705 (M-R0009)
     Kind         : mouse
     Wireless PID : 101B
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 7C44B18E
          Firmware: 17.01.B0017
        Bootloader: 02.06
             Other: 00.04
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: 25%, discharging.

  2: Wireless Illuminated Keyboard K800
     Codename     : K800
     Kind         : keyboard
     Wireless PID : 2010
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: FFC65665
          Firmware: 22.01.B0019
        Bootloader: 02.01
             Other: 00.07
     The power switch is located on the top right corner.
     Notifications: battery status (0x100000).
     Battery: full, discharging.
```

**Describe the bug**
The scroll becomes slow after a while, probably if the mouse enters in kind of standby. Slow means that many scrolls (I'd say, at least three times more than regular) are needed for one scroll step to occur.

**To Reproduce**
Previous version was 0.92-r3, info here https://packages.sabayon.org/show/solaar,3979,sabayonlinux.org,armv7l,5,standard, and behaved differently, at the first login in KDE, it was slow, then works fine after unplugging/plugging the dongle.

Current version, 1.0.1-r1 needs re-plugging all the time. It simply becomes slow scrolling. Only scrolling, as long as Solaar is on. If it is closed, the scroll operates as fast continuously, even after long inactivity.

**Comment by pfps** [comment] 2020-03-10 11:31
About the only thing that I can think of is that Solaar is setting some sort of speed control for the mouse, but not all the time.   As your mouse uses HID++ 1.0, solaar show doesn't show everything about the mouse.  (Yes, yes, it should, but ....)  Looking at descriptors.py there are a couple of scrolling features that can be changed, and maybe Solaar is changing them when the mouse wakes up after sleep.  
To check, you could remove the saved settings for the mouse by deleting ~/.config/solaar/config.json when solaar is not running.
There was a bug in solaar having to do with incorrect setting of saved features that was fixed recently so you also might want to clone this repository and run solaar from there.

**Comment by msdobrescu** [comment] 2020-03-10 18:24
Deleted that, re-created, so far so good.

**Comment by msdobrescu** [comment] 2020-03-11 06:47
it works after the suggested operation, thank you.
Might be a confusion between the config entries?
I've had there one more mouse, initially.

**Comment by pfps** [comment] 2020-03-11 15:01
Solaar should be keeping track of different mice using different entries, unless the mice in question don't have serial numbers.
But as the problem isn't a current problem, I'm closing this issue.  Feel free to reopen if the problem recurs.

**Closed by pfps** 2020-03-11 15:01 UTC
Labels: bug
