### ISSUE TITLE
Please update the Flatpak on Fedora/Nobara, it's getting close to 6 months old

### ISSUE THREAD

**Issue by Waifu4Life** [pwr-Solaar/Solaar#2364] opened 2024-03-04 04:03 UTC
Please update the Flatpak on Fedora/Nobara, it's getting close to 6 months old

**Comment by pfps** [comment] 2024-03-04 04:18
You will have to contact whoever is responsible for this.

You can install Solaar in Fedora with just `sudo dnf install solaar`.

**Comment by Waifu4Life** [comment] 2024-03-04 04:20
> sudo dnf install solaar

Will this install the same version that I see in Discovery or the latest version here?

**Comment by pfps** [comment] 2024-03-04 04:22
It generally installs the most recent release but right now it is installing 1.1.10, not 1.1.11.

**Comment by Waifu4Life** [comment] 2024-03-04 04:23
> It generally installs the most recent release but right now it is installing 1.1.10, not 1.1.11.

1.1.10 is what I have right now, guess the Flatpak won't be updated until the command itself installs 1.1.11.

**Comment by pfps** [comment] 2024-03-04 04:25
You can also install using `pip install solaar`, which will install 1.1.11.   If you have Solaar already installed you shouldn't need to do anything else, except make sure that the pip user bin directory is in your path.

**Comment by Waifu4Life** [comment] 2024-03-04 04:29
> You can also install using `pip install solaar`, which will install 1.1.11. If you have Solaar already installed you shouldn't need to do anything else, except make sure that the pip user bin directory is in your path.

That version is broken, gears are always spinning, can't find my mouse and keyboard. How do I uninstall this?

**Comment by pfps** [comment] 2024-03-04 04:32
`pip uninstall solaar`

I see that.  I wonder why there have not been any reports of problems.

**Comment by Waifu4Life** [comment] 2024-03-04 04:36
> `pip uninstall solaar`
> 
> I see that. I wonder why there have not been any reports of problems.

Beats me, but 1.1.10 works. Thank your help regardless.

**Comment by pfps** [comment] 2024-03-04 04:40
I uploaded a fixed version so `pip install solaar` should install 1.1.11.1 (the .1 is only visible when installing).

**Comment by Waifu4Life** [comment] 2024-03-04 04:43
> I uploaded a fixed version so `pip install solaar` should install 1.1.11.1 (the .1 is only visible when installing).

Just tried it, same problem.

**Comment by pfps** [comment] 2024-03-04 04:43
Hmm.

**Comment by pfps** [comment] 2024-03-04 04:52
It's working for me.   Did you check to make sure that the install log had 1.1.11.1 in it (in two places, I think).

**Comment by Waifu4Life** [comment] 2024-03-04 04:54
> It's working for me. Did you check to make sure that the install log had 1.1.11.1 in it (in two places, I think).

I went to "About Solaar".

**Comment by pfps** [comment] 2024-03-04 04:54
That says 1.1.11 as I didn't update it.

**Comment by Waifu4Life** [comment] 2024-03-04 05:00
> That says 1.1.11 as I didn't update it.

Sorry, I'm still new in Linux, so I don't know where to search most of the time.

**Comment by pfps** [comment] 2024-03-04 05:04
When you use pip to install something it prints out progress lines.   These should have included 1.1.11.1 somewhere.

You can even see some of this  with `pip install solaar` even if Solaar is already installed using pip.  This is what I see

```
pip install solaar
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: solaar in /home/pfps/.local/lib/python3.12/site-packages (1.1.11.1)
Requirement already satisfied: pyudev>=0.13 in /usr/lib/python3.12/site-packages (from solaar) (0.24.1)
Requirement already satisfied: PyYAML>=3.12 in /usr/lib64/python3.12/site-packages (from solaar) (6.0.1)
Requirement already satisfied: python-xlib>=0.27 in /usr/lib/python3.12/site-packages (from solaar) (0.33)
Requirement already satisfied: psutil>=5.4.3 in /usr/lib64/python3.12/site-packages (from solaar) (5.9.5)
Requirement already satisfied: evdev>=1.1.2 in /usr/lib64/python3.12/site-packages (from solaar) (1.6.1)
Requirement already satisfied: dbus-python in /usr/lib64/python3.12/site-packages (from solaar) (1.3.2)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.12/site-packages (from python-xlib>=0.27->solaar) (1.16.0)
```

If you want to run the pip-installed Solaar you have to make sure that your shell can find it.   `which solaar` should say something like
`/home/<your user ID>/.local/bin/solaar`

**Comment by Waifu4Life** [comment] 2024-03-04 05:17
> which solaar

Not sure if you changed something, but the software is working now after the installation I did 3 minutes ago. I now see features that were not in 1.1.10 such as using a different on-board profile in my G703 (before that it was the 1st profile on or off). Thank you very much.

I have an off-topic question if you don't mind. I configured one my mouse buttons in the G-Hub software to use the Play/Pause feature in Windows, it would play or pause the latest media that I started on my computer (YouTube, VLC, etc.). In Nobara, this button doesn't do anything, but on my Logitech keyboard, hitting Fn+F9 does Play/Pause. Any idea what's happening?

**Comment by pfps** [comment] 2024-03-04 05:23
Most modifications to mice and keyboards are forgotten when the mouse or keyboard goes into a power-saving mode or is turned off.  So software like Solaar has to remember the changes and reimpose them each time the mouse or keyboard wakes up.

The default action for many Fn-shifted function keys is to send an HID consumer control "character", hopefully one related to the symbol on the key cap.   Linux software understands some of these "characters" out of the box;  some need to be set up specially to work as expected; and some are not compatible with Linux.    MacOS and Windows work differently from Linux, and from each other.

**Comment by Waifu4Life** [comment] 2024-03-04 05:36
> Most modifications to mice and keyboards are forgotten when the mouse or keyboard goes into a power-saving mode or is turned off. So software like Solaar has to remember the changes and reimpose them each time the mouse or keyboard wakes up.
> 
> The default action for many Fn-shifted function keys is to send an HID consumer control "character", hopefully one related to the symbol on the key cap. Linux software understands some of these "characters" out of the box; some need to be set up specially to work as expected; and some are not compatible with Linux. MacOS and Windows work differently from Linux, and from each other.

Sorry, I probably did not give enough details. In G-Hub, I made my profile on-board in my mouse and I've configured 4 keys on it: 
Mouse wheel button: Stat Menu
Upper-side button: Backspace
Lower-side button: Ctrl
Tiny button bellow the mouse wheel: Play/Pause

The other 3 buttons do work in Nobara with my on-board profile. In-fact, using Solaar, I can disable the profile. It's just that Play/Pause button that works differently in Linux somehow.

**Comment by pfps** [comment] 2024-03-04 14:21
What you want to do is to find out what  happens when you press the button that you want to do Play/Pause.  The problem is that this is somewhat difficult to do.   One way to proceed is to use the command `sudo showkey --keycodes`, which shows keycodes for the keys you type.  As a test, press the keyboard key (or combination) that is doing what you want and then the mouse button.  I expect that you will see something like

```
idefix ~> sudo showkey --keycodes
kb mode was ?UNKNOWN?
[ if you are trying this under X, it might not work
since the X server is also reading /dev/console ]

press any key (program terminates 10s after last keypress)...
keycode  28 release
keycode 164 press
keycode 164 release
keycode ??? press
keycode ??? release
```
The 164 is from when I press F9 on my Logitech keyboard.   The ??? is what the mouse button produces.

**Comment by pfps** [comment] 2024-03-04 14:28
If the ??? is 164 then something weird is going on.   If the ??? is some other number then the profile is telling the mouse button to produce something different that Linux doesn't understand.

**Comment by Waifu4Life** [comment] 2024-03-04 17:43
> If the ??? is 164 then something weird is going on. If the ??? is some other number then the profile is telling the mouse button to produce something different that Linux doesn't understand.

Hi there, thank you again for the reply. 164 is indeed the key that Linux sees for Play/Pause on my Keyboard when I hit Fn+F9. That being said, the Play/Pause on my mouse is not registering as anything under "sudo showkey --keycodes" command while the other keys mapped to my mouse did. I even went back into Windows, inverted the Play/Pause and another button to see, but same thing. Whatever Pay/Pause is doing in Windows is not being recognised in Linux and I'm assuming vice-versa. 

The built-in mouse button reconfiguration in KDE is hot garbage with limitations that doesn't work half the time, Piper has never worked for me and has not been updated in almost 2 years (dead project?), so unless Solaar can add button remapping, I'll need to find a way to map Play/Pause in Nobara to a set of key combo and then map that to the mouse button.

**Comment by pfps** [comment] 2024-03-04 21:06
It looks as if the current profile for your mouse is doing something different for the button.   What you should do is read up on profiles in https://pwr-solaar.github.io/Solaar/capabilities.   If you need further help post the profile dump here.

**Comment by Waifu4Life** [comment] 2024-03-04 21:33
> It looks as if the current profile for your mouse is doing something different for the button. What you should do is read up on profiles in https://pwr-solaar.github.io/Solaar/capabilities. If you need further help post the profile dump here.

How would one dump a profile?

**Comment by pfps** [comment] 2024-03-04 22:07
Read https://pwr-solaar.github.io/Solaar/capabilities

**Comment by pfps** [comment] 2024-03-08 20:36
Closing, as the initial topic is finished.

**Closed by pfps** 2024-03-08 20:36 UTC
Labels: enhancement
