### ISSUE TITLE
Chorded key press doesn't always hit all keys (?)

### ISSUE THREAD

**Issue by janlat** [pwr-Solaar/Solaar#2226] opened 2024-01-24 16:02 UTC
**Information**

- Solaar version: `solaar 1.1.9+git2025-4160b0e`
- Distribution: Ubuntu
- Kernel version: `Linux 6.5.0-14-generic x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar version 1.1.9+git2025-4160b0e

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : A2929342
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=173

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw2
     WPID         : 4082
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 55EDEBC3
     Model ID:      B02340820000
     Unit ID:       55EDEBC3
        Bootloader: BOT 95.01.B0015
          Firmware: MPM 19.01.B0015
             Other: 
     The power switch is located on the base.
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V3     
            Firmware: Bootloader BOT 95.01.B0015 00006A9CA89D
            Firmware: Firmware MPM 19.01.B0015 40826A9CA89D
            Firmware: Other   
            Unit ID: 55EDEBC3  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000} V1     
            Battery: 100%, discharging, next level 50%.
         9: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Mouse Gestures, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Diverted, Smart Shift:Regular}
        10: CHANGE HOST            {1814} V1     
            Change Host        : 1:ubuntu
        11: XY STATS               {2250} V1     
        12: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Ratcheted
            Scroll Wheel Ratcheted        : Ratcheted
            Scroll Wheel Ratchet Speed (saved): 10
            Scroll Wheel Ratchet Speed        : 10
        14: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: THUMB WHEEL            {2150} V0     
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
            Thumb Wheel Diversion (saved): True
            Thumb Wheel Diversion        : True
        16: WHEEL STATS            {2251} V0     
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V6    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:1890           {1890} V5    internal, hidden 
        25: unknown:1891           {1891} V5    internal, hidden 
        26: unknown:18A1           {18A1} V0    internal, hidden 
        27: unknown:1DF3           {1DF3} V0    internal, hidden 
        28: unknown:1E00           {1E00} V0    hidden 
        29: unknown:1EB0           {1EB0} V0    internal, hidden 
        30: unknown:1861           {1861} V0    internal, hidden 
        31: unknown:9001           {9001} V0    internal, hidden 
        32: unknown:9203           {9203} V0    internal, hidden 
        33: unknown:9205           {9205} V0    internal, hidden 
        34: unknown:9300           {9300} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted, raw XY diverted
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.
```
</details>

- Contents of `~/.config/solaar/config.yaml`:

<details>

```
- 1.1.9+git2025-4160b0e
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B02340820000
  _sensitive: {change-host: false, divert-keys: true, hires-scroll-mode: ignore, hires-smooth-invert: false, hires-smooth-resolution: false, scroll-ratchet: false,
    thumb-scroll-invert: false, thumb-scroll-mode: false}
  _serial: 55EDEBC3
  _unitId: 55EDEBC3
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 2, 196: 0}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: true
```
</details>

**Describe the bug**
I use these rules to switch between virtual desktops with the thumb wheel:
```
---
- Test: [thumb_wheel_down, 10]
- KeyPress:
  - [Super_L, Page_Up]
  - click
...
---
- Test: [thumb_wheel_up, 10]
- KeyPress:
  - [Super_L, Page_Down]
  - click
...
```
Generally, they work fine, however sometimes after the switch, the app which got focus also gets scrolled up/down. This looks like Page Up/Down is somehow pressed on its own (without the other key in the chord) for a brief moment (?)

**To Reproduce**
Seems random to me, so the only way I've found is just to scroll left & right really fast a dozen times until it finally happens

**Comment by pfps** [comment] 2024-01-24 17:32
This may be a timing issue with the program that intercepts these keystrokes.   

One thing you can do is check whether Solaar is simulating the keys correctly by running `solaar -ddd` and looking at the output at the time you move the thumbwheel.  You should see the key up and key down for both Super_L and Page_... each time.   If not, there is a problem with Solaar.  If you see that the simulated keystrokes are temporally mixed up then there is also a problem with Solaar.

Then see whether Linux input system is getting the keystrokes.  I think that this depends on whether you are running X and whether you are using uinput.   With X and not uinput you should be able to use `xinput` to check which input devices you have and then use `xinput test n` where n is the number for Virtual core XTEST keyboard.   With other setups you'll have to figure out how to do this.  (`xev` is likely not completely work, as the keystrokes don't get through to the end application, but you might use it as well to have another probe into what is happening.)

If everything appears to be working fine then the problem is likely timing.   I could add a very short delay between simulated keystrokes, if you are willing to test it out.

**Comment by janlat** [comment] 2024-01-27 18:55
So it simulates keystrokes properly most of the time
```
2024-01-25 11:35:17,479,479    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Test: thumb_wheel_down
2024-01-25 11:35:17,479,479     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['Super_L', 'Page_Up'] click, group 0, modifiers 0
2024-01-25 11:35:17,480,480    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 2 133
2024-01-25 11:35:17,481,481    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 2 112
2024-01-25 11:35:17,481,481    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 3 112
2024-01-25 11:35:17,481,481    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 3 133
...
2024-01-25 11:35:17,993,993    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Test: thumb_wheel_up
2024-01-25 11:35:17,993,993     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['Super_L', 'Page_Down'] click, group 0, modifiers 0
2024-01-25 11:35:17,994,994    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 2 133
2024-01-25 11:35:17,995,995    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 2 117
2024-01-25 11:35:17,995,995    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 3 117
2024-01-25 11:35:17,996,996    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 3 133
```
but I was able to catch two instances where it didn't
```
2024-01-25 11:35:17,281,281    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Test: thumb_wheel_up
2024-01-25 11:35:17,285,285     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['Super_L', 'Page_Down'] click, group 0, modifiers 64
2024-01-25 11:35:17,292,292    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 2 117
2024-01-25 11:35:17,292,292    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 3 117
...
2024-01-25 11:35:24,034,034    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Test: thumb_wheel_down
2024-01-25 11:35:24,037,037     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['Super_L', 'Page_Up'] click, group 0, modifiers 64
2024-01-25 11:35:24,039,039    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 2 112
2024-01-25 11:35:24,039,039    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f3a4370e860> 3 112
```
they happen right after "properly" simulated ones. Super is not pressed, but there's apparently some modifiers set (`Alt_L`?)

**Comment by pfps** [comment] 2024-01-27 19:29
Yes, the problem is likely that when Solaar checks what modifiers are on X11 responds with 64 but by the time Solaar simulates the keypress X11 has processed a (simulated) modifier release.  I guess the solution is to insert more checks and some short delays.  I'll have to think about what the best thing to do here is.

You could modify your rules to explicitly press and release the modifier key.   This should make the workspace switch always happen at the expense of logically unpressing any physically pressed Super key.

**Comment by pfps** [comment] 2024-01-27 20:43
Solaar is trying to solve a problem what would happen if it simulated a modifier key press and release while the modifier key is down on an actual keyboard.   If Solaar did this the X11 modifier would be unset, which would not be nice.  The problem is that any solution is going to have a race condition because there is a delay between (simulated) input and the effects of the input being visible in Solaar.

I don't see any decent way to get around this issue.  Any solution that helps in your case can cause more problems.  So my suggestion is to use explicit depress and release KeyPress actions, which bypass the checking.  Then you just need to remember that your rule will wipe out the effect of any physically pressed Super_L key.

**Comment by janlat** [comment] 2024-01-27 23:31
I see, thanks. The workaround works well

**Comment by pfps** [comment] 2024-01-28 00:23
OK, closing.

**Closed by pfps** 2024-01-28 00:23 UTC
Labels: bug
