### ISSUE TITLE
logitech K400 after some time the swap off configuration switch back

### ISSUE THREAD

**Issue by enricoT** [pwr-Solaar/Solaar#430] opened 2018-04-23 10:50 UTC
Hi, im using on archlinuxarm armv7h solaar:
`aur/solaar-git r930.dd2f884-1 [installed: r961.59b7285-1] (28) (1.90)
    Linux devices manager for the Logitech Unifying Receiver.`

the command is in .xinitrc

solaar config 0 fn-swap 0

before 

exec i3

it works, also if i use config 0 or config 1, but with same behaviour
after some time, the swap off is restored to 1 .
I teste turning off the screen/tv seems that is not the problem .There is something that restore in the same session X the swap to 1

**Comment by elstoc** [comment] 2018-04-30 19:28
Same issue here with the K400 plus and the latest master (fn-swap does not stay off). Also, when using my K400r (as well as my K400 plus) solaar gui thinks it's offline so I'm having to revert back to the last release and my K400r. This happens using the cli interface and also the GUI (when it occasionally thinks my keyboard is attached).

**Comment by elstoc** [comment] 2018-04-30 19:33
output of solaar show for my k400r

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 5A8A9B46
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=156

  1: Wireless Touch Keyboard K400
     Codename     : K400
     Kind         : keyboard
     Wireless PID : 4024
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: D1DF3A6D
          Firmware: RQK 50.01.B0013
     The power switch is located on the edge of top right corner.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: FEATURE INFO           {0002}   
         3: DEVICE FW VERSION      {0003}   
         4: DEVICE NAME            {0005}   
         5: BATTERY STATUS         {1000}   
         6: REPROG CONTROLS        {1B00}   
         7: REPROG CONTROLS V3     {1B03}   
         8: WIRELESS DEVICE STATUS {1D4B}   
         9: unknown:1DF0           {1DF0}   hidden
        10: unknown:1DF3           {1DF3}   internal, hidden
        11: unknown:1E00           {1E00}   hidden
        12: VERTICAL SCROLLING     {2100}   
        13: HI RES SCROLLING       {2120}   
        14: MOUSE POINTER          {2200}   
        15: FN INVERSION           {40A0}   
        16: NEW FN INVERSION       {40A2}   
        17: ENCRYPTION             {4100}   
        18: KEYBOARD LAYOUT        {4520}   
        19: TOUCHPAD FW ITEMS      {6010}   
        20: TOUCHPAD SW ITEMS      {6011}   
        21: TOUCHPAD WIN8 FW ITEMS {6012}   
     Has 18 reprogrammable keys:
         0: SHOW DESKTOP               => ShowDesktop                   is FN, reprogrammable
         1: METRO APPSWITCH            => MetroAppSwitch                is FN, reprogrammable
         2: METRO SEARCH               => MetroSearch                   is FN, reprogrammable
         3: METRO SHARE                => MetroShare                    is FN, reprogrammable
         4: METRO DEVICES              => MetroDevices                  is FN, reprogrammable
         5: METRO SETTINGS             => MetroSettings                 is FN, reprogrammable
         6: Previous                   => Previous                      is FN
         7: Play/Pause                 => Play/Pause                    is FN
         8: Next                       => Next                          is FN
         9: Mute                       => Mute                          is FN
        10: Volume Down                => Volume Down                   is FN
        11: Volume Up                  => Volume Up                     is FN
        12: MEDIA PLAYER               => Music                         nonstandard, reprogrammable
        13: Lock PC                    => WindowsLock                   nonstandard, reprogrammable
        14: SLEEP                      => Sleep                         nonstandard, reprogrammable
        15: LEFT CLICK                 => LeftClick                     mse
        16: LEFT CLICK                 => LeftClick                     mse
        17: RIGHT CLICK                => RightClick                    mse
```
Output of solaar show for K400 plus

```
  2: Wireless Touch Keyboard K400 Plus
     Codename     : Plus
     Kind         : keyboard
     Wireless PID : 404D
     Protocol     : HID++ 4.1
     Polling rate : 8 ms (125Hz)
     Serial number: C91FA95C
        Bootloader: BOT 22.01.B0001
          Firmware: RQK 63.01.B0014
             Other: 
     The power switch is located on the top edge.
     Supports 24 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: REPROG CONTROLS V4     {1B04}   
         8: SWAP BUTTON            {2005}   
         9: NEW FN INVERSION       {40A2}   
        10: ENCRYPTION             {4100}   
        11: KEYBOARD DISABLE       {4521}   
        12: TOUCHPAD RAW XY        {6100}   
        13: GESTURE 2              {6501}   
        14: DFUCONTROL 2           {00C1}   
        15: unknown:1811           {1811}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1DF3           {1DF3}   internal, hidden
        19: unknown:1E00           {1E00}   hidden
        20: unknown:1EB0           {1EB0}   internal, hidden
        21: unknown:1861           {1861}   internal, hidden
        22: unknown:18B0           {18B0}   internal, hidden
        23: unknown:1F11           {1F11}   internal, hidden
     Has 20 reprogrammable keys:
         0: unknown:00B8              , default: LeftClick                   => unknown:00B8              
             mse, divertable, pos:0, group:0, gmask:0
         1: BACK AS HID               , default: BackEx                      => BACK AS HID               
             is FN, FN sensitive, reprogrammable, divertable, pos:1, group:0, gmask:0
         2: MY HOME                   , default: HomePage                    => MY HOME                   
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, gmask:0
         3: Application Switcher      , default: Application Switcher        => Application Switcher      
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, gmask:0
         4: CONTEXTUAL MENU           , default: RightClick                  => CONTEXTUAL MENU           
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, gmask:0
         5: SEARCH                    , default: SearchForFiles              => SEARCH                    
             is FN, FN sensitive, reprogrammable, divertable, pos:5, group:0, gmask:0
         6: SHOW DESKTOP              , default: ShowDesktop                 => SHOW DESKTOP              
             is FN, FN sensitive, reprogrammable, divertable, pos:6, group:0, gmask:0
         7: WIN7 MAXIMIZE AS WIN ARROW, default: unknown:0095                => WIN7 MAXIMIZE AS WIN ARROW
             is FN, FN sensitive, reprogrammable, divertable, pos:7, group:0, gmask:0
         8: WIN7 SHOW PRESENTATION MODE, default: unknown:0093                => WIN7 SHOW PRESENTATION MODE
             is FN, FN sensitive, reprogrammable, divertable, pos:8, group:0, gmask:0
         9: MEDIA PLAYER              , default: Music                       => MEDIA PLAYER              
             is FN, FN sensitive, reprogrammable, divertable, pos:9, group:0, gmask:0
        10: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:10, group:0, gmask:0
        11: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:11, group:0, gmask:0
        12: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:12, group:0, gmask:0
        13: unknown:00B7              , default: ShowUI                      => unknown:00B7              
             divertable, pos:0, group:0, gmask:0
        14: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:0, gmask:0
        15: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:0, gmask:0
        16: Mute                      , default: Mute                        => Mute                      
             nonstandard, divertable, pos:0, group:0, gmask:0
        17: Volume Up                 , default: Volume Up                   => Volume Up                 
             nonstandard, divertable, pos:0, group:0, gmask:0
        18: Volume Down               , default: Volume Down                 => Volume Down               
             nonstandard, divertable, pos:0, group:0, gmask:0
        19: SLEEP                     , default: Sleep                       => SLEEP                     
             reprogrammable, divertable, pos:0, group:0, gmask:0
     Battery: 90%, discharging.

```

**Comment by elstoc** [comment] 2018-09-03 21:01
Seems to be resolved in latest git branch. Many thanks.

**Comment by pfps** [comment] 2020-01-12 23:50
OK, closing.  If the problem is still active in the version in this repo, please reopen this issue.

**Closed by pfps** 2020-01-12 23:50 UTC
