### ISSUE TITLE
Premature warning about battery low level.

### ISSUE THREAD

**Issue by KacperPerschke** [pwr-Solaar/Solaar#764] opened 2020-05-09 10:16 UTC
**Information**
- Solaar version 1.0.1+dfsg-4
- Distribution: Debian
- Kernel version (ex. `uname -srmo`): Linux 5.6.0-1-amd64 x86_64 GNU/Linux
- Output of `solaar show`:
nifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c526
  Serial       : 38627A73
    Firmware   : 05.00.B0023
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless (0x000100)

  1: VX Nano Cordless Laser Mouse
     Codename     : VX Nano
     Kind         : mouse
     Wireless PID : 100F
     Protocol     : HID++ 1.0
     Serial number: 38627A73
          Firmware: 07.00.B0025
     The power switch is located on the (nieznane).
     Notifications: battery status (0x100000).
     Battery: 85%, discharging.

**Describe the bug**
Solaar warns about low battery level when mouse reports 85% charge.

**To Reproduce**
1. Install sollar by apt.
2. Use Logitech VX Nano
3. Load new batteries
4. Wait couple of days
5. Observe warning sign.

**Screenshots**
![Solaar_warn](https://user-images.githubusercontent.com/1840255/81471047-b3064d00-91ee-11ea-88e3-63109ec7dcdb.png)

**Comment by pfps** [comment] 2020-05-09 12:51
This bug should be fixed by a recent PR.   Please download Solaar from this repository and try with this version.  For more information on using Solaar this way see https://pwr-solaar.github.io/Solaar/installation  As you are already running Solaar you should not need to use sudo or install the udev rule.

**Comment by pfps** [comment] 2020-05-26 00:56
Version 1.0.2 is available and should not have this problem (unless the problem is incorrect icons in your theme).

**Comment by pfps** [comment] 2020-06-04 11:52
Closing due to no response from submitter.

**Closed by pfps** 2020-06-04 11:52 UTC

**Comment by KacperPerschke** [comment] 2021-09-19 16:44
_I'm sorry for not responding._
Solaar 1.0.4 does **not** contain an error & works correctly.
