### ISSUE TITLE
Wrong name and battery status

### ISSUE THREAD

**Issue by mesb1** [pwr-Solaar/Solaar#550] opened 2019-08-04 09:48 UTC
HI.
I have Logitech MK240 keyboard and mouse combo with one big receiver.
On 0.9.2 and 1.0.1 i always have only 30% battery level with mouse and keyboard.
[debug.0.9.2.txt](https://github.com/pwr-Solaar/Solaar/files/3464773/debug.0.9.2.txt)
[debug.1.0.1.txt](https://github.com/pwr-Solaar/Solaar/files/3464774/debug.1.0.1.txt)

And for some reason solaar shows them as MK270 and M150.

But in real life on keyboard i got: K240
And on mouse i got: M212

Is there any way to get this fixed?

**Comment by pfps** [comment] 2019-12-23 23:12
Version 0.9.2 is old.  Please clone this repository and run solaar out of its bin directory.  If the problem is now fixed you can close this report.

**Comment by pfps** [comment] 2020-01-18 21:22
Closing due to no response.

**Closed by pfps** 2020-01-18 21:22 UTC
