### ISSUE TITLE
OSError exception in logitech_receiver/base.py

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#1092] opened 2021-02-27 12:09 UTC
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): **1.0.4**
- Distribution: **Fedora 33**
- Kernel version (ex. `uname -srmo`): **5.10.17-200.fc33.x86_64**
- Output of `solaar show`: **N/A** _(asked reporter to provide)_

**Describe the bug**
Solaar crashes with unhandled OSError exception.
```
Truncated backtrace:
base.py:262:_read:logitech_receiver.base.NoReceiver: {'reason': OSError(5, 'Input/output error')}

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 258, in _read
    data = _hid.read(int(handle), _MAX_READ_SIZE, timeout)
  File "/usr/lib/python3.9/site-packages/hidapi/udev.py", line 365, in read
    data = _os.read(device_handle, bytes_count)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/ui/__init__.py", line 154, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/usr/lib/python3.9/site-packages/solaar/ui/__init__.py", line 114, in _startup
    startup_hook()
  File "/usr/lib/python3.9/site-packages/solaar/listener.py", line 301, in start_all
    _process_receiver_event('add', device_info)
  File "/usr/lib/python3.9/site-packages/solaar/listener.py", line 377, in _process_receiver_event
    _start(device_info)
  File "/usr/lib/python3.9/site-packages/solaar/listener.py", line 286, in _start
    receiver.status.changed(True)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/status.py", line 307, in changed
    for s in d.settings:
  File "/usr/lib/python3.9/site-packages/logitech_receiver/device.py", line 341, in settings
    self._feature_settings_checked = _check_feature_settings(self, self._settings)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 763, in check_feature_settings
    setting = check_feature(device, name, featureId, featureFn)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 741, in check_feature
    if featureId not in device.features:
  File "/usr/lib/python3.9/site-packages/logitech_receiver/hidpp20.py", line 315, in __contains__
    reply = self.device.request(0x0000, _pack('!H', ivalue))
  File "/usr/lib/python3.9/site-packages/logitech_receiver/device.py", line 424, in request
    return _base.request(
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 399, in request
    reply = _read(handle, timeout)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 262, in _read
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': OSError(5, 'Input/output error')}

Local variables in innermost frame:
handle: <_ThreadedHandle(/dev/hidraw0)>
timeout: 4000
```

**To Reproduce**
_unknown, asked reporter to reproduce_

**Additional context**
[Downstream bug report (private)](https://bugzilla.redhat.com/show_bug.cgi?id=1933399).
Looks similar to the last one in #995 .

**Comment by pfps** [comment] 2021-02-27 13:05
This event appears to be happening after a resume when Solaar is trying to connect to all the receivers that where connected at the suspend.  One of the receivers is not connected so a read from the device fails.   I'll see what happens under these circumstances on my setup.

**Comment by pfps** [comment] 2021-02-27 13:27
It appears that the `--restart-on-wakeup` flag is required to cause this event.  I've not seen a need for this flag and it is marked experimental so my first suggestion is to just run Solaar without this flag.

**Comment by pfps** [comment] 2021-02-27 14:02
I have a potential fix for this problem, but I'm going to release 1.0.5 without it as my cure might cause Solaar to become unstable - instead of crashing immediately.

**Comment by rathann** [comment] 2021-03-21 19:49
> This event may be happening after a resume when Solaar is trying to connect to all the devices that eere connected at the suspend. One of the devices is not connected so a read from the device fails. I'll see what happens under these circumstances on my setup. It appears that the `--restart-on-wakeup` flag is required to cause this event at resume. I've not seen a need for this flag and it is marked experimental so if this is the case my first suggestion is to just run Solaar without this flag.

Solaar was invoked as `/usr/bin/solaar --window=hide` in this case, so I don't see how the `--restart-on-wakeup` flag comes into play here.

> Alternatively if this is happening at some other time it looks as if the problem is that somehow a device was detected but the first interaction with the device failed. This looks to be a rare event and I am unable to reproduce it and further it is unclear what should happen in this case.

I wonder if this is the case.

**Comment by pfps** [comment] 2021-03-21 20:24
Indeed I am not completely sure of the cause of the problem, but PR #1094 should provide a more graceful recovery.

**Comment by rathann** [comment] 2021-03-22 10:24
I have another downstream bug report for this: [#1940294](https://bugzilla.redhat.com/show_bug.cgi?id=1940294). I'll build a package with your PR and ask reporters to test it.

**Comment by rathann** [comment] 2021-03-22 10:57
One of the reporters said they have no Receiver attached, just a MX Master 3 mouse via Bluetooth and that solaar works fine otherwise. Does this help?

**Comment by pfps** [comment] 2021-03-22 12:42
The remediation should help in both cases.   There is the possibility that Solaar is trying to communicate with the device before it is ready (maybe because Solaar is too fast!).  It this is the case, the error should be largely repeatable (which should now produce a message, not a Python error report) but some different fix may be needed.

**Closed** 2021-04-05 02:33 UTC
Labels: bug
