### ISSUE TITLE
Ubuntu PPA out of date

### ISSUE THREAD

**Issue by asgrim** [pwr-Solaar/Solaar#165] opened 2014-05-28 07:10 UTC
https://launchpad.net/~daniel.pavel/+archive/solaar

I can see here that only Trusty has been updated recently - is there any chance of an updated version of Solaar past 0.9.2 to be released (`precise` in my case)?

``` bash
$ solaar-cli -V
solaar-cli 0.9.2
```

**Comment by mfonville** [comment] 2015-06-12 09:38
Also see https://github.com/pwr/Solaar/issues/181

**Comment by bdcomp** [comment] 2019-12-12 09:25
As this project just released new versions, an updated PPA will be very appreciated.

**Comment by FFY00** [comment] 2019-12-12 09:38
I am not releasing anything in a PPA as I don't use any debian based distro, I don't think @Lekensteyn will either as he is busy.

You should be able to manually install the package from Ubuntu 19.10 but that will come with no support from the package maintainers.

When you choose a distribution, one of the main things to take into account is the release cycle. If your distribution is not releasing fast enough for you then you should think about changing to another one, it is not up to us to fix it for you.

Closing this as the issue is really old and Solaar 1.0.1 is packaged in recent versions of all the major distributions and there's no manpower to maintain a PPA.

**Closed by FFY00** 2019-12-12 09:38 UTC

**Comment by muzena** [comment] 2019-12-12 10:27
@bdcomp @FFY00 
https://launchpad.net/~solaar-unifying
https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable
https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa

**Comment by bdcomp** [comment] 2019-12-12 10:31
@muzena thank you!
