### ISSUE TITLE
Fn key setting mysteriously changing for  Logitech ERGO K860 keyboard (Unifying)

### ISSUE THREAD

**Issue by atryastsyn** [pwr-Solaar/Solaar#1364] opened 2021-12-05 10:17 UTC
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.1.0
- Distribution:
- Kernel version (ex. `uname -srmo`): Linux 5.11.0-40-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 1028954D
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=114, 2=147

  1: Wireless Keyboard ERGO K860
     Device path  : /dev/hidraw7
     WPID         : 4088
     Codename     : ERGO K860
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 3F6E01A7
     Model ID:      B35940880000
     Unit ID:       3F6E01A7
        Bootloader: BL1 09.00.B0010
          Firmware: MPK 10.00.B0010
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 09.00.B0010 0000EC099C7F01
            Firmware: Firmware MPK 10.00.B0010 4088EC099C7F01
            Firmware: Other   
            Unit ID: 3F6E01A7  Model ID: B35940880000  Transport IDs: {'btleid': 'B359', 'wpid': '4088'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Keyboard ERGO K860
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: ERGO K860
         7: BATTERY STATUS         {1000}   
            Battery: 100%, discharging, next level 50%.
         8: REPROG CONTROLS V4     {1B04}   
         9: CHANGE HOST            {1814}   
            Change Host        : 1:novakid-thinkpad
        10: HOSTS INFO             {1815}   
            Host 0 (paired): novakid-thinkpad
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        11: K375S FN INVERSION     {40A3}   
            Swap Fx function (saved): False
            Swap Fx function        : False
        12: ENCRYPTION             {4100}   
        13: LOCK KEY STATE         {4220}   
        14: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {'1': False, '16': False, '2': False, '4': False, '8': False}
            Disable keys        : {'1': False, '2': False, '4': False, '8': False, '16': False}
        15: MULTIPLATFORM          {4531}   
            Set OS (saved): 0
            Set OS        : Windows
        16: DFUCONTROL SIGNED      {00C2}   
        17: DEVICE RESET           {1802}   internal, hidden
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: unknown:1813           {1813}   internal, hidden
        21: OOBSTATE               {1805}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1890           {1890}   internal, hidden
        24: unknown:1891           {1891}   internal, hidden
        25: unknown:18A1           {18A1}   internal, hidden
        26: unknown:1DF3           {1DF3}   internal, hidden
        27: unknown:1E00           {1E00}   hidden
        28: unknown:1EB0           {1EB0}   internal, hidden
        29: unknown:1861           {1861}   internal, hidden
        30: unknown:18B0           {18B0}   internal, hidden
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Multiplatform App Switch 2, default: App Switch                  => App Switch                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: MultiPlatform Search      , default: Multiplatform Search        => Multiplatform Search      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Fn Inversion/Hot Key      , default: Fn Inversion                => Fn Inversion              
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: unknown:0034              , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.
```
</details>

**Is your feature request related to a problem? Please describe.**
Almost everything works like a charm except I can not change FN keys behavior. It seems to me Solaar fails to store this setting.

Desirable settings:
![image](https://user-images.githubusercontent.com/2949865/144742393-e8834dd2-190a-4d69-8670-82e5b77c681b.png)

After reopen settings window:
![image](https://user-images.githubusercontent.com/2949865/144742380-4fc479c2-8859-4ac8-a979-f81d9eda5fb7.png)

**Comment by pfps** [comment] 2021-12-05 14:43
The ERGO K860 has the K375S FN INVERSION feature, which is used for the Swap Fx function setting.

The output of `solaar show` indicates that when it was run the setting was off.

```
        11: K375S FN INVERSION     {40A3}   
            Swap Fx function (saved): False
            Swap Fx function        : False
```

What is strange is that the displayed value for any setting should not change just by closing and reopening the Solaar main window.  In fact, Solaar very seldom reads from the device at all.

Please run Solaar as `solaar -dd` and post the output from the time that you see the main window with the desirable settings and the time that you see the main window with the switched settings.  That should show what is going on.

**Comment by atryastsyn** [comment] 2021-12-06 06:59
That's strange but now it works properly. Please wait for one week before closing this issue, maybe I will reproduce bug once again

**Comment by pfps** [comment] 2021-12-17 19:54
Closing for now.  If the bug reappears you can reopen this issue.

**Comment by xesarni** [comment] 2022-01-13 17:00
Solaar 1.1.1 and Logitech K400 Plus on Xubuntu 20.04.3

I have the Swap Fx function disabled and locked but sometimes it enables itself while the GUI shows it as disabled.

**Comment by pfps** [comment] 2022-01-13 18:00
What is happening when the Swap Fx function becomes enabled?  Does this happen while you are using the keyboard or does it happen when the keyboard wakes up after not being used for a while?  It would be useful to see the output of `solaar -ddd` when this happens.  (There will be a lot of output.)

**Comment by xesarni** [comment] 2022-01-13 19:21
It happens sometimes while I'm using it.
Also, and this is the best way to reproduce this issue, when the turned off keyboard is turned on before the PC is powered up.

**Comment by pfps** [comment] 2022-01-13 19:47
Hmm.  Please run Solaar with the `-ddd` option and capture its output and post when you encounter the problem.

**Comment by pfps** [comment] 2022-02-04 15:20
@xesarni Any updates?

**Comment by xesarni** [comment] 2022-02-04 16:35
The problem does not appear when I turn on the keyboard after the system (and Solaar) is loaded.

**Comment by pfps** [comment] 2022-02-04 18:59
@xesarni Please try to run `solaar -ddd` and capture the output when you encounter the problem.

**Comment by xesarni** [comment] 2022-02-05 12:05
Here's the output: [solaar.log](https://github.com/pwr-Solaar/Solaar/files/8007972/solaar.log)

**Comment by pfps** [comment] 2022-02-05 14:55
This log is missing lines that should be output if you are running version 1.1.1.  Please make sure that you are running that version and try again.   Also please include contents of 
~/.config/solaar/config.json

**Comment by pfps** [comment] 2022-02-05 15:10
Also fully describe the situation of the log.  What did you do from the time Solaar started and what was happening during the period of the log.

**Comment by pfps** [comment] 2022-02-28 17:41
Closing due to no information from submitter.   If you have the requested information, just add it here and reopen the issue.

**Closed by pfps** 2022-02-28 17:41 UTC
Labels: information needed
