### ISSUE TITLE
MX Master does not support Solaar mouse gestures

### ISSUE THREAD

**Issue by dvonessen** [pwr-Solaar/Solaar#1587] opened 2022-04-29 06:15 UTC
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.3
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): Linux 5.17.4-arch1-1 x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
Solaar version 1.1.3

USB and Bluetooth Devices

  1: Wireless Mouse MX Master
     Device path  : /dev/hidraw4
     USB id       : 046d:B012
     Codename     : MX Master
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B01240410000
     Unit ID:       3E9C68EF
        Bootloader: BOT 18.01.B0014
          Firmware: MPM 11.02.B0014
          Firmware: MPM 11.02.B0014
             Other: 
     Supports 28 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 18.01.B0014 40410862AB80
            Firmware: Firmware MPM 11.02.B0014 B0120862AB80
            Firmware: Firmware MPM 11.02.B0014 40410862AB80
            Firmware: Other   
            Unit ID: 3E9C68EF  Model ID: B01240410000  Transport IDs: {'btleid': 'B012', 'wpid': '4041'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse MX Master
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 50%, discharging, next level 20%.
         7: CHANGE HOST            {1814}   
            Change Host        : 1:heimdall
         8: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Diverted, Smart Shift:Diverted}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Diverted, Smart Shift:Diverted}
         9: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        10: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        11: SMART SHIFT            {2110}   
            Scroll Wheel Rachet (saved): 35
            Scroll Wheel Rachet        : 35
        12: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        13: GESTURE 2              {6501}   
            Gestures (saved): {45: True, 46: True}
            Gestures        : {46: True, 45: True}
            Gestures Diversion (saved): {46: False, 98: False, 211: False, 212: False}
            Gestures Diversion        : {46: False, 98: False, 211: False, 212: False}
        14: unknown:1813           {1813}   internal, hidden
        15: unknown:1830           {1830}   internal, hidden
        16: unknown:1890           {1890}   internal, hidden
        17: unknown:18A1           {18A1}   internal, hidden
        18: unknown:18C0           {18C0}   internal, hidden
        19: unknown:1DF3           {1DF3}   internal, hidden
        20: unknown:1E00           {1E00}   hidden
        21: unknown:1EB0           {1EB0}   internal, hidden
        22: unknown:1803           {1803}   internal, hidden
        23: unknown:1861           {1861}   internal, hidden
        24: unknown:9000           {9000}   internal, hidden
        25: unknown:9200           {9200}   internal, hidden
        26: unknown:9240           {9240}   internal, hidden
        27: OOBSTATE               {1805}   internal, hidden
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, pos:0, group:2, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button              => Gesture Button            
             mse, reprogrammable, divertable, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted
     Has 5 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled(   0): True   Diverted:(   0) False
        NaturalScrolling           Enabled(   1): True   Diverted:(None) None
        Finger9                    Enabled(None): None   Diverted:(   1) False
        unknown:00D3               Enabled(None): None   Diverted:(   2) False
        unknown:00D4               Enabled(None): None   Diverted:(   3) False
        period unit                Spec   (   3): 800
        DVI field width            Spec   (   1): 8
        field widths               Spec   (   2): 8
        resolution                 Spec   (   4): 2048
     Battery: 50%, discharging, next level 20%.
```
</details>

**Describe the bug**
Mouse Gestures not working. In "normal" mode for gesture button, the mouse pointer stops and while moving in any directory none of the configured `key press`'s are happening.
When gesture button is `diverted` while pressed the button `key press` is taken in effect but gestures not. 
The button press event shows:
```
08:05:25,027    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(255,B012,Wireless Mouse MX Master,)>: notification for feature REPROG CONTROLS V4, report 0, data 00C30000000000000000000000000000
08:05:25,027    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(255,B012,Wireless Mouse MX Master,)>: diverted controls pressed: 0xc3, 0x0, 0x0, 0x0
08:05:25,191    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (17) => r[11 FF 0800 00000000000000000000000000000000]
08:05:25,191    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(255,B012,Wireless Mouse MX Master,)>: notification for feature REPROG CONTROLS V4, report 0, data 00000000000000000000000000000000
08:05:25,191    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(255,B012,Wireless Mouse MX Master,)>: diverted controls pressed: 0x0, 0x0, 0x0, 0x0
```

`config.yaml`:

<details>

```
- 1.1.3
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-mode, thumb-scroll-invert,
    onboard_profiles, report_rate, pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    divert-crown, crown-smooth, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params]
  _modelId: B35B408A0000
  _unitId: 845AEDEE
  backlight: true
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: false
  multiplatform: 0
- _NAME: Wireless Mouse MX Master
  _absent: [hi-res-scroll, lowres-scroll-mode, thumb-scroll-mode, thumb-scroll-invert, onboard_profiles, report_rate, pointer_speed, dpi-sliding, speed-change,
    mouse-gestures, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, divert-crown, crown-smooth, divert-gkeys, m-key-leds,
    mr-key-led, multiplatform, gesture2-params]
  _modelId: B01240410000
  _sensitive: {divert-keys: true, dpi: false, gesture2-divert: false, gesture2-gestures: false, hires-scroll-mode: false, hires-smooth-invert: false, hires-smooth-resolution: false,
    reprogrammable-keys: false, smart-shift: false}
  _unitId: 3E9C68EF
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 1, 196: 1}
  dpi: 1000
  gesture2-divert: {46: false, 98: false, 211: false, 212: false}
  gesture2-gestures: {45: true, 46: true}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  smart-shift: 35
```

</details>

`rules.yaml`
<details>

```
%YAML 1.3
---
- Key: [Smart Shift, pressed]
- KeyPress: XF86_AudioPause
...
---
- Rule:
  - MouseGesture: Mouse Right
  - KeyPress: XF86_AudioNext
- Rule:
  - MouseGesture: Mouse Left
  - KeyPress: XF86_AudioPrev
- Rule:
  - MouseGesture: Mouse Up
  - KeyPress: XF86_AudioRaiseVolume
- Rule:
  - MouseGesture: Mouse Down
  - KeyPress: XF86_AudioLowerVolume
...
```

</details>

**Comment by pfps** [comment] 2022-04-29 11:20
What is happening is that Solaar does not recognize this mouse as one that can support the Mouse Gestures setting.  Compare the situation with your mouse and the MX Master 3, which does support the setting.  When the setting is on pressing the Mouse Gesture Button and moving the mouse results in:

```
07:09:05,565    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (15) => r[11 FF 0900 00C30000000000000000000000000000]
07:09:04,868    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: notification for feature REPROG CONTROLS V4, report 0, data 00C30000000000000000000000000000
07:09:04,869    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: diverted controls pressed: 0xc3, 0x0, 0x0, 0x0
07:09:05,280    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (15) => r[11 FF 0910 0001FFFF000000000000000000000000]
07:09:05,281    DEBUG [ReceiverListener:hidraw5] logitech_receiver.settings: dpi: settings read 1650 from <Device(255,B023,MX Master 3 Wireless Mouse,)>
07:09:05,281    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: notification for feature REPROG CONTROLS V4, report 0, data 0001FFFF000000000000000000000000
07:09:05,281    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: rawXY dx=1 dy=-1
07:09:05,281    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (15) => r[11 FF 0910 0000FFFF000000000000000000000000]
...
07:09:05,513    DEBUG [ReceiverListener:hidraw5] logitech_receiver.settings: dpi: settings read 1650 from <Device(255,B023,MX Master 3 Wireless Mouse,)>
07:09:05,513    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: notification for feature REPROG CONTROLS V4, report 0, data 00010000000000000000000000000000
07:09:05,513    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: rawXY dx=1 dy=0
07:09:05,565    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (15) => r[11 FF 0900 00000000000000000000000000000000]
07:09:05,566     INFO [ReceiverListener:hidraw5] logitech_receiver.settings_templates: mouse gesture notification [0]
07:09:05,566    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: notification for feature REPROG CONTROLS V4, report 0, data 00000000000000000000000000000000
07:09:05,566    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(255,B023,MX Master 3 Wireless Mouse,)>: diverted controls pressed: 0x0, 0x0, 0x0, 0x0
```

The core of the issue is that your mouse doesn't support rawXY reporting for the Mouse Gesture Button.  Contrast the relevant part of the `solaar show` output for the MX Master 3:
```
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted, raw XY diverted
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
```

So why does your mouse have a Mouse Gesture Button at all, if it works differently from the button on the MX Master 3?   That's a good question.  Maybe Logitech software intercepts regular mouse movement reports and doesn't pass them on when producing its analogue of Mouse Gestures.

So your mouse doesn't seem to be able to support Solaar Mouse Gestures.  Because of this there is no Mouse Gestures setting for your mouse even though it has a Mouse Gesture Button.

**Comment by pfps** [comment] 2022-05-08 12:57
Closing as there doesn´t appear to be anything to be done here.

**Comment by shahriar0247** [comment] 2022-09-06 12:38
so its almost impossible to do windows like gestures in linux with master 2s?

**Comment by pfps** [comment] 2022-09-06 13:24
Mouse gestures in Solaar depends on getting mouse movement reports through a special channel, which is present on some Logitech mice but not on the mouse of the original poster.  That said, the poster's mouse identifies as Wireless Mouse MX Master, not a 2S.  If you have a different mouse then mouse gestures might be possible.  Provide the output of `solaar show` for your mouse if you want to pursue this further.

**Comment by pfps** [comment] 2022-09-06 18:03
@shahriar0247  Please provide the output of `solaar show` for your mouse if you want to pursue this further.

**Comment by timkrief** [comment] 2023-02-10 21:51
I have the MX Master 2S, here's the output for solaar show:

```
solaar version 1.1.8

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 37819F7F
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=92

  1: Wireless Mouse MX Master 2S
     Device path  : /dev/hidraw1
     WPID         : 4069
     Codename     : MX Master 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 11D37C0A
     Model ID:      B01940690000
     Unit ID:       911830CE
        Bootloader: BOT 56.01.B0006
          Firmware: MPM 12.01.B0006
          Firmware: MPM 12.01.B0006
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BOT 56.01.B0006 406916A9FC5401
            Firmware: Firmware MPM 12.01.B0006 B01916A9FC5401
            Firmware: Firmware MPM 12.01.B0006 406916A9FC5401
            Firmware: Other   
            Unit ID: 911830CE  Model ID: B01940690000  Transport IDs: {'btleid': 'B019', 'wpid': '4069'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master 2S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V0     
         7: BATTERY STATUS         {1000} V0     
            Battery: 50%, discharging, next level 20%.
         8: CONFIG DEVICE PROPS    {1806} V0    internal, hidden 
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:Metroid
        10: REPROG CONTROLS V4     {1B04} V3     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        11: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1100
            Sensitivity (DPI)        : 1100
        12: VERTICAL SCROLLING     {2100} V0     
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Ratcheted
            Scroll Wheel Ratcheted        : Ratcheted
            Scroll Wheel Ratchet Speed (saved): 39
            Scroll Wheel Ratchet Speed        : 39
        14: HIRES WHEEL            {2121} V0     
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: GESTURE 2              {6501} V0     
            Gestures (saved): {45: True, 46: True}
            Gestures        : {46: True, 45: True}
            Gestures Diversion (saved): {46: False}
            Gestures Diversion        : {46: False}
        16: DFUCONTROL SIGNED      {00C2} V0     
        17: unknown:1813           {1813} V0    internal, hidden 
        18: unknown:1830           {1830} V0    internal, hidden 
        19: unknown:1890           {1890} V0    internal, hidden 
        20: unknown:1891           {1891} V0    internal, hidden 
        21: unknown:18A1           {18A1} V0    internal, hidden 
        22: unknown:18C0           {18C0} V0    internal, hidden 
        23: unknown:1DF3           {1DF3} V0    internal, hidden 
        24: unknown:1E00           {1E00} V0    hidden 
        25: unknown:1EB0           {1EB0} V0    internal, hidden 
        26: unknown:1803           {1803} V0    internal, hidden 
        27: unknown:1861           {1861} V0    internal, hidden 
        28: unknown:9001           {9001} V0    internal, hidden 
        29: unknown:9200           {9200} V0    internal, hidden 
        30: unknown:9202           {9202} V0    internal, hidden 
        31: OOBSTATE               {1805} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled(   0): True   Diverted:(   0) False
        NaturalScrolling           Enabled(   1): True   Diverted:(None) None
        period unit                Spec   (   3): 800
        DVI field width            Spec   (   1): 8
        field widths               Spec   (   2): 8
        resolution                 Spec   (   4): 2048
     Battery: 50%, discharging, next level 20%.


```

**Comment by pfps** [comment] 2023-02-10 22:10
The 2S should support mouse gestures.  What is needed is a button that has both divertable and raw XY.  The Key/Button Diversion setting should provide Mouse Gestures values for some buttons.

**Closed** 2023-02-10 22:11 UTC

**Comment by timkrief** [comment] 2023-02-10 22:46
Thanks! I finally found out that you have to specify this for it to work: 
![image](https://user-images.githubusercontent.com/14089949/218214947-75533961-7937-4810-a793-4c7ddc15bdf5.png)
It works

**Comment by Zarubaxa** [comment] 2024-10-07 14:45
> Спасибо! Я наконец узнал, что нужно указать это, чтобы это работало: Это работает ![изображение](https://user-images.githubusercontent.com/14089949/218214947-75533961-7937-4810-a793-4c7ddc15bdf5.png)

i made the same, but gestures dont work
