### ISSUE TITLE
Wrong icons in GNOME 3

### ISSUE THREAD

**Issue by AlexWayfer** [pwr-Solaar/Solaar#456] opened 2018-08-16 10:23 UTC
Adwaita (full default): 

![image](https://user-images.githubusercontent.com/6510020/44201662-7ceb8480-a152-11e8-8811-c0b8745e54be.png)

[Materia](https://github.com/nana-4/materia-theme) + [Paper icons](https://github.com/snwh/paper-icon-theme):

![image](https://user-images.githubusercontent.com/6510020/44203345-49f7bf80-a157-11e8-8be8-bfcf1c43871d.png)

It was light-gray, as others. 

I think it's not theme issue because it's black with any theme, even default.

After upgrade from `r961.59b7285` to `r985.b852903`.

**Comment by Lekensteyn** [comment] 2018-08-16 16:02
This is probably caused by b5d43cd (via #295 by @cschreib).

All icons seem however present with the Adwaita theme. Do you get any errors? If you strace Solaar, can you figure out which files it tried? If you revert that commit, how will it look like?

**Comment by AlexWayfer** [comment] 2018-08-16 16:13
> This is probably caused by b5d43cd (via #295 by @cschreib).

Yep, looks like this.

> Do you get any errors?

No.

> If you strace Solaar, can you figure out which files it tried?

I don't know how to strace, sorry. Do you have any guide for this?

But I saw in this repo how to enable debug logs:

```
19:07:06,605    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/bin
19:07:06,606    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/icons
19:07:06,606    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
19:07:06,606    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/alex/.local/share/solaar/icons
19:07:06,606    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
19:07:06,606    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
19:07:06,606    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/alex/.local/share/icons', '/home/alex/.icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
19:07:06,617    DEBUG [MainThread] solaar.ui.icons: detected icon sets: Mint True, gpm True, oxygen False, gnome True, elementary True
```

So, yes, it finds `Mint` icons. I don't know how — I don't have installed anything with `mint`.

> If you revert that commit, how will it look like?

It looks OK, light-gray. Debug log:

```
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /home/alex/Projects/Solaar/lib
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/alex/Projects/Solaar/icons
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/alex/Projects/Solaar/share/solaar/icons
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/alex/.local/share/solaar/icons
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
19:12:26,279    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/home/alex/Projects/Solaar/share/solaar/icons', '/home/alex/.local/share/icons', '/home/alex/.icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
19:12:26,290    DEBUG [MainThread] solaar.ui.icons: detected icon sets: gpm True, oxygen False, gnome True, elementary True
```

**Comment by Lekensteyn** [comment] 2018-08-17 10:40
> So, yes, it finds Mint icons.

It is a misnomer, it actually looks for names that are part of the Adwaita theme in GNOME. As for strace, close existing solaar instances and run:

    strace -e file -o strace.txt solaar

Then inspect the (large) strace.txt file for paths containing `battery-good-symbolic`.

**Comment by AlexWayfer** [comment] 2018-08-17 14:06
> Then inspect the (large) strace.txt file for paths containing battery-good-symbolic.

Not found, only `battery-full-symbolic`: [strace.txt](https://github.com/pwr/Solaar/files/2297502/strace.txt)

**Comment by Lekensteyn** [comment] 2018-08-17 22:36
Can you post a strace with the faulty commit reverted?

**Comment by AlexWayfer** [comment] 2018-08-18 10:11
Yes, I can on Monday (this computer at work 😬 ).

**Comment by hxss** [comment] 2018-08-18 15:15
@Lekensteyn my strace also contain only battery-full-symbolic.
[strace.txt](https://github.com/pwr/Solaar/files/2299643/strace.txt)

**Comment by AlexWayfer** [comment] 2018-08-21 11:34
> Can you post a strace with the faulty commit reverted?

Here it's: 
[strace.txt](https://github.com/pwr/Solaar/files/2306073/strace.txt)

**Comment by AlexWayfer** [comment] 2018-08-30 07:58
Also, for 50% icon. How it was (or how it's with reverted commit):

![image](https://user-images.githubusercontent.com/6510020/44837893-83dec080-ac43-11e8-9210-8f5e4f1d35c5.png)

How it's now:

![image](https://user-images.githubusercontent.com/6510020/44837919-92c57300-ac43-11e8-924c-e6ce3cf6682a.png)

![image](https://user-images.githubusercontent.com/6510020/44837946-a40e7f80-ac43-11e8-90af-0a2ff1ab3965.png)

It doesn't look like a half.

**Comment by dmradcilff** [comment] 2018-11-06 14:46
Seeing incorrect icons in Fedora 29 also.  When I query the status either from the command line or using the GUI my battery is at 70%.
![image](https://user-images.githubusercontent.com/34752304/48071610-b7404d00-e1a8-11e8-8016-488075178b4c.png)

**Comment by philfry** [comment] 2018-12-10 13:34
Same here… Fedora 29 using `solaar-0.9.2-10.20180813gitf0fc63e.fc29.noarch`
![screenshot from 2018-12-10 14-33-36](https://user-images.githubusercontent.com/1649785/49735854-bce9f080-fc88-11e8-9c89-3b3e0a573423.png)

**Comment by ZachCook** [comment] 2019-07-29 03:31
#543 fixes using the wrong icons for battery levels >20 and <90

**Comment by rgarcia7** [comment] 2019-08-03 00:29
#548 Fixes this by checking the current loaded theme
This way you can use Mint Icons if available or use the regular ones available in all themes and distros
Mint Example:
Window:
![window-example](https://user-images.githubusercontent.com/29512992/62404448-8df2f880-b551-11e9-919c-486e4ba5ddc8.png)

Taskbar:
![task-bar-example](https://user-images.githubusercontent.com/29512992/62404366-e8d82000-b550-11e9-84a1-c6ac29adec58.png)

Mouse Icons:
![mouse-battery-empty](https://user-images.githubusercontent.com/29512992/62404406-440a1280-b551-11e9-8f36-e498e830c436.png)
![mouse-battery-medium](https://user-images.githubusercontent.com/29512992/62404408-47050300-b551-11e9-90d8-7a37f2b76ab0.png)
![mouse-battery-full](https://user-images.githubusercontent.com/29512992/62404409-48363000-b551-11e9-8f4d-b10a36f79783.png)

**Comment by pfps** [comment] 2020-01-16 23:47
#548 should have solved the problem.  If not, you can reopen this issue.

**Comment by AlexWayfer** [comment] 2020-01-17 00:10
> #548 should have solved the problem.

Not merged PR should have solved the problem… how?

**Comment by pfps** [comment] 2020-01-17 00:35
Oops, my bad.  I looked at CLOSED and didn't notice that it had not been merged.  My apologies.  I'm reopening.

**Comment by pfps** [comment] 2020-01-17 00:52
Solaar is trying to adapt its battery icon names to the current theme. Unfortunately, the debugging logging that would show just what name is being used has been commented out.  strace shows which files have been accessed but not why they were accessed.
If you can run solaar from this repository then you uncomment this debugging.  Just uncomment the two commented lines in the battery function in lib/solaar/ui/icons.py
Then run solaar -dd
This will produce a lot of output.  What is of interest are the lines from this logging output, i.e., lines containing "battery icon for".
This will show what solar thinks of the battery and which icon name it will use.

For example, what I see are 
19:46:34,188    DEBUG [MainThread] solaar.ui.icons: battery icon for None:None = battery-missing-symbolic
19:46:35,205    DEBUG [MainThread] solaar.ui.icons: battery icon for good:False = battery-good-symbolic
which look appropriate to me.

**Comment by pfps** [comment] 2020-01-17 02:18
I see that there might be progress with #548, so I suggest waiting to see if that comes to fruition.

**Comment by pfps** [comment] 2020-04-20 21:38
If anyone is still experiencing this problem please try out the proposed solution in #746

**Comment by pfps** [comment] 2020-04-21 14:54
@AlexWayfer  @philfry @dmradcilff I installed 1.0.1 on a different machine and noticed the problem with icons that do not reflect the actual battery level.  This has since been fixed.  If you are still experiencing the problem, please clone and try out Solaar from this repository.

**Closed** 2020-05-02 14:28 UTC
Labels: bug
