### ISSUE TITLE
Feature Persistent Remappable Action {1C00}

### ISSUE THREAD

**Issue by adatum** [pwr-Solaar/Solaar#832] opened 2020-07-01 01:36 UTC
It would be great to have persistent key or button remappings, which survive the device being turned off/on if Solaar is not running. See also https://github.com/pwr-Solaar/Solaar/issues/519#issuecomment-652018424 and related to https://github.com/pwr-Solaar/Solaar/issues/582#issue-530642547

**Information**
- Output of `solaar show` for the target device (if applicable):

```
> M720 Triathlon Multi-Device Mouse
>      Codename     : M720 Triathlon
>      Kind         : mouse
>      Wireless PID : 405E
>      Protocol     : HID++ 4.5
>      Polling rate : 8 ms (125Hz)
>      Serial number: C00C3906
>         Bootloader: BOT 34.00.B0004
>           Firmware: MPM 04.02.B0009
>              Other: 
>      The power switch is located on the base.
>      Supports 35 HID++ 2.0 features:
>          0: ROOT                   {0000}   
>          1: FEATURE SET            {0001}   
>          2: DEVICE FW VERSION      {0003}   
>          3: DEVICE NAME            {0005}   
>          4: WIRELESS DEVICE STATUS {1D4B}   
>          5: RESET                  {0020}   
>          6: CRYPTO ID              {0021}   
>          7: DEVICE FRIENDLY NAME   {0007}   
>          8: BATTERY STATUS         {1000}   
>          9: CHANGE HOST            {1814}   
>         10: HOSTS INFO             {1815}   
>         11: REPROG CONTROLS V4     {1B04}   
>             Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93, '208': 208}
>         **12: PERSISTENT REMAPPABLE ACTION {1C00}**   
>         13: POINTER SPEED          {2205}   
>             Pointer Speed: 1.0
>             Sensitivity (Pointer Speed): 256
>         14: VERTICAL SCROLLING     {2100}   
>             Roller type: 3G
>             Ratchet per turn: 24
>             Scroll lines: 0
>         15: DFUCONTROL UNSIGNED    {00C1}   
>         16: DFUCONTROL SIGNED      {00C2}   
>         17: DEVICE RESET           {1802}   internal, hidden
>         18: unknown:1803           {1803}   internal, hidden
>         19: CONFIG DEVICE PROPS    {1806}   internal, hidden
>         20: OOBSTATE               {1805}   internal, hidden
>         21: unknown:1813           {1813}   internal, hidden
>         22: unknown:1830           {1830}   internal, hidden
>         23: unknown:1861           {1861}   internal, hidden
>         24: unknown:1890           {1890}   internal, hidden
>         25: unknown:1891           {1891}   internal, hidden
>         26: unknown:18A1           {18A1}   internal, hidden
>         27: unknown:1DF3           {1DF3}   internal, hidden
>         28: unknown:1E00           {1E00}   hidden
>         29: unknown:1EB0           {1EB0}   internal, hidden
>         30: unknown:18B1           {18B1}   internal, hidden
>         31: unknown:1850           {1850}   internal, hidden
>         32: unknown:1F03           {1F03}   internal, hidden
>         33: unknown:18C0           {18C0}   internal, hidden
>         34: HIRES WHEEL            {2121}   
>             Multiplier: 8
>             Has invert
>               Normal wheel motion
>             Has ratchet switch
>               Free wheel mode
>             High resolution mode
>             HID notification
>             High Resolution Wheel Invert: False
>             Wheel Resolution: True
>      Has 9 reprogrammable keys:
>          0: Left Button               , default: Left Click                  => Left Button               
>              mse, reprogrammable, pos:0, group:1, gmask:1
>          1: Right Button              , default: Right Click                 => Right Button              
>              mse, reprogrammable, pos:0, group:1, gmask:1
>          2: Middle Button             , default: Mouse Middle Button         => Middle Button             
>              mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
>          3: Back Button               , default: Mouse Back Button           => Back Button               
>              mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
>          4: Forward Button            , default: Mouse Forward Button        => Forward Button            
>              mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
>          5: Left Tilt                 , default: Mouse Scroll Left Button    => Left Tilt                 
>              mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
>          6: Right Tilt                , default: Mouse Scroll Right Button   => Right Tilt                
>              mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
>          7: Multiplatform gesture button, default: Multiplatform Gesture Button => Multiplatform gesture button
>              mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
>          8: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
>              divertable, virtual, pos:0, group:3, gmask:0
>      Battery: 50%, discharging, next level 20%.
```

**Comment by pfps** [comment] 2020-07-02 11:52
The documentation for this feature showed up quickly.  Implementing it might take quite a few interactions, as I don't have a device with the feature.  The first step is to dump the relevant feature data, which I already implemented in PR #834.  Please run this pull request and report back the results there.

**Comment by adatum** [comment] 2020-07-02 18:17
> KEYS ARRAY PERSISTENT init 8
>      Has 8 persistent remappable keys:
> KEYS ARRAY PERSISTENT getitem keydata 00:50:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:50:01:02:00:01:00:00:00:00:00:00:00:00:00:00
>          0: Left Button                => code 1 actionId 2 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:51:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:51:01:02:00:02:00:00:00:00:00:00:00:00:00:00
>          1: Right Button               => code 2 actionId 2 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:52:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:52:01:02:00:04:00:00:00:00:00:00:00:00:00:00
>          2: Middle Button              => code 4 actionId 2 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:53:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:53:01:02:00:08:00:00:00:00:00:00:00:00:00:00
>          3: Back Button                => code 8 actionId 2 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:56:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:56:01:02:00:10:00:00:00:00:00:00:00:00:00:00
>          4: Forward Button             => code 10 actionId 2 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:5b:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:5b:01:06:40:00:00:00:00:00:00:00:00:00:00:00
>          5: Left Tilt                  => code 4000 actionId 6 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:5d:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:5d:01:06:80:00:00:00:00:00:00:00:00:00:00:00
>          6: Right Tilt                 => code 8000 actionId 6 modifiers 0 status 0
> KEYS ARRAY PERSISTENT getitem keydata 00:d0:00:00:00:00:00:00:00:00:00:00:00:00:00:00
> KEYS ARRAY PERSISTENT getitem mapdata 00:d0:01:01:00:2b:05:00:00:00:00:00:00:00:00:00
>          7: Multiplatform gesture button => code 2b actionId 1 modifiers 5 status 0

**Comment by pfps** [comment] 2020-07-02 19:57
That's interesting.  It looks as if you could reprogram any of your mouse buttons to be any button, any key, or any scroll action. Reprogramming the left button to space would be a good way to lock you out of your system if you didn't have another mouse.

**Comment by pfps** [comment] 2020-07-02 19:59
The weird thing is that this is a completely different setup than the reprogrammable keys features.

**Comment by adatum** [comment] 2020-07-02 20:02
> It looks as if you could reprogram any of your mouse buttons to be any button, any key, or any scroll action.

Very nice. Could they also be reprogrammed to a key combination, eg. Alt-Tab ?

**Comment by pfps** [comment] 2020-07-02 22:18
A modified key combination, yes.  The last button defaults to control-alt-tab.  But I don't think you can do multiple regular keys.

**Comment by pfps** [comment] 2020-07-03 11:35
The problem is going to be coming up with a reasonable interface.   A simple choice box is not going to be adequate as there are thousands of options.

**Comment by adatum** [comment] 2020-07-03 23:23
> The problem is going to be coming up with a reasonable interface.

Yes, I was wondering about that. What about something like the interface for creating keyboard shortcuts? I'm not sure how easy or difficult this would be to implement.

![keyboard_shortcuts](https://user-images.githubusercontent.com/9773655/86500848-12ea2180-bd62-11ea-833f-7368aff753b1.png)
Importantly, with a "reset to default" either for individual buttons or all at once, especially to avoid getting stuck without a left click.

**Comment by pfps** [comment] 2020-07-04 02:00
Problem 1: I think that you will often want to turn a key into a key you don't have, which I don't think is possible with this interface.
Problem 2: As soon as lose left-click you can't do a "reset to default" --- because you don't have left-click to activate it.

**Comment by adatum** [comment] 2020-07-04 02:29
Good points. 

RE: Problem 1: Maybe have a drop down list of such keys as an alternative to direct input? Problem is coming up with a good list, and the added complication to the interface. Or, type the key names instead of pressing them? Problem is input validation.

RE: Problem 2: Use keyboard Tab and Enter to reach and activate "reset"? And/or have a timed "Do you really want to accept this change" dialog? Adds complications, and I don't see how to make this 100% foolproof.

**Comment by barolo** [comment] 2020-07-04 12:24
The most common desktop interface for custom shortcuts is just an input field with keystroke detection, Logitech Options are like that and System Settings are like that too, commonly

**Comment by pfps** [comment] 2020-07-04 13:40
System Settings has the problem that you can't set a key to be a key that you don't have, which is likely to be a major use case for this feature.  
How does Logitech Options set a key to a key you don't have?

**Comment by pfps** [comment] 2020-07-04 13:42
Maybe a way to go for key selection is to allow typing but with completion from the list of key names.

**Comment by barolo** [comment] 2020-07-04 14:21
> How does Logitech Options set a key to a key you don't have?

Not sure I understand what you mean

**Comment by pfps** [comment] 2020-07-04 15:41
This feature should be able to remap a key (like Volume Down) to a key you don't have (like Pause).

**Comment by barolo** [comment] 2020-07-04 18:11
> This feature should be able to remap a key (like Volume Down) to a key you don't have (like Pause).

Ok, L.O. doesn't really offer it for something predefined that you don't have. Still it has crazy amount of options per key. It uses list with radioboxes per each item which are expanded where it's applicable, for things like modifiers and keystroke assignment, you can even assign folders to them.
![logitech-logi-options](https://user-images.githubusercontent.com/1215421/86518556-93785300-be32-11ea-9684-45eca0033764.png)

**Comment by adatum** [comment] 2020-07-04 18:24
Having a suitable list of predefined actions, which might be modified over time, plus the option to assign custom keystrokes, seems pretty good to me.

**Comment by pfps** [comment] 2020-07-05 11:59
The trouble with typing at a box and collecting that keystroke is that to do it right requires taking over the lowest levels of the input driver (and even that isn't always sufficient).   Some keys do special things (like the media keys) so this should be turned off.  Some keys (like power keys, sometimes) create ACPI events which aren't even seen as keystrokes.

Here is what can be done, I think.  Select from a list of all the "possible" keystrokes (depending on what counts, there are about 1000 of them).  But also allow typing the "name" of the keystroke with a popup showing which keystrokes start with characters entered so far.  I have this about 90% working.

**Comment by barolo** [comment] 2020-07-05 12:22
I was looking at how KDE/Plasma system settings does this and weirdly enough, keys like "show desktop" are registered as "Meta + D" and can't be remapped since Plasma detects properly that it's bound to "show desktop" function already.
I agree, let's see what can be done and if it works first.

**Comment by pfps** [comment] 2020-07-05 12:53
I implemented the fancier selection in #834.   Remappable key actions use this selection mechanism so you can see how it works. 
There are a few things that don't work as well as they should, but I'm not a GTK expert so I'm not sure how to make the interface better.   Three things that would be nice are automatic completion, automatic selection if there is only one completion, and undoing characters that result in no completions.

**Comment by barolo** [comment] 2020-07-05 16:35
Yeah, now it's a hybrid combo/input field. It's not very useful till we get custom mappings, no? I've noticed that thumb button on MX Master got renamed to "App Switch Gesture" which really confused me, since there's no support for gestures.

**Comment by pfps** [comment] 2020-07-05 17:46
It's not useful for a smell or medium number of mappings.  I suppose that text input could be enabled only if there are lots of mappings.
I received a list of official names for the keys which has this key as "App Switch Gesture" so that's what it is called (for now).

**Comment by pfps** [comment] 2022-01-01 01:50
PR #1407 has an initial implementation of this feature.  Because the changes are persistent Solaar does not keep track of the remappings between runs, instead reading the current values from the device.  Solaar also only writes to the device when a key is remapped, resulting in a lot fewer writes for the feature.   The implementation only works for devices that can remap to HID and Consumer codes, which should be most keyboards with this feature.  The interface uses a Gtk Entry box, which allows typing in the name of an HID key or Consumer control.  Seeing the options requires entering at least one letter of the name, as there are over 2000 possibilities (and that is even ignoring several thousand that don't make much sense).

The interface allows remapping the key back to its default setting, pseudo-value 'Default'.   It would be better if this resulted in the actual default mapping showing in the Solaar GUI but this remains to be done.  The next time Solaar is run it will show the mapping.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1407, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1407/head:pull_1407
git checkout pull_1407
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1407
git fetch origin pull/1407/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment] 2022-03-07 23:54
PR #1407 should fix this problem, but it won't be merged in for now unless there is some independent testing done on it.

**Comment by adatum** [comment] 2022-03-09 04:18
@pfps Thanks for the detailed instructions. 
I fetched and ran the latest commit (commit 810f750ad216da2b511ea9f6e25135f0048be0ac). I might be doing something wrong, but the changed button action (Multiplatform Gesture Button mapped to Mouse Middle Button) does not persist if the mouse (M720) is powered off then on again and if Solaar is not running. 
If Solaar is started, then the remapped button/action takes effect.
![solaar](https://user-images.githubusercontent.com/9773655/157371514-5fa4538e-2048-4e65-969f-765c772a63ea.png)

**Comment by pfps** [comment] 2022-03-09 07:09
There are two device features that cause key remappings and thus two settings.  The one that persists has setting Persistent Key/Button Mapping, which is not showing for you.   It may be that there is a bug in the new setting that is causing it to not work for your device.
Please provide output of `bin/solaar show` and contents of `~/.config/solaar/config.json`.  You could also try the next step, which would be to edit config.json to remove any entries for "_absent" and then run Solaar as `bin/solaar -dd` (after killing any running Solaar processes).

**Comment by adatum** [comment] 2022-03-09 08:16
[bin/solaar show](https://gist.github.com/adatum/8f148a9e7fa4a42604f0c451c361c2b5)
[config.json](https://gist.github.com/adatum/3fe1283bc8f271c95a4d29ddb66fc58b)

After removing "_absent" entries (i.e. "_absent": [], ...), I still do not see a Persistent Key/Button Mapping option: 
[bin/solaar -dd](https://gist.github.com/adatum/c464afaa49708f06d820f0ad1268df31)

When solaar is run, the "_absent" entries are repopulated as before.

**Comment by pfps** [comment] 2022-03-09 14:11
What appears to have happened is that the change in the PR no longer works correctly with the other changes to Solaar.

**Comment by pfps** [comment] 2022-03-09 15:13
@adatum Your debug output has uncovered a different bug in Solaar.  Please see Issue #1484 and test out PR #1485

**Comment by pfps** [comment] 2022-03-09 15:28
@adatum Your keyboard appears to be producing output that Solaar does not expect.  Please provide the output from `bin/solaar -ddd show` after removing "_absent" entries from config.json

**Comment by adatum** [comment] 2022-03-09 19:19
Output from `bin/solaar -ddd show` for pull_1407 (1.1.1-124-ga683e99) after removing "_absent" entries from config.json: https://gist.github.com/adatum/188a43891ee781fcff92bc425a4fb0c4

"_absent" entries were repopulated upon running Solaar.

**Comment by pfps** [comment] 2022-03-09 20:19
@adatum One of the errors appears to be caused by old bad data in a setting.  I think that the bad data doesn't cause any problem, but please remove the "divert-keys" entry for your mouse, kill Solaar, and then run Solaar as `bin/solaar -ddd`.   Take a screenshot of the main window with the mouse shown and post the screenshot, the contents of config.json, and the output from Solaar.

**Comment by pfps** [comment] 2022-03-09 20:42
@adatum Your config.json file appears to be corrupted.  It appears to have four entries for two K830s and two M720s overall.  That's OK, but one of the K830s and one of the M720s appear to share the same serial number, which seems suspect.  Please try with only one M720 entry and no '_absent' field in it.

**Comment by adatum** [comment] 2022-03-09 21:20
@pfps I have one K830 and one M720, though I have previously used them with two different Unifying receivers if that makes a difference. Would it help to clear old bad data? Perhaps deleting config.json or otherwise?

**Comment by pfps** [comment] 2022-03-09 21:51
Using different receivers should not cause a problem.  You could try deleting config.json entirely.  In fact that would be a good test as there are some things that Solaar only does when information is not present in config.json

**Comment by pfps** [comment] 2022-03-09 21:52
By the way, Solaar has to take care when determining the identity of a device.  At some times there were bugs in this determination, which may be why you have extra entries.

**Comment by adatum** [comment] 2022-03-10 05:09
`bin/solaar -ddd` output for pull_1407 (1.1.1-124-ga683e99) after deleting config.json: https://gist.github.com/adatum/79246b60f6ca42d08e37c8e8deaca775

config.json generated by Solaar on first run:  https://gist.github.com/adatum/ce5c3bcabe572a39f67eab0403405211

![solaar_m720](https://user-images.githubusercontent.com/9773655/157593725-1f3198ce-618a-444c-949a-3f8c6e9f785a.png)

**Comment by pfps** [comment] 2022-03-10 11:11
The problem here is that the code is so far only set up to handle the normal case with keyboards.  Your mouse has two additional cases that need to be handled.  Please provide the output of `bin/solaar -ddd show` so I can see exactly how the mouse stores these cases.

Then download the PR again and try `bin/solaar show`.

**Comment by adatum** [comment] 2022-03-10 22:52
`bin/solaar -ddd show` with 1.1.1-124-ga683e99 : https://gist.github.com/adatum/7ab51c34674900706330f60f52cbe679

After downloading PR again, `bin/solaar -ddd show` with 1.1.1-126-ga1c1530 : https://gist.github.com/adatum/98d591d0c4b7f9856f61a8b2b52487dd

**Comment by pfps** [comment] 2022-03-10 23:18
Thanks.   This will help implementing (but the horizontal scroll information looks weird).  Oh well.

**Comment by pfps** [comment] 2022-03-11 01:28
PR #1407 should now handle persistent remappable action for your M720 so please download and try it out.   You will probably have to remove persistent_remappable_action from _absent.  Run Solaar as `solaar -dd` to show any errors.

The interface is not great, but there doesn't seem to be much that can be done.   The mouse buttons can be mapped to keys plus modifiers or to mouse buttons or to horizontal scrolling.  That leaves a lot of possibiities.

**Comment by pfps** [comment] 2022-03-11 01:31
Just be careful as changes are permanent.   There is a comment in setting_templates.py hinting on how to recover from invalid settings.   Strangely my Craft Keyboard allows changes that appear to be invalid and then Solaar refuses to accept the supposedly invalid entry.  Changing your left button, for example, can cause serious problems if you do not have another pointing device.

**Comment by adatum** [comment] 2022-03-11 02:29
1.1.1-127-gd63dc9a works! https://gist.github.com/adatum/e963ea035395b949e995ab0a241b2f7c

Persistent Key option is shown and the remapping persists powering the mouse off/on without Solaar running. 

I remapped the Multiplatform Gesture Button to Mouse Button Middle for testing, but it is a bit scary to see Left Button as the default key shown when Solaar is started as that would be the worst one to change permanently. As you said, gotta be careful.

I saw the hint "# TO RECOVER FROM BAD VALUES use _special_keys.KEYS" but I'm not sure how that would be used.

![solaar_persistent_remap](https://user-images.githubusercontent.com/9773655/157788712-bf54b3cf-190f-46e4-a5f2-bc2b53781c65.png)

Is there a possibility of invalid or corrupt settings that would be unrecoverable? Luckily I do have a second pointing device.

**Comment by pfps** [comment] 2022-03-11 02:36
Having the left button show up might not be ideal but at least the setting should be locked by default.

I had a bug in the code that I was using that allowed mapping my Craft keys to mouse buttons.   The Craft didn't complain when I did what should have been an invalid mapping and then Solaar complained about what it thought was an invalid mapping.  Using the commented-out value makes Solaar more permissive and thus allowed it to start up and let me change back to a good value.  I put the comment in as a reminder for if there are problems in the future.

I'll merge in the PR in a day or two if no problems surface.

**Closed** 2022-03-12 17:20 UTC
Labels: enhancement
