### ISSUE TITLE
Solaar doesn't sometime load configs

### ISSUE THREAD

**Issue by jkaart** [pwr-Solaar/Solaar#551] opened 2019-08-07 18:32 UTC
Hi,
I have problem with my Logitech MX Master 2S mouse and Solaar.
Seems Solaar doesn't load config sometime when I boot my computer. This happen about 1/4 times when I boot.
OS is 64-bit Ubuntu 18.04 Mate edition.

Edit: Looks like it load configs if I wakeup mouse before Ubuntu boot.
If I don't wakeup mouse, I need quit solaar and relaunch it.

**Comment by cryptomilk** [comment] 2019-08-20 08:39
This should be fixed with a868b477e1f4cdc13115909a5d4a2915145e29d8

**Comment by jkaart** [comment] 2019-08-20 13:11
Yes it should but not fixed!

**Comment by aleho** [comment] 2019-08-30 18:12
Can confirm. Especially at startup DPI is never set. Also after a wakeup the value is not set again.

**Comment by pettert85** [comment] 2019-11-07 18:30
any ideas as to when this issue will be addressed? I'm having the same issue with my Logitech MX Master 2s. The configuration file is sometimes read, but most of the time after suspend / reboots it does not.

**Comment by FFY00** [comment] 2019-11-30 23:32
@pettert85 I don't have the time to look into it. You can try to fix it yourself :confused:.

**Comment by Lekensteyn** [comment] 2019-12-01 14:51
Is it possible to start Solaar with the `--debug` option and check if there are any errors?

When the device is reconnected, settings should have been applied.

**Comment by lukasmichel** [comment] 2020-01-06 10:32
I am using an MX Master 2S and experience the same issue. I experimented a bit and found out that it makes a differences in which order you start the mouse and Solaar. If is turn on the mosue before is start Solaar, the configuration is loaded (Solaar log: [start_mouse_before_solaar.txt](https://github.com/pwr-Solaar/Solaar/files/4025669/start_mouse_before_solaar.txt)). If I do it the other way round, i.e. I start Solaar before I turn on the mouse, the configuration is not loaded (Solaar log: [start_solaar_before_mouse.txt](https://github.com/pwr-Solaar/Solaar/files/4025670/start_solaar_before_mouse.txt)). I hope this helps you. If I can do anything else, I am happy to help.

**Comment by pfps** [comment] 2020-01-17 19:01
It looks as if something screwy is going on in Setting.read in settings.py that is reading from the device when it shouldn't.  Based on the traces, this function should be getting 3400 from self.persister which should be returned but somehow this isn't happening in one case and the function is actually getting the current value from the device, which is then written back by Setting.apply.  As I don't have a device that has dpi I can't check this out, but the thing to do is to print self.persister at the beginning of the Setting.read function and then self._value after the first if statement.  The persister should be a dictionary with 3400 as value for 'dpi' and _value should then be 3400.

**Comment by lukasmichel** [comment] 2020-01-19 18:27
I have added both debug prints. I have again attached solaar's logs (using `-dd`). I have added `>>>>` before the lines I print from `Setting.apply` so that you can identify them more easily.

I have observed the following:
- First turn on mouse, then start solaar ([mouse_off.txt](https://github.com/pwr-Solaar/Solaar/files/4083075/mouse_off.txt)):
    - Every setting is loaded twice
    - The settings are always read correct, i.e. `self.persister` contains the correct values and the correct values are stored to `self._value`
- First start solaar, then turn on the mouse. ([mouse_off.txt](https://github.com/pwr-Solaar/Solaar/files/4083109/mouse_off.txt), mouse is turned on at time 19:12:00,186)
    - The settings are only read once
    - For hires-smooth-invert and hires-smooth-resolution the settings are loaded correctly and `self.persister` contains the correct values for all settings.
    - For dpi and smart-shift, `self.persister` is `None`. This seems to be the problem here. 

I hope this helps. I tried to dig into it myself, but up until now I couldn't even figure out from where these calls to `Settings.read` are made.

**Comment by pfps** [comment] 2020-01-20 00:35
OK, I have a tentative cause.   The MX Master 2S has four settings in Solaar, but only two features are listed in descriptors.py.  If Solaar is started with the mouse off the saved settings are attached to these two features but when the other features are discovered the saved settings are not attached to discovered features.  So the solution is to add the saved settings to discovered features.  It probably isn't going to be too hard to do this, but I don't think I have a device to test on, so I'll need some help testing.

**Comment by lukasmichel** [comment] 2020-01-20 10:15
I can help testing. I own a MX Master 2S and also an MX Anywhere 2 for which I just confirmed that it shows the same behaviour.

**Comment by pfps** [comment] 2020-01-20 14:46
@lukasmichel Thanks.  You should be able to clone
https://github.com/pfps/Solaar/tree/settings
and run
bin/solaar
from there.
Check that when you start with the mouse off you see two settings.  When you turn the mouse on you should see four settings and the new settings should have their saved values.  You should be able to change all four settings and the changes should come back even when you stop and start solaar and turn the mouse off and on.

**Closed** 2020-01-21 03:23 UTC
