### ISSUE TITLE
Running solaar breaks the resolution up/down buttons on G900

### ISSUE THREAD

**Issue by nowheretobefound** [pwr-Solaar/Solaar#1139] opened 2021-04-10 12:32 UTC
Solaar is working fine, but running it in any way, f.eks
`solaar show`
  makes the buttons for resolution up/down stop working.
These are the Button 7 and 8 from ratbag on top of the mouse next to the three led indicators.
To get them working again you have to turn the mouse on and off with the physical button under the mouse. (or start windows and the logitech application)

**Comment by nowheretobefound** [comment] 2021-04-10 12:46
Linux box 5.3.18-lp152.66-default #1 SMP Tue Mar 2 13:18:19 UTC 2021 (73933a3) x86_64 x86_64 x86_64 GNU/Linux
solaar 1.0.5

**Comment by pfps** [comment] 2021-04-10 13:01
Please provide output of `solaar show` to show which devices you have and what settings you have set up.

**Comment by pfps** [comment] 2021-04-10 13:44
I think I might know what the problem is.   The G900 likely has onboard profiles and when they are turned off (which Solaar does so that it can easily change the ) the behaviour of your mouse changes.   

PR #1135 add the ability to ignore settings.  Once that PR is merged in it should be easy to upgrade the polling rate setting so that it does not turn off onboard profiles when it is being ignored.

You will have to test this change for it to become part of Solaar.

**Comment by pfps** [comment] 2021-04-10 15:56
Try out PR #1140 and see whether it fixes your problem.

**Comment by nowheretobefound** [comment] 2021-04-12 06:12
Tried PR #1140 but same problem.
The button functionality is gone as soon as solaar is started. Theres alse a M720 mouse connected, ignore that.

Did this :

`git clone https://github.com/pwr-Solaar/Solaar.git
Cloning into 'Solaar'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 10562 (delta 84), reused 112 (delta 81), pack-reused 10415
Receiving objects: 100% (10562/10562), 5.94 MiB | 5.81 MiB/s, done.
Resolving deltas: 100% (5917/5917), done.
jenserun@ul001580:~/development$ cd Solaar
jenserun@ul001580:~/development/Solaar$ git fetch origin pull/1140/head:pull_1140
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 32 (delta 21), reused 30 (delta 21), pack-reused 0
Unpacking objects: 100% (32/32), 19.92 KiB | 657.00 KiB/s, done.
From https://github.com/pwr-Solaar/Solaar
 * [new ref]         refs/pull/1140/head -> pull_1140
jenserun@ul001580:~/development/Solaar$ git checkout pull_1140
Switched to branch 'pull_1140'
jenserun@ul001580:~/development/Solaar$ bin/solaar 

/development/Solaar$ bin/solaar -d
08:10:01,537     INFO [MainThread] root: language nb_NO (UTF-8), translations path None
08:10:01,729     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
08:10:02,154     INFO [MainThread] solaar.ui.notify: starting desktop notifications
08:10:02,338     INFO [MainThread] solaar.listener: starting receiver listening threads
08:10:02,341     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw2', vendor_id='046D', product_id='C52B', serial='', release=None, manufacturer=None, product=None, interface=2, driver='logitech-djreceiver', bus_id=3, isDevice=None)
08:10:02,350     INFO [ReceiverListener:hidraw2] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw2,17)> (17)
08:10:02,350     INFO [ReceiverListener:hidraw2] solaar.listener: <UnifyingReceiver(/dev/hidraw2,17)>: notifications listener has started (17)
08:10:02,352     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw6', vendor_id='046D', product_id='C539', serial='', release=None, manufacturer=None, product=None, interface=2, driver='logitech-djreceiver', bus_id=3, isDevice=None)
08:10:02,354     INFO [ReceiverListener:hidraw2] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,17)>: receiver notifications enabled => ('wireless', 'software present')
08:10:02,357     INFO [ReceiverListener:hidraw6] logitech_receiver.listener: started with <LightspeedReceiver(/dev/hidraw6,18)> (18)
08:10:02,357     INFO [ReceiverListener:hidraw6] solaar.listener: <LightspeedReceiver(/dev/hidraw6,18)>: notifications listener has started (18)
08:10:02,359     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw2,17)>: present, No paired devices. (0) 
08:10:02,361     INFO [ReceiverListener:hidraw6] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw6,18)>: receiver notifications enabled => ('wireless', 'software present')
08:10:02,363     INFO [ReceiverListener:hidraw6] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw6,18)>: present, No paired devices. (0) 
08:10:02,365     INFO [ReceiverListener:hidraw2] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,17)>: found new device 1 (405E)
08:10:02,366     INFO [ReceiverListener:hidraw2] solaar.listener: connection Notification(10,1,41,04,325E40) for <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)> (mouse)
08:10:02,371     INFO [ReceiverListener:hidraw6] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw6,18)>: found new device 1 (4053)
08:10:03,288     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw2,17)>: present, 1 paired device. (0) 
08:10:03,288     INFO [ReceiverListener:hidraw6] solaar.listener: connection Notification(10,1,41,0C,325340) for <Device(1,4053,G900 Chaos Spectrum Gaming Mouse,7D67F943)> (mouse)
08:10:03,293     INFO [ReceiverListener:hidraw6] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw6,18)>: present, 1 paired device. (0) 
08:10:03,408     INFO [ReceiverListener:hidraw2] logitech_receiver.device: <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)>: unitId 928EAC09 does not match serial 5667DC1B
08:10:03,631     INFO [ReceiverListener:hidraw6] logitech_receiver.status: <Device(1,4053,G900 Chaos Spectrum Gaming Mouse,7D67F943)> pushing device settings [<Setting([feature:choice] G900:dpi=None)>, <Setting([feature:choice] G900:report_rate=None)>]
08:10:03,735     INFO [ReceiverListener:hidraw6] solaar.listener: status_changed <Device(1,4053,G900 Chaos Spectrum Gaming Mouse,7D67F943)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': NamedInt(50, 'average'), 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3984, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
08:10:03,736     INFO [ReceiverListener:hidraw6] solaar.listener: status_changed <Device(1,4053,G900 Chaos Spectrum Gaming Mouse,7D67F943)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': NamedInt(50, 'average'), 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3984, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
08:10:03,751     INFO [ReceiverListener:hidraw6] solaar.listener: connection Notification(10,1,41,0C,B25340) for <Device(1,4053,G900 Chaos Spectrum Gaming Mouse,7D67F943)> (mouse)
08:10:03,752     INFO [ReceiverListener:hidraw6] solaar.listener: status_changed <LightspeedReceiver(/dev/hidraw6,18)>: present, 1 paired device. (0) 
08:10:03,753     INFO [ReceiverListener:hidraw6] solaar.listener: status_changed <Device(1,4053,G900 Chaos Spectrum Gaming Mouse,7D67F943)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': NamedInt(50, 'average'), 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': 3984, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
08:10:04,194     INFO [ReceiverListener:hidraw2] logitech_receiver.status: <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)> pushing device settings [<Setting([feature:toggle] M720 Triathlon:hires-smooth-invert=None)>, <Setting([feature:toggle] M720 Triathlon:hires-smooth-resolution=None)>, <Setting([feature:range] M720 Triathlon:pointer_speed=None)>, <Setting([feature:map choice] M720 Triathlon:reprogrammable-keys=None)>, <Setting([feature:map choice] M720 Triathlon:divert-keys=None)>, <Setting([feature:choice] M720 Triathlon:change-host=None)>]
08:10:04,620     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 20, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
08:10:04,621     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 20, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
08:10:04,622     INFO [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)>: spurious BATTERY status Notification(11,1,07,10,0400C21C0A0000000000000000000000)
08:10:04,622  WARNING [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)>: unknown WHEEL Notification(11,1,20,20,02000000000000000000000000000000)
08:10:04,623     INFO [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,405E,M720 Triathlon Multi-Device Mouse,5667DC1B)>: WHEEL: res: 0 periods: 8 delta V:3072
`

**Comment by pfps** [comment] 2021-04-12 08:58
As stated in  the first comment for PR #1140 you have to set Polling Rate to ignore and then turn your mouse off and on again.

**Comment by nowheretobefound** [comment] 2021-04-12 09:59
Yes, It now works. Ignore polling rate did it.
Thank you for the swift response :)

**Closed** 2021-04-12 12:04 UTC
Labels: bug
