### ISSUE TITLE
Cannot launch Solaar after installation

### ISSUE THREAD

**Issue by Hybjis** [pwr-Solaar/Solaar#2006] opened 2023-02-27 21:53 UTC
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.8
- Distribution: Fedora 37
- Kernel version (ex. `uname -srmo`): 6.1.13-200.fc37.x86_64
- Output of `solaar show`: 

<details>

```
solaar version 1.1.8

Lightspeed Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C539
  Serial       : D4409A8A
    Firmware   : 39.04.B0036
    Bootloader : 02.09
    Other      : AA.BE
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G703 Lightspeed Gaming Mouse
     Device path  : /dev/hidraw7
     WPID         : 4070
     Codename     : G703
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: FB710CC9
     Model ID:      C08700000000
     Unit ID:       FB710CC9
          Firmware: MPM 14.00.B0004
        Bootloader: BOT 64.00.B0004
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Firmware MPM 14.00.B0004 C087
            Firmware: Bootloader BOT 64.00.B0004 AADB
            Firmware: Other   
            Unit ID: FB710CC9  Model ID: C08700000000  Transport IDs: {'usbid': 'C087'}
         3: DEVICE NAME            {0005} V0     
            Name: G703 Wired/Wireless Gaming Mouse
            Kind: mouse
         4: BATTERY VOLTAGE        {1001} V2     
            Battery: 50% 3847mV , discharging.
         5: unknown:1863           {1863} V0    internal, hidden 
         6: unknown:18A1           {18A1} V0    internal, hidden 
         7: unknown:1E00           {1E00} V0    hidden 
         8: unknown:1E20           {1E20} V0     
         9: unknown:1EB0           {1EB0} V0    internal, hidden 
        10: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 800
            Sensitivity (DPI)        : 800
        11: ANGLE SNAPPING         {2230} V0     
        12: SURFACE TUNING         {2240} V0     
        13: REPORT RATE            {8060} V0     
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        14: ONBOARD PROFILES       {8100} V0     
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        15: MOUSE BUTTON SPY       {8110} V0     
        16: unknown:1850           {1850} V0    internal, hidden 
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: unknown:1801           {1801} V0    internal, hidden 
        19: DEVICE RESET           {1802} V0    internal, hidden 
        20: unknown:1803           {1803} V0    internal, hidden 
        21: unknown:1890           {1890} V0    internal, hidden 
        22: unknown:1811           {1811} V0    internal, hidden 
        23: LATENCY MONITORING     {8111} V0     
        24: COLOR LED EFFECTS      {8070} V4     
        25: unknown:1809           {1809} V0     
        26: unknown:1830           {1830} V0    internal, hidden 
        27: OOBSTATE               {1805} V0    internal, hidden 
        28: CONFIG DEVICE PROPS    {1806} V0    internal, hidden 
     Battery: 50% 3847mV , discharging.
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.7
- _NAME: G703 Lightspeed Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    pointer_speed, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert,
    gesture2-params, sidetone, equalizer, scroll-ratchet]
  _battery: 4097
  _modelId: C08700000000
  _serial: FB710CC9
  _unitId: FB710CC9
  _wpid: '4070'
  dpi: 800
  onboard_profiles: 1
  report_rate: 1
```
</details>

- Errors or warrnings from Solaar:

```
(solaar:5387): Gtk-WARNING **: 22:36:21.333: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
Traceback (most recent call last):
  File "/home/traxler/.local/lib/python3.10/site-packages/solaar/ui/__init__.py", line 170, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/home/traxler/.local/lib/python3.10/site-packages/solaar/ui/__init__.py", line 117, in _startup
    window.init(show_window, use_tray)
  File "/home/traxler/.local/lib/python3.10/site-packages/solaar/ui/window.py", line 825, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/home/traxler/.local/lib/python3.10/site-packages/solaar/ui/__init__.py", line 135, in _command_line
    _activate(app)
  File "/home/traxler/.local/lib/python3.10/site-packages/solaar/ui/__init__.py", line 128, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value`
```

**Describe the bug**
After installing Solaar I get an error when trying to open the program by running "solaar". If I try to start the program by clicking the application I get no errors but Solaar does not start. I have tried installing Solaar in terminal (sudo dnf install solaar) and in GNOME Software.

**To Reproduce**
1. Try to open Solaar by running "solaar" in terminal.

**Screenshots**

**Additional context**
When reading documents I saw that ayatanaappindicator was required. I was not able to find a way to install it on Fedora but I did install libappindicator instead.

**Comment by pfps** [comment] 2023-02-27 23:58
The error occurs because Solaar is unable to find the solaar icon.   Solaar looks in a lot of places for the icon, including the usual places for icons but also from around the directory it is running from.   To diagnose for sure, run Solaar as `solaar -ddd` and look for the line that contains `solaar.ui.icons: icon theme paths:`.     There should be some Solaar icons (solaar.png or solaar.svg) under some of these directories.

**Comment by pfps** [comment] 2023-02-28 12:07
I am also running Fedora.   I checked to see what happened if I made all the solaar....png files on my system inaccessible and Solaar still worked find.  I then checked to see what happened if I made all the solaar.svg files inacessible and Solaar threw and error that it could not load a solaar.svg file because of a permissions error.  So gdk on my system can load svg files.  I run XFCE and X11 so maybe the problem is that you are running Gnome.

I see that there are some bug reports on other systems with the same problem.   Please try the solution in https://github.com/dino/dino/issues/1024.

But the big question is why gdk isn't set up to load SVG files.  That would seem to be a core functionality for GDK/GTK.

**Comment by Hybjis** [comment] 2023-02-28 21:08
Holy shit I just got it to work. The solution was to uninstall Miniconda. I have no idea why conda/miniconda breaks it, but I'm glad I found it. :smile:

**Comment by pfps** [comment] 2023-02-28 21:11
You may have been running in an environment where a library was unavailable.

Anyway, I'm closing this issue.

**Closed by pfps** 2023-02-28 21:11 UTC
Labels: bug
