### ISSUE TITLE
Question: Is the SysTray icon supposed to be interactive?

### ISSUE THREAD

**Issue by ChaosNicro** [pwr-Solaar/Solaar#366] opened 2017-06-24 21:41 UTC
Since Solaar starts minimized when run I expected a double click on the icon to open the interface but it does not react to any kind of clicks in any way. 
Running from console gave some deprecation errors about the theme parser but no errors related to the indicator library which would usually process this kind of event.
For now I just open Solaar a second time to get the interface.

My setup:
Opensuse Leap 42.2
KDE-Plasma 5.8.6
Solaar 9.2

**Comment by andyspiros** [comment] 2017-09-01 05:39
Any updates on this? It works correctly for me: a left click opens up the interface window and a right click opens the menu with information about the devices and the quit button.

Arch Linux
Solaar 0.9.2
Plasma 5.10.5

**Comment by Lekensteyn** [comment] 2017-09-21 00:23
I believe this is a duplicate of #223, either Solaar needs some fixes or the compatibility layer used by Plasma needs fixing

**Comment by pfps** [comment] 2020-01-12 23:20
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment] 2020-02-07 16:17
Closing due to no response from original poster.

**Closed by pfps** 2020-02-07 16:17 UTC
