### ISSUE TITLE
Missing system-tray icon on Wayland (Fedora 25)

### ISSUE THREAD

**Issue by arigit** [pwr-Solaar/Solaar#324] opened 2016-12-17 17:39 UTC
With Fedora's default wayland desktop, Solaar's system try icon is not visible, hence the app can't be invoked once it was launched

This is with the latest git code. I see some warnings when launching from a terminal

> solaar
/usr/lib/python2.7/site-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python2.7/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/solaar/ui/tray.py:148: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

**Comment by Lekensteyn** [comment] 2016-12-20 20:31
Have you tried git? The warnings you posted have been fixed in git.

If Fedora does not implement the right appindicator or Xembed library, then the icon may be missing.

**Comment by arigit** [comment] 2016-12-20 20:46
Yes I'm using the latest git version
Note that when I log-in using Xorg instead of Wayland, the system-tray icon shows up. They problem is on Wayland sessions only, so I'm guessing the required libraries are there.

On Wayland, other apps don't seem to have a problem with system-tray icons. Apps that work fine include Audacious-GTK, Google Music, other gnome-shell extensions.

**Comment by Lekensteyn** [comment] 2016-12-20 20:55
Possible related issues: #223, #300

(patches welcome!)

**Comment by simonbcn** [comment] 2017-01-17 14:20
Same problem.

**Comment by moceap** [comment] 2017-01-31 20:53
Patch:
https://github.com/pwr/Solaar/pull/332

**Comment by pfps** [comment] 2020-01-12 21:53
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment] 2020-02-07 16:13
Closing due to no response from original posters.

**Closed by pfps** 2020-02-07 16:13 UTC
Labels: bug

**Comment by arigit** [comment] 2020-02-07 17:31
sorry for the slow response. Yes this has been fixed and is no longer an issue in current distro releases / latest solaar

**Comment by chris-aeviator** [comment] 2020-07-27 08:36
I do not see a tray icon on arch linux, I can confirm that all other "normal" tray icons (e.g. running nextcloud, syncthing, telegram, bluetooth-tray...) appear. I have downloaded and used the provided version from git, bin folder.

Solaar V 1.0.3rc1

**Comment by pfps** [comment] 2020-07-27 09:12
@chris-aeviator Please see issue #843 
This is likely a not a problem with Solaar.

**Comment by chris-aeviator** [comment] 2020-07-27 13:26
@pfps after `chown me /dev/hidraw3` and thus not needing to run solaar with sudo anymore the icon perfectly fine appears
