### ISSUE TITLE
Add support for N305 Number pad?

### ISSUE THREAD

**Issue by cbrown1** [pwr-Solaar/Solaar#1337] opened 2021-11-19 20:18 UTC
I am using solaar version 1.0.7, which was packaged for manjaro linux. I have 2 Logitech N305 number pads. I am able to pair each of the devices in solaar, but they are identified as N545, and they do not produce keypresses. When I turn a paired N305 on, the LED at the top stays on for a few seconds and then turns off. These devices have the red star 'unifying' logo on the back. 

Let me know if more info is needed. Thanks.

**Comment by pfps** [comment] 2021-11-19 20:31
Solaar isn't a device driver, so if your number pads don't work then the problem is likely elsewhere.  You should be looking at whether an input device shows up in `xinput` or whether a node is created in /dev/input for it.

Solaar has a table that provides names for many older Logitech devices based on their product IDs.  This method misidentifies devices sometimes because sometimes the same product ID is used for differently-labelled products.  As the names are not significant to the workings of Solaar (or other parts of Linux) it is not a real problem that they are sometimes not correct.

You could post the output of `solaar show` to show just what Solaar thinks about these devices.

**Comment by cbrown1** [comment] 2021-11-19 20:38
It looks like you are correct, as there is no device path. Any suggestions where I should go from here? Thanks.

  3: Number Pad N545
     Device path  : None
     WPID         : 2006
     Codename     : N545
     Kind         : numpad
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: C44E0978
          Firmware: 13.00.B0037
        Bootloader: 02.03
             Other: 00.01
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Features: (none)
     Battery: full, discharging.

**Comment by pfps** [comment] 2021-11-19 20:52
This might or might not be a problem. 
First, check whether a new node shows up in /dev/input when you plug in the receiver.   If not, then there is some low-level problem and you will have to ask someone who knows about drivers, etc.
Next, check whether a new entry shows up in xinput.  If not, then the device is not being recognized by X probably because there is no udev rule that knows what kind of a device it is.  See one of the comments in https://stackoverflow.com/questions/873975/how-can-i-capture-raw-hid-input-on-linux for more information.
Next, run `sudo evtest` and enter the device (event) number for your keypad and then type on the keypad.  This should produce some input.  If not, then it is likely that the keypad is not producing input.
Next, check the output that evtest produces showing what characters evtest thinks the keypad is producing.  If these are not as expected you need to set up a good mapping of what the keypad produces to X characters.  You will have to ask someone else about this.
Finally, if evtest is showing reasonable results (codes like KEY_KP4, etc.) then everything is working fine up to the point that the key event is sent to the application, which might not be prepared for keypad codes.  Use a different application.

**Comment by pfps** [comment] 2021-11-19 20:57
By the way, all this has nothing to do with Solaar.

**Comment by pfps** [comment] 2021-11-26 21:26
Closed as probably not relevant for Solaar.

**Closed by pfps** 2021-11-26 21:26 UTC

**Comment by cbrown1** [comment] 2021-12-01 18:37
Just a follow up. I followed your detailed instructions. All tests passed and when I got to running `sudo evtest` I was getting keyboard input and I also noticed that the key I was pressing was showing up mixed in with the evtest output. I canceled evtest, and the keypad now works without any issue. So I am all set, although I wish I knew what fixed it. Could just running evtest have solved the problem? 

Thanks for the help.

**Comment by pfps** [comment] 2021-12-01 18:47
It is entirely possible that something went wrong when Linux was trying to set up the number pad (possibly due to some transient hardware problem).   The setup may have been tried again because some time had elapsed or one of the steps you did triggered it.

**Comment by pfps** [comment] 2022-03-29 15:56
This is not necessarily a Solaar problem.   Solaar doesn't interfere with normal operation of Logitech devices.  All it does is pair/unpair and change the settings of device features.   I suppose it is possible that Solaar forced some change on the device that caused the device not to work, but Solaar generally doesn't change anything on the device unless it has been told to do so.

From the information you provided the pad appears to be quite old and uses the original HID++ protocol.  It also doesn't have any settings that Solaar can change.  This makes it extremely unlikely that Solaar did anything to the device.
