### ISSUE TITLE
Solaar started reseting randomly Ubuntu 22.04

### ISSUE THREAD

**Issue by cvetan** [pwr-Solaar/Solaar#2366] opened 2024-03-05 10:35 UTC
**Information**

- Solaar version `1.1.11`
- Distribution: `Ubuntu 22.04`
- Kernel version `Linux 6.5.0-21-generic x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar version 1.1.11

Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C52B
  Serial       : 22D995E2
    Firmware   : 24.11.B0036
    Bootloader : 03.09
    Other      : AA.AD
  Has 3 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 2=215

  1: Wireless Mouse MX Master 2S
     Device path  : /dev/hidraw4
     WPID         : 4069
     Codename     : MX Master 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Report Rate : 8msms
     Serial number: 705F6C1B
     The power switch is located on the base.
     Battery: unknown (device is offline).

  2: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw5
     WPID         : 4082
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Report Rate : 8msms
     Serial number: D1FCEE8F
     Model ID:      B02340820000
     Unit ID:       D1FCEE8F
        Bootloader: BOT 95.00.B0013
          Firmware: MPM 19.01.B0015
             Other: 
     The power switch is located on the base.
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V3     
            Firmware: Bootloader BOT 95.00.B0013 0000D8279515
            Firmware: Firmware MPM 19.01.B0015 40826A9CA89D
            Firmware: Other   
            Unit ID: D1FCEE8F  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000} V1     
            Battery: 100%, discharging, next level 50%.
         9: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        10: CHANGE HOST            {1814} V1     
            Change Host        : 1:executor
        11: XY STATS               {2250} V1     
        12: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Ratcheted
            Scroll Wheel Ratcheted        : Ratcheted
            Scroll Wheel Ratchet Speed (saved): 50
            Scroll Wheel Ratchet Speed        : 50
        14: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: THUMB WHEEL            {2150} V0     
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
            Thumb Wheel Diversion (saved): False
            Thumb Wheel Diversion        : False
        16: WHEEL STATS            {2251} V0     
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V6    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:1890           {1890} V5    internal, hidden 
        25: unknown:1891           {1891} V5    internal, hidden 
        26: unknown:18A1           {18A1} V0    internal, hidden 
        27: unknown:1DF3           {1DF3} V0    internal, hidden 
        28: unknown:1E00           {1E00} V0    hidden 
        29: unknown:1EB0           {1EB0} V0    internal, hidden 
        30: unknown:1861           {1861} V0    internal, hidden 
        31: unknown:9001           {9001} V0    internal, hidden 
        32: unknown:9203           {9203} V0    internal, hidden 
        33: unknown:9205           {9205} V0    internal, hidden 
        34: unknown:9300           {9300} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.

  3: MX Keys Keyboard
     Device path  : /dev/hidraw6
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Report Rate : 20msms
     Serial number: 5AC36EFF
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

Bolt Receiver
  Device path  : /dev/hidraw11
  USB id       : 046d:C548
  Serial       : 32464237323844454332304238463134
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: (empty)

  1: MX Keys Mini
     Device path  : None
     WPID         : B369
     Codename     : MX Keys Mini
     Kind         : keyboard
     Protocol     : unknown (device is offline)
     Report Rate : 0ms
     Serial number: 773F221F
     The power switch is located on the (unknown).
     Battery: unknown (device is offline).
```

</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.11
- _NAME: G502 Gaming Mouse
  _modelId: 407FC08D0000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: A20B2798
  _unitId: A20B2798
  _wpid: 407F
  dpi: 0x3e8
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  onboard_profiles: 0x1
  report_rate: 0x1
- _NAME: Wireless Mouse MX Master 2S
  _modelId: B01940690000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 705F6C1B
  _unitId: A6D47229
  _wpid: '4069'
  change-host: null
  divert-keys: {0x52: 0x0, 0x53: 0x0, 0x56: 0x0, 0xc3: 0x0, 0xc4: 0x0}
  dpi: 0x3e8
  gesture2-divert: {0x2e: false}
  gesture2-gestures: {0x2d: true, 0x2e: true}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xc3: 0xc3, 0xc4: 0xc4}
  scroll-ratchet: 0x2
  smart-shift: 0x32
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 0x1000
  _modelId: B02340820000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: D1FCEE8F
  _unitId: D1FCEE8F
  _wpid: '4082'
  change-host: null
  divert-keys: {0x52: 0x0, 0x53: 0x0, 0x56: 0x0, 0xc3: 0x0, 0xc4: 0x0}
  dpi: 0x3e8
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xc3: 0xc3, 0xc4: 0xc4}
  scroll-ratchet: 0x2
  smart-shift: 0x32
  thumb-scroll-invert: false
  thumb-scroll-mode: false
- _NAME: MX Keys Keyboard
  _modelId: B35B408A0000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 5AC36EFF
  _unitId: 5AC36EFF
  _wpid: 408A
  backlight: true
  change-host: null
  disable-keyboard-keys: {0x1: false, 0x2: false, 0x4: false, 0x8: false, 0x10: false}
  divert-keys: {0xa: 0x0, 0x6e: 0x0, 0x6f: 0x0, 0xbf: 0x0, 0xc7: 0x0, 0xc8: 0x0, 0xd1: 0x0, 0xd2: 0x0, 0xd3: 0x0, 0xe0: 0x0, 0xe1: 0x0, 0xe2: 0x0, 0xe3: 0x0,
    0xe4: 0x0, 0xe5: 0x0, 0xe6: 0x0, 0xe7: 0x0, 0xe8: 0x0, 0xe9: 0x0, 0xea: 0x0, 0xeb: 0x0, 0xec: 0x0}
  fn-swap: true
  multiplatform: 0x0
- _NAME: MX Keys Mini
  _modelId: B36900000000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 773F221F
  _unitId: 773F221F
  _wpid: B369
  backlight: true
  change-host: null
  disable-keyboard-keys: {0x1: false, 0x8: false, 0x10: false}
  divert-keys: {0xe2: 0x0, 0xe3: 0x0, 0xe5: 0x0, 0xe7: 0x0, 0xe8: 0x0, 0xe9: 0x0, 0x103: 0x0, 0x108: 0x0, 0x10a: 0x0, 0x117: 0x0, 0x11c: 0x0}
  fn-swap: false
  multiplatform: 0x0
- _NAME: MX518 Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, report_rate_extended, pointer_speed, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer, adc_power_management]
  _battery: 0x0
  _modelId: C08E00000000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore, onboard_profiles: false}
  _unitId: '34384713'
  dpi: 0x3e8
  onboard_profiles: 0x1
  report_rate: 0x1
```

</details>

Solaar started reseting randomly. I am working normally and I have mouse disconnected, solaar resets and then it normally works afterwards. I still haven't had situation that this happens more than once per session. But it started appearing rather frequently.

**Comment by pfps** [comment] 2024-03-05 10:45
What do you mean by Solaar resetting?

**Comment by cvetan** [comment] 2024-03-05 11:56
The application is reseting. It exits, and then starts again. For that time, I loose connection on mouse briefly.

**Comment by pfps** [comment] 2024-03-05 12:02
Solaar isn't set up to reset.   How are you running Solaar?

Solaar is not a device driver so there is no reason that problems with Solaar should cause a device to stop working. 

Please quit out of Solaar and then run it as `solaar -dd`.   When the mouse problem occurs see whether there is any output.  If so, post it.  If not then the problem is likely a hardware issue.

**Comment by cvetan** [comment] 2024-03-05 12:11
I am running solar with startup script `solaar --window=hide`

OK, I will. Thanks.

**Comment by pfps** [comment] 2024-03-05 12:14
Are you running that command from a terminal or is it invoked using some other means?

**Comment by cvetan** [comment] 2024-03-05 21:13
It is startup application, .desktop file from .config/autostart

**Comment by pfps** [comment] 2024-03-06 03:47
That should support any restart or reset.  So I expect that your icon theme does not have the Solaar icon available and when Solaar changes to that icon name that nothing is showing up in the system tray.  

I'm still strongly suspecting that something is causing your receivers to be disconnected from the system.

**Comment by Metal-spoon** [comment] 2024-03-08 16:45
I'm having a similar issue since upgrading to `1.1.11`
Some info about my system:
- version: `1.1.11`
- distro: `Fedora 39`
- kernel version:  `6.7.7-200.fc39.x86_64`

I attached a log I collected when running `solaar -dd`:
[solaarlog.txt](https://github.com/pwr-Solaar/Solaar/files/14540829/solaarlog.txt)

I have since downgraded back to `1.1.10` and the issue has disappeared.

**Comment by pfps** [comment] 2024-03-08 16:59
@Metal-spoon This looks to be a different problem.  You can open a new issue if you want.  But I expect that what is happening is that the DPI from your mouse's profiles is now overriding the DPI you explicitly set.   This is what should have been happening all along, but Solaar didn't have support for profiles until 1.1.11.

**Comment by Metal-spoon** [comment] 2024-03-08 17:06
> @Metal-spoon This looks to be a different problem. You can open a new issue if you want. But I expect that what is happening is that the DPI from your mouse's profiles is now overriding the DPI you explicitly set. This is what should have been happening all along, but Solaar didn't have support for profiles until 1.1.11.

I see, thanks for the swift reply :)
Sorry for adding irrelevant info.

**Comment by pfps** [comment] 2024-03-20 19:24
Closing due to no recent response from original poster.

**Closed by pfps** 2024-03-20 19:24 UTC
Labels: bug
