### ISSUE TITLE
Solaar depends on a udev file that is not present

### ISSUE THREAD

**Issue by jason-gu** [pwr-Solaar/Solaar#1004] opened 2020-11-17 20:52 UTC
**Information**

- Solaar version: 1.0.4
- Distribution: Ubuntu 20.04.1
- Kernel version: `Linux 5.4.0-54-generic x86_64 GNU/Linux`
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C52B
  Serial       : 68F19F6F
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: (empty)

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw3
     WPID         : 4082
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: B4BAB65C
     The power switch is located on the base.
     Battery: unknown (device is offline).

```

**Describe the bug**
I installed Solaar from Solaar git ppa (https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa), installation succeeded, but when I click on the Solaar icon to start the app, the app failed to start and resulted in error trace.

11:25:22 AM systemd: gnome-launched-solaar.desktop-13037.scope: Succeeded.
11:25:22 AM solaar: ModuleNotFoundError: No module named 'pynput'
11:25:22 AM solaar: ModuleNotFoundError: No module named 'pynput'
11:25:22 AM solaar:     from pynput import keyboard as _keyboard
11:25:22 AM solaar:   File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 30, in <module>
11:25:22 AM solaar:     from . import diversion as _diversion
11:25:22 AM solaar:   File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 30, in <module>
11:25:22 AM solaar:     from logitech_receiver import notifications as _notifications
11:25:22 AM solaar:   File "/usr/share/solaar/lib/solaar/listener.py", line 32, in <module>
11:25:22 AM solaar:     import solaar.listener as listener
11:25:22 AM solaar:   File "/usr/share/solaar/lib/solaar/gtk.py", line 153, in main
11:25:22 AM solaar: solaar: error: Traceback (most recent call last):
11:25:22 AM solaar: at https://pwr-solaar.github.io/Solaar/installation
11:25:22 AM solaar: For more information see the Solaar installation directions
11:25:22 AM solaar: Solaar depends on a udev file that is not present

On my system, the udev files are located:
/lib/udev/rules.d/60-solaar.rules
/usr/share/solaar/udev-rules.d/42-logitech-unify-permissions.rules

**Comment by pfps** [comment] 2020-11-17 21:07
There appear to be two problems.  

First pynput doesn't appear to be installed.  To fix that
```
pip install --user pynput
```
For a short time that module was needed but not required.  And the patches for the PPA are failing now, I think.

Second, the PPA does not appear to be installing the udev rule.  You need 
```
/etc/udev/rules.d/42-logitech-unify-permissions.rules
```
I don't know that the 60-solaar.rules is supposed to be for.

To fix this problem you need to copy the 42-... file to the right place as root.


I don't know why the PPA isn't doing this.

**Comment by pfps** [comment] 2020-11-17 22:01
Hmm there may also be a problem with pynput in the current version of Solaar.

**Comment by pfps** [comment] 2020-11-18 15:13
You should also reach out to the person responsible for the Ubuntu PPAs.

@muzena

**Comment by jason-gu** [comment] 2020-11-18 17:39
thanks for the quick response @pfps, I was able to fix the "Solaar depends on a udev file that is not present" issue by symlinking /usr/share/solaar/udev-rules.d/42-logitech-unify-permissions.rules to /etc/udev/rules.d/42-logitech-unify-permissions.rules. But ModuleNotFoundError: No module named 'pynput remains.

I ended up using the stable ppa https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable which has 1.0.3 and works.

**Comment by pfps** [comment] 2020-11-18 19:33
If `pip install --user pynput` doesn't fix the missing pynput problem, then you probably have to install pynput for your entire system using `sudo pip install pynput`.

peter

**Comment by Klap-in** [comment] 2020-11-18 20:22
@muzena Is it possible to integrate (eventually installing via pip of) pynput in the package offered via the ppa?

**Comment by muzena** [comment] 2020-11-18 21:20
I will check this problem tomorrow

**Comment by comxd** [comment] 2020-11-18 23:00
Try switch to downgrade to the 1.0.3 using the **stable** PPA: https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable
I can confirm that this version is working correctly with KUbuntu 20, MX Master 3 & Craft keyboard.

**Comment by pfps** [comment] 2020-11-19 11:46
The development version of Solaar in this repository has a new rule capability, which has new dependencies, and dependencies where not being set up correctly.  This should now be fixed.

**Comment by muzena** [comment] 2020-11-25 12:54
Problem is that this build dependency (pynput) in debian does not exist.
For building pynput package in debian one of required dependencies is python-setuptools-lint which also does not exist in debian...
It's dependency hell.

**Comment by pfps** [comment] 2020-11-26 00:16
Given that I'm already using X11 I should be able to remove the use of pynput.

**Comment by pfps** [comment] 2020-11-26 02:02
PR #1014 removes pynput, using x11 directly.  It would be nice to also remove psutil, but that seems more difficult.

It should get some more testing.

@muzena Can you try building this PR in debian?

**Comment by pfps** [comment] 2020-11-27 15:14
@muzena pynput is not longer used and should not be needed at al for Solaar.

**Comment by muzena** [comment] 2020-11-28 11:54
@pfps 
I get this [build error](https://launchpadlibrarian.net/509000365/buildlog_ubuntu-focal-amd64.solaar_1.0.4+git1254-0427e56-202011281142~ubuntu20.04.1_BUILDING.txt.gz) in launchpad.

**Comment by pfps** [comment] 2020-11-28 11:59
Solaar uses psutil to get the name of processes.  psutil comes from PyPI.   I'm not sure what the best way to proceed is.   I'll investigate.

**Comment by pfps** [comment] 2020-11-28 12:11
psutil should be available in debian systems 
```
sudo apt-get install -y python-psutil 
```
I'm not sure which version, so you may need to adjust the dependency in setup.py .  If so, let me know and I'll try changing it here.

**Comment by pfps** [comment] 2020-11-28 12:43
@muzena psutil should be available in debian systems
```
sudo apt-get install -y python-psutil 
```
I'm not sure which version, so you may need to adjust the dependency in setup.py . If so, let me know and I'll try changing it here.

**Comment by muzena** [comment] 2020-11-28 16:08
@pfps 
I add  python-psutil package as dependency, but there is same [build error](https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-git).
Ubuntu Groovy and Hirsute waiting dependency because python-psutil package dosen't exist anymore in [their repo](https://packages.ubuntu.com/focal/python-psutil).

**Comment by pfps** [comment] 2020-11-28 16:33
@muzena 
The psutil package should be in /usr/local/lib64/python3.*/site-packages/psutil or /usr/lib64/python3.*/site-packages/psutil where X is the version of python that you are using.  If this directory not present then something is wrong with the package.
Another way to go would be to use the pip package - psutil.  I'm not sure how to include a pip dependency in a system package.

**Comment by pfps** [comment] 2020-11-28 19:35
@rathann 
Solaar now depends on several new packages.  Can you update your fedora package locally to check that the fedora package can correctly depend on them?

**Comment by rathann** [comment] 2020-11-28 21:29
@pfps update to current git master? Sure, I'll try to find some time to spin up a new package. Have you decided what the next version number is going to be?

**Comment by rathann** [comment] 2020-11-28 21:35
Also, on Fedora, the package puts udev rules in `/usr/lib/udev/rules.d/`. [gtk.py:142](https://github.com/pwr-Solaar/Solaar/blob/master/lib/solaar/gtk.py#L142) checks both `/etc/udev` and `/lib/udev`. The latter resolves to `/usr/lib/udev` because of `/lib -> /usr/lib` symlink.

**Comment by pfps** [comment] 2020-11-28 23:10
@rathann  The next version will be 1.0.5

**Comment by rathann** [comment] 2020-12-04 12:45
Latest git builds and works fine (except for a small issue with the metainfo.xml file). New xlib dependency is automatically generated by the build process. In fact, I'm going to remove the explicit dependency on pyudev from Fedora package because it's become redundant.

**Comment by pfps** [comment] 2020-12-04 15:19
@rathan Thanks.  I've merged your PR in.
@muzena Does Solaar build for you now?  

I'm trying to figure out whether to create the new release with user rules in their current state (turned off in Wayland) or try to partially fix them in Wayland.

**Comment by pfps** [comment] 2020-12-12 17:41
@muzena I expect that you running into 2/3 problems and the package you need is
`python3-psutil`.  You will also need `python3-xlib` and `python3-pyyaml`.

**Comment by pfps** [comment] 2020-12-19 15:09
@muzena  Have you had a chance to try the python3 versions of these packages?

**Comment by muzena** [comment] 2020-12-20 10:24
@pfps 
python3-pyyaml dosen't exist in debian/ubuntu repositories, you mean on python3-yaml package?
[Building now working](https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-git) except for Ubuntu Trust and Xenial they are to old releases.

**Comment by pfps** [comment] 2020-12-20 12:28
@muzena Yes.  Sorry about the mistake.

**Comment by pfps** [comment] 2020-12-27 15:53
@muzena  Is this fixed now?

**Comment by pfps** [comment] 2021-01-04 14:58
This appears to be fixed so I'm closing the issue.

**Closed by pfps** 2021-01-04 14:58 UTC
Labels: bug
