### ISSUE TITLE
DPI setting always reset to 1000 on system reboot

### ISSUE THREAD

**Issue by MacedoRAC** [pwr-Solaar/Solaar#642] opened 2020-01-16 10:22 UTC
I have a **MX Master 2S** and if I change the default DPI setting from 1000 to another value it works perfectly. However, every time I reboot or shutdown the PC the changes don't persist and I have to change the DPI Setting again.

**OS:** Linux Mint 19.3 Tricia 
**Kernel version:** 5.0.0-37-generic
**Solaar version:** 1.0.1

**Comment by pfps** [comment] 2020-01-16 16:41
Solaar stores the device settings in ~/.config/solaar/config.json
If there is no section there with the Wireless PID and serial number of your device (both are in the info section of the Solaar window - click on the little icon to the left of the Pair new device to see) that has a DPI value in it then Solaar is not going to restore the DPI setting.
If that information is not present, it may be that Solaar just doesn't store that setting (yet).
If it is then there is definitely some bug.  Could you try solaar -dd and look for lines containing something like DPI (or dpi).  You will probably see a lot of chatter in the output, particularly if you move your mouse around, as solaar currently thinks that lots of device reports are unknown notifications. (A fix is in the works for this.)

**Comment by MacedoRAC** [comment] 2020-01-16 17:04
Sorry but I got truly confused with your comment.
As can be seen in the image below in the config.json the dpi value is being saved.

![Selection_069](https://user-images.githubusercontent.com/6772123/72546196-3ee01c00-3882-11ea-96dd-d779695f3fce.png)

**Comment by pfps** [comment] 2020-01-16 17:26
OK, some sort of bug.
I don't know if I have access to a mouse where I can change the DPI setting.  If not, I won't be able to do much.
If you can run solaar -dd when you reboot and attach the output here that might also help.  Don't just copy and past the output as it is likely to be large.

**Comment by MacedoRAC** [comment] 2020-01-16 17:34
Ok I rebooted the PC and as expected the config.json stills the same but in the solaar application you can see that is set to 1000 (and 1000 is the real value because the mouse is really not sensible :P)

![Selection_070](https://user-images.githubusercontent.com/6772123/72548213-2a058780-3886-11ea-956b-1666649eef97.png)


Regarding the result of running **solaar --dd** the entire log is just three lines:

```
17:29:56,518     INFO [MainThread] root: language en_US (UTF-8), translations path None
17:29:56,563    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
17:29:56,570     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
```

**Comment by pfps** [comment] 2020-01-16 17:35
Thanks, I'll see if I have a suitable mouse to see what is going on here.

**Comment by MacedoRAC** [comment] 2020-01-16 17:47
@pfps  thank you very much. If I can help with anything else just let me know

**Comment by pfps** [comment] 2020-01-17 02:05
Unfortunately I don't have a mouse with this feature, so I don't think I can do anything more just now.

**Comment by lukasmichel** [comment] 2020-01-17 17:50
This could be related to or a duplicate of #551.

**Comment by pfps** [comment] 2020-01-21 14:01
PR #649 should have fixed this issue.  Please download the current version of Solaar from this repository and see if your problem persists.

**Closed** 2020-02-07 16:50 UTC
Labels: bug
