### ISSUE TITLE
Cannot detect Logitech devices anymore

### ISSUE THREAD

**Issue by jean-christophe-manciot** [pwr-Solaar/Solaar#537] opened 2019-07-23 23:26 UTC
Ubuntu 19.10 Linux 5.2.0-8

Comparing different solaar versions in this exact same OS environment with the exact same Logitech devices:

1) solaar ```0.9.2+dfsg-9``` (official Ubuntu build)
![Solaar 0 9 2+dfsg-9](https://user-images.githubusercontent.com/13176858/61753906-5ea1f600-adb1-11e9-8947-4a5b172c2f72.png)

2) solaar commit ```a587ae6``` (20190629) and ```a597b81``` (20190714)
![Solaar a587ae6](https://user-images.githubusercontent.com/13176858/61753964-9446df00-adb1-11e9-9b6c-b63b004324e9.png)

In the case 2), the mouse is seen on the CLI but not graphically:
```
# solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 85EC9B56
    Firmware   : 24.05.B0029
    Bootloader : 01.08
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=138, 2=242

  1: Wireless Mouse B330/M330/M331
     Codename     : B330/M330/M331
     Kind         : mouse
     Wireless PID : 4057
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: BEF9D3BF
          Firmware: RQM 55.04.B0021
     The power switch is located on the base.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: BATTERY STATUS         {1000}   
         6: unknown:1810           {1810}   internal, hidden
         7: unknown:1830           {1830}   internal, hidden
         8: unknown:1802           {1802}   internal, hidden
         9: unknown:1862           {1862}   internal, hidden
        10: unknown:1890           {1890}   internal, hidden
        11: unknown:18A0           {18A0}   internal, hidden
        12: unknown:18B1           {18B1}   internal, hidden
        13: REPROG CONTROLS V4     {1B04}   
        14: WIRELESS DEVICE STATUS {1D4B}   
        15: unknown:1DF0           {1DF0}   hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1EB0           {1EB0}   internal, hidden
        19: unknown:1F03           {1F03}   internal, hidden
        20: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
        21: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
     Has 3 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             divertable, mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             divertable, mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             divertable, mse, reprogrammable, pos:0, group:2, gmask:3
     Battery: 70%, discharging.

  2: Wireless Keyboard K230
     Codename     : K230
     Kind         : keyboard
     Wireless PID : 400D
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 9BB42D7D
          Firmware: RQK 40.00.B0011
     The power switch is located on the bottom left corner.
     Supports 14 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: FEATURE INFO           {0002}   
         3: DEVICE FW VERSION      {0003}   
         4: DEVICE NAME            {0005}   
         5: BATTERY STATUS         {1000}   
         6: unknown:1820           {1820}   hidden
         7: REPROG CONTROLS        {1B00}   
         8: REPROG CONTROLS V2     {1B01}   
         9: WIRELESS DEVICE STATUS {1D4B}   
        10: unknown:1DF0           {1DF0}   hidden
        11: unknown:1DF3           {1DF3}   hidden
        12: ENCRYPTION             {4100}   
        13: KEYBOARD LAYOUT        {4520}   
     Has 12 reprogrammable keys:
         0: FN F1                      => Do Nothing One                is FN, reprogrammable
         1: FN F2                      => Do Nothing One                is FN, reprogrammable
         2: FN F3                      => Do Nothing One                is FN, reprogrammable
         3: FN F4                      => Do Nothing One                is FN, reprogrammable
         4: FN F5                      => Do Nothing One                is FN, reprogrammable
         5: FN F6                      => Do Nothing One                is FN, reprogrammable
         6: FN F7                      => Do Nothing One                is FN, reprogrammable
         7: FN F8                      => Do Nothing One                is FN, reprogrammable
         8: FN F9                      => Do Nothing One                is FN, reprogrammable
         9: Mute                       => Mute                          is FN
        10: Volume Down                => Volume Down                   is FN
        11: Volume Up                  => Volume Up                     is FN
     Battery: 70%, discharging.

# solaar config mouse
solaar: error: '_SETTINGS_LIST' object has no attribute 'low_res_scroll'
```

3) solaar commit ```f455723``` (20190716)
![Solaar f455723](https://user-images.githubusercontent.com/13176858/61754022-d07a3f80-adb1-11e9-8d30-e4c107b42d3f.png)

In the latter case:
```
# solaar show
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
solaar: error: Logitech receiver not found
```

**Comment by mfulz** [comment] 2019-07-25 23:09
Had the same issue and during playing around with debugging output I found, that inside receiver.py line 357:

`class Receiver(object):
        """A Unifying Receiver instance.

        The paired devices are available through the sequence interface.
        """
        number = 0xFF
        kind = None

        def __init__(self, handle, device_info):
                assert handle
                self.handle = handle
                assert device_info
                self.path = device_info.path
                # USB product id, used for some Nano receivers
                self.product_id = device_info.product_id

                # read the serial immediately, so we can find out max_devices
                # this will tell us if it's a Unifying or Nano receiver
                if self.product_id != 'c534':
                        serial_reply = self.read_register(_R.receiver_info, 0x03)
                        assert serial_reply
                        self.serial = _strhex(serial_reply[1:5])
                        self.max_devices = ord(serial_reply[6:7])
                else:
                        self.serial = 0
                        self.max_devices = 6

                if self.product_id == 'c539' or self.product_id == 'c53a':
                        self.name = 'Lightspeed Receiver'
                elif self.max_devices == 6:
                        self.name = 'Unifying Receiver'
                elif self.max_devices < 6:
                        self.name = 'Nano Receiver'
                else:
                        raise Exception("unknown receiver type", self.max_devices)
                self._str = '<%s(%s,%s%s)>' % (self.name.replace(' ', ''), self.path, '' if isinstance(self.handle, int) else 'T', self.handle)
                time.sleep(1)

                # TODO _properly_ figure out which receivers do and which don't support unpairing
                self.may_unpair = self.write_register(_R.receiver_pairing) is None
`

if I insert the time.sleep(1) after the self._str it works again.

Does anyone understand what is happening here?

**Comment by trulex** [comment] 2019-07-26 07:11
My output:
```
$ solaar show
Exception ignored in: <function Receiver.__del__ at 0x7f8894352158>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 370, in __del__
    self.close()
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 366, in close
    self._devices.clear()
AttributeError: 'Receiver' object has no attribute '_devices'
solaar: error: Logitech receiver not found
```

**Comment by mfulz** [comment] 2019-07-26 07:20
can you run solaar -d show ?
Further to be sure it's not a permission problem: Try it as user and as root.
Have you imported time module in the receiver.py?

**Comment by jean-christophe-manciot** [comment] 2019-07-26 07:24
As root, then as non-root:
```
# solaar -d show
09:22:48,210    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw0', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='2405', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 348, in __init__
    if self.product_id == 'c539' or slef.product_id == 'c53a':
NameError: global name 'slef' is not defined
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
solaar: error: Logitech receiver not found

$ solaar -d show
09:23:28,643    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw0', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='2405', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 348, in __init__
    if self.product_id == 'c539' or slef.product_id == 'c53a':
NameError: global name 'slef' is not defined
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
solaar: error: Logitech receiver not found
```

**Comment by mfulz** [comment] 2019-07-26 07:26
`NameError: global name 'slef' is not defined`

You still have the type in receiver.py line 348
Change slef to self this is still in the git codebase ^^

**Comment by FFY00** [comment] 2019-07-26 14:13
Could you quickly confirm that the last commit in master works?

**Comment by david-geiger** [comment] 2019-07-26 14:27
As I have the same problem with new 1.0.0 release:
I can confirm that the latest commit in master fixes this issue, now it can again detect my Logitech device (Wireless Mouse M560).

**Comment by FFY00** [comment] 2019-07-26 14:31
Okay, I'll just push some final fixes and then make a bugfix release.

**Comment by david-geiger** [comment] 2019-07-26 14:36
Also don't forget to update "__version__" in setup.py file :)

**Comment by FFY00** [comment] 2019-07-26 14:37
Yeah :smile:.

**Comment by mfulz** [comment] 2019-07-26 15:53
@FFY00 https://github.com/pwr-Solaar/Solaar/issues/524 looks like the same issue ;)

**Comment by david-geiger** [comment] 2019-07-26 17:05
hmmm! in setup.py file version is still "0.9.2", see line12:

__version__ = '0.9.2'

**Comment by FFY00** [comment] 2019-07-26 17:37
Well, this is resolved so closing.

**Closed by FFY00** 2019-07-26 17:37 UTC
