### ISSUE TITLE
GUI crash in gtk_cell_renderer_get_aligned_area with Menta themes under MATE

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#578] opened 2019-10-31 11:01 UTC
According to downstream [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1754278), the GUI is crashing in [`gtk_cell_renderer_get_aligned_area()`](https://github.com/GNOME/gtk/blob/622111f1caf9104251de79bfa27ccfba9614cc90/gtk/gtkcellrenderer.c#L1796) (failing the first `g_assert()` call) when selecting any device from the drop-down tray applet menu (About and Quit don't crash). The original reported has a receiver:
```
  USB id       : 046d:c52b
  Serial       : 9D2AACB0
    Firmware   : 24.07.B0030
    Bootloader : 02.09
    Other      : AA.AC
```
with M510 mouse and K750 keyboard paired and I'm able to reproduce this with a different receiver:
```
  USB id       : 046d:c52b
  Serial       : 7A7097E8
    Firmware   : 12.10.B0032
    Bootloader : 02.15
    Other      : AA.AA

```
with M310 and K520 paired, but not with yet another receiver:
```
  USB id       : 046d:c52b
  Serial       : AC5991B4
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
```
with M325 and K800 paired. These are all running solaar-1.0.1. I don't see any pattern here. Any ideas?

Here's the exact GTK error:
```
Gtk:ERROR:gtkcellrenderer.c:1796:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
Bail out! Gtk:ERROR:gtkcellrenderer.c:1796:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
```

**Comment by pfps** [comment] 2020-01-13 02:21
I just tried to reproduce this using the current version of Solaar (well, actually with a few changes that have not yet been merged, but I don't see how they can affect the situation).

I set up my receiver 
  USB id       : 046d:c52b
  Serial       : 965E9E17
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
with a K520 keyboard and an M510 mouse.
I turned the keyboard off and clicked on various items in the tray menu.
No problem whatsoever.

Do you have a more detailed sequence of events that cause the problem?

I am running F31, so probably newer GTK libraries, but I kind of doubt that that is relevant.

Do you know which cell is involved?

**Comment by rathann** [comment] 2020-01-13 22:45
The machine on which I was able to reproduce this is running F31 now, too. I'll check if I can still reproduce within the next few days.

**Comment by rathann** [comment] 2020-01-14 21:08
Alright, it looks like I can reproduce it on F31, too. The keyboard doesn't have to be off. It just crashes after selecting any entry from the drop-down menu of the tray icon. I'm using MATE desktop.

Log of `solaar -dd`: [solaar-dd.log](https://github.com/pwr-Solaar/Solaar/files/4061486/solaar-dd.log)

**Comment by pfps** [comment] 2020-01-15 15:59
Hmm.   That GTK error does look familiar.  But I don't know what it really means, nor how to fix it.  from my limited understanding it looks as if something is trying to figure out just which of the items in the tray menu are being selected.  That's not something in the Solaar code, I think, but in GTK itself or in the python interface to GTK.  If so, I'm not sure what the remedy should be.
One thing to check is whether the tray menu shows the expected icons.  The tray menu should be showing an entry for the receiver, entries for each of the devices, a line, and then an About Solaar entry and a Quit entry.  Each entry should have an icon.  If this is not what you are seeing then the problem might be in Solaar, or the Solaar installation script.
The other avenue of approach would be to see if the problem persists in the current version of Solaar here.

**Comment by rathann** [comment] 2020-01-16 10:37
The menu looks like this:
![solaar-tray-menu-issue-578](https://user-images.githubusercontent.com/5873507/72517441-adf24c00-3853-11ea-8492-95986d36819b.png)
Should it have an icon for the receiver, too?

Do you mean current git master HEAD by *current version*?

**Comment by pfps** [comment] 2020-01-16 11:03
What I see for the tray menu is

![Screenshot_2020-01-16_05-43-23](https://user-images.githubusercontent.com/6618235/72518455-66ec6280-3823-11ea-974d-a53590b99cda.png)

So, yes, there should be an icon for the receiver.

Solaar is looking for an icon for preferences-desktop-peripherals.  It may be that if there is no such icon the tray menu code gets confused.  Try adding that menu in a place that Solaar looks in.  (I think that Solaar will pick the icon up even from the Solaar icon directories but you may have to put it in your icon theme directory.)

I don't think running from github will help, as I don't think that the tray menu part of Solaar has been changed recently.

**Comment by rathann** [comment] 2020-01-16 11:16
That icon seems to be present:
```
$ find /usr/share/icons/ -type f | grep preferences-desktop-peripherals
/usr/share/icons/HighContrast/scalable/categories/preferences-desktop-peripherals.svg
/usr/share/icons/Adwaita/22x22/legacy/preferences-desktop-peripherals.png
/usr/share/icons/Adwaita/32x32/legacy/preferences-desktop-peripherals.png
/usr/share/icons/Adwaita/24x24/legacy/preferences-desktop-peripherals.png
/usr/share/icons/Adwaita/48x48/legacy/preferences-desktop-peripherals.png
/usr/share/icons/Adwaita/16x16/legacy/preferences-desktop-peripherals.png
/usr/share/icons/oxygen/base/128x128/categories/preferences-desktop-peripherals.png
/usr/share/icons/oxygen/base/22x22/categories/preferences-desktop-peripherals.png
/usr/share/icons/oxygen/base/32x32/categories/preferences-desktop-peripherals.png
/usr/share/icons/oxygen/base/64x64/categories/preferences-desktop-peripherals.png
/usr/share/icons/oxygen/base/48x48/categories/preferences-desktop-peripherals.png
/usr/share/icons/oxygen/base/16x16/categories/preferences-desktop-peripherals.png
/usr/share/icons/gnome/22x22/categories/preferences-desktop-peripherals.png
/usr/share/icons/gnome/32x32/categories/preferences-desktop-peripherals.png
/usr/share/icons/gnome/24x24/categories/preferences-desktop-peripherals.png
/usr/share/icons/gnome/48x48/categories/preferences-desktop-peripherals.png
/usr/share/icons/gnome/16x16/categories/preferences-desktop-peripherals.png
/usr/share/icons/ContrastHigh/scalable/categories/preferences-desktop-peripherals.svg
/usr/share/icons/mate/22x22/categories/preferences-desktop-peripherals.png
/usr/share/icons/mate/32x32/categories/preferences-desktop-peripherals.png
/usr/share/icons/mate/24x24/categories/preferences-desktop-peripherals.png
/usr/share/icons/mate/48x48/categories/preferences-desktop-peripherals.png
/usr/share/icons/mate/16x16/categories/preferences-desktop-peripherals.png
```
I'll check where solaar (GTK?) is looking for it.

**Comment by pfps** [comment] 2020-01-16 11:22
Solaar should be complaining if it can't find the image, as in

(solaar:540531): Gtk-WARNING **: 06:16:03.158: Error loading theme icon 'preferences-desktop-peripheralsXX' for stock: Icon 'preferences-desktop-peripheralsXX' not present in theme gnome

If you are not seeing these messages than it is picking up an icon.

The next guess is that the image you are picking up is somehow unsuitable (or damaged in some way) but how can that be?

Just to be sure, the error you see occurs when you click anywhere in the tray menu, including in the Quit item?  Or is it just in particular parts of the menu?  Do you even see each of the menu items being highlighted when the mouse is over them?

**Comment by rathann** [comment] 2020-01-16 12:10
Solaar manages to find a suitable icon, strace shows this:
```
12534 openat(AT_FDCWD, "/usr/share/icons/mate/32x32/categories/preferences-desktop-peripherals.png", O_RDONLY) = 16
```
I checked the file, it's a valid PNG 32x32px image:
![preferences-desktop-peripherals](https://user-images.githubusercontent.com/5873507/72523904-109e1480-3861-11ea-94f4-f79bf6ef718f.png)

**About** and **Quit** menu items don't cause a crash, only the items for the receiver and paired devices do. All items get highlighted as usual when the mouse pointer is over them.

**Comment by pfps** [comment] 2020-01-16 12:55
So why isn't the image showing up?  I don't see any reason why.
If the highlighting works, why the crash?  GTK is getting the right size to do the highlighting.
I'm running Fedora 31, why don't I experience the crash?  The only difference is that my theme appears to be gnome. Can you switch to that theme?

It looks to me as if the problem is in GTK.  However GtkImageMenuItem is deprecated so getting the problem looked at may be difficult.

The relevant code is in tray.py - _add_receiver and _add_device.

**Comment by pfps** [comment] 2020-01-16 13:21
I don't see BlueMenta as a theme when  I do dnf search icon-theme.  How is it installed?

**Comment by rathann** [comment] 2020-01-16 13:28
Sorry, I was talking about desktop themes. From what I can see, both TraditionalOk and BlueMenta themes use MATE icon theme. And actually, using GNOME icon theme with BlueMenta also crashes. So I'd say the chosen desktop theme is the trigger, not the icon theme. I can only reproduce crashes with either Menta or BlueMenta desktop theme. None of the others I have installed triggers a crash.

**Comment by pfps** [comment] 2020-01-16 14:13
Looking at old GTK-related bug reports it appears that there is a long-running problem with setting the width of elements.  Sometimes the width ends up as zero and this triggers this kind of assertion.  So setting min-width might be a solution, but on what?  It looks as if this is supposed to be done using CSS nowadays.

**Comment by pfps** [comment] 2020-01-16 14:34
Success!  (Actually failure!)   With BlueMenta theme I get the crash.  
The main solaar window shows up momentarily and then the crash happens.  So it might be a problem with the main solaar window in some themes.
But checking with my changes to start up the main window directly I do not have a crash.  I can close the main window and open it from the tray with no crash.  But if I start up with the main window not showing the crash happens when the main window is first shown.
I now expect that the problem is that the main window might be being set up in a way that is not completely correct.

**Comment by pfps** [comment] 2020-01-16 15:43
So presenting the main window at startup does not crash but presenting it later does.  It is the realization part of presentation that is crashing presumably because something has a small (probably zero) width.  But what is too small and why it only happens with some themes is beyond me.
However, there is a band-aid - realizing the main window at startup.
In window.py add _window.realize() at the end of init.  This always realizes the window at startup.  I'll submit a pull request for this but could you also try this band-aid?

**Comment by raveit65** [comment] 2020-01-16 16:09
I don't think that using a padding inside GtkTreeView or GtkCellGtkCellRenderer is a theme issue.
See rhbz report.
In short:
Commenting out those 2 lines in gtkwidget.css avoid this crash.

https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/gtk-widgets.css#L4631

treeview.view {
/*    padding: 0px 1px;*/
}

https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/gtk-widgets.css#L4771

.cell {
/*	padding: 2px;*/
	text-shadow: none;
}

But using a padding in treeview.view {} or .cell {} is quite common and not a theme issue. Other applications (eg. gtk3-widget-factory or others) with a treeview don't crash with this setting.
And i am in doubt that this is an bug in GtkCellGtkCellRenderer itself.

**Comment by pfps** [comment] 2020-01-16 16:34
I agree that the padding itself is likely not the cause.  I expect that the padding somehow makes some other element too small and that is dependent on how Solaar is setting up its tree view and how the theme modifies the rendering.
But shouldn't GTK be defensive about this sort of thing?

**Comment by raveit65** [comment] 2020-01-16 17:00
Not sure.
I think the problem is in GtkCellRenderer code because 
treeview.view {
 padding: 0px 1px;
}
is a setting for GtkTreeView and all his childs.
Do you use a fixed size for the treeview somewhere?

**Comment by raveit65** [comment] 2020-01-17 17:17
@pfps 
If you add a style class with `gtk_style_context_add_class` to solar window, than i can add a specific setting to Menta themes without padding.
Eg:
```
.solar treeview.view {
    padding: 0px;
}

.solar .cell {
    padding: 0px;
}
```
Example in one of our applications.
https://github.com/mate-desktop/mate-screensaver/commit/e3d8ca494335bcea1aa776614ed17c75012e1f2b

**Comment by pfps** [comment] 2020-01-17 17:50
I'm not an expert in GTK.  :-)
What I see is a moderately complex treeview, with switching between two panels.  It may be that trying to realize the window when one of these panels is not supposed to be visible is causing the problem.
In any case, I can certainly *try* to add the context.  Should it be added to the main window?  Should I check for GTK 3, or is that not really needed anymore?

**Comment by raveit65** [comment] 2020-01-17 18:13
> Should I check for GTK 3, or is that not really needed anymore?

I think the solar application use gtk3, because i can inspect it with gtk3-inspector tool, or not ?  :)

>  Should it be added to the main window?

This is the crashing window + gtk3-inspector
![Screenshot at 2020-01-17 19-06-56](https://user-images.githubusercontent.com/961604/72635232-a10d4f80-395c-11ea-8600-9cbc320c93ad.png)

offtopic on
I am still wondering why i see 2 entries (paired devices) of my logitec mouse?
offtopic off

**Comment by raveit65** [comment] 2020-01-17 18:18
The gtk3 check isn't needed. At the time of the example MATE desktop was switching from Gtk2 to Gtk3.

**Comment by pfps** [comment] 2020-01-17 21:26
@raveit65 You mean two mouse entries in the Solaar window?  Those are two different mice.  If you click on the little light bulb you can see more information about each of them.
Why the split model numbers?  Logitech creates mice that look different outside but look the same to software.  (Well perhaps the model is encoded somewhere, but Solaar is only looking at the USB id.)

**Comment by pfps** [comment] 2020-01-17 22:22
I found an actual problem.
Two icon columns in the tree-view had fixed-width set to 1 pixel!  With the padding that may have pushed the size for the column content to zero or less, which then violated assertion, or at least that is my guess.
In any case, turning off the fixed-width has good visual effects, as it was causing the icons in the tree-view to be invisible.
If you want to see the difference, just comment out the two lines in window.py that contain set_fixed_width(1).

**Comment by pfps** [comment] 2020-01-17 23:20
Pull request #643 should fix the crash and also adds the solaar style class to the main window.

**Comment by raveit65** [comment] 2020-01-18 10:08
PR fixes the crashes with Menta themes and new appearance with the visible icons looks much better than before.
And yes, a fixed-width=1 is a conflict to padding settings.
But in my opinion Gtk or python should handle a default setup in code, no matter what a gtk theme does.
I didn't know this application before for paring logitec devices, very useful.
Only the symbolic icon in notification-area doesn't look so nice for me, i prefer regular colored icons.
But this is my personal taste ;)
Thanks for the quick fix.

**Comment by raveit65** [comment] 2020-01-18 10:16
I forgot, the style class is shown with gtk3-inspector.
window.background.solaar
Now a theme artist can style the window without styling other applications, which is a good band aid, ihmo.
With BlueMenta theme:
![Screenshot at 2020-01-18 11-12-03](https://user-images.githubusercontent.com/961604/72662130-9a75eb00-39e3-11ea-89e1-2caa10a90307.png)

**Comment by raveit65** [comment] 2020-01-18 11:22
If i remove all occurrence of `_has_mint_icons` in icons.py i have a beautiful green colored icon from mate-icon-theme in na-tray.
Looks good with HIDPI monitor, or not?
![Screenshot at 2020-01-18 12-17-20](https://user-images.githubusercontent.com/961604/72662891-94383c80-39ec-11ea-872c-0d7dc7d2b240.png)
Why hard-coding to linuxmint preferences?
Most other distros with MATE desktop are using regular icons, which is vanila MATE default.

**Comment by raveit65** [comment] 2020-01-18 12:11
It seems solaar reads only the first icon-set in order of icon.py :/
Diff LinuxMint first --> symbolic icons.
```
--- icons.py.orig	2020-01-18 12:44:25.456513000 +0100
+++ icons.py	2020-01-18 12:58:08.353247351 +0100
@@ -73,6 +73,7 @@ def _look_for_application_icons():
 
 _default_theme = None
 _has_mint_icons = None
+_has_mate_icons = None
 _has_gpm_icons = None
 _has_oxygen_icons = None
 _has_gnome_icons = None
@@ -90,9 +91,11 @@ def _init_icon_paths():
 	if _log.isEnabledFor(_DEBUG):
 		_log.debug("icon theme paths: %s", _default_theme.get_search_path())
 
-	global _has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons
+	global _has_mate_icons, _has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons
 
 	_has_mint_icons = _default_theme.has_icon('battery-good-symbolic')
+	_has_mate_icons = _default_theme.has_icon('battery-caution-charging') and \
+						_default_theme.has_icon('battery-full-charged')
 	_has_gpm_icons = _default_theme.has_icon('gpm-battery-020-charging')
 	_has_oxygen_icons = _default_theme.has_icon('battery-charging-caution') and \
 						_default_theme.has_icon('battery-charging-040')
@@ -101,10 +104,10 @@ def _init_icon_paths():
 	_has_elementary_icons = _default_theme.has_icon('battery-020-charging')
 
 	if _log.isEnabledFor(_DEBUG):
-		_log.debug("detected icon sets: Mint %s, gpm %s, oxygen %s, gnome %s, elementary %s",
-						_has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons)
+		_log.debug("detected icon sets: Mint %s, mate %s, gpm %s, oxygen %s, gnome %s, elementary %s",
+						_has_mint_icons, _has_mate_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons)
 
-	if (not _has_mint_icons and not _has_gpm_icons and not _has_oxygen_icons and
+	if (not _has_mint_icons and not _has_mate_icons and not _has_gpm_icons and not _has_oxygen_icons and
 		not _has_gnome_icons and not _has_elementary_icons):
 		_log.warning("failed to detect a known icon set")
 
@@ -138,6 +141,14 @@ def _battery_icon_name(level, charging):
 		level_name = ('caution', 'low', 'good', 'full')[3*(level_approx // 100)]
 		return 'battery-%s%s-symbolic' % (level_name, '-charging' if charging else '')
 
+	if _has_mate_icons:
+		if level == 100 and charging:
+			return 'battery-full-charged'
+		if level_approx == 0 and charging:
+			return 'battery-caution-charging'
+		level_name = ('empty', 'caution', 'low', 'good', 'good', 'full')[level_approx // 20]
+		return 'battery-%s%s' % (level_name, '-charging' if charging else '')
+
 	if _has_gpm_icons:
 		if level == 100 and charging:
 			return 'gpm-battery-charged'
```
Diff Mate first --> regular colored icons
```
--- icons.py.orig	2020-01-18 12:44:25.456513000 +0100
+++ icons.py	2020-01-18 13:03:17.321782608 +0100
@@ -72,6 +72,7 @@ def _look_for_application_icons():
 
 
 _default_theme = None
+_has_mate_icons = None
 _has_mint_icons = None
 _has_gpm_icons = None
 _has_oxygen_icons = None
@@ -90,8 +91,10 @@ def _init_icon_paths():
 	if _log.isEnabledFor(_DEBUG):
 		_log.debug("icon theme paths: %s", _default_theme.get_search_path())
 
-	global _has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons
+	global _has_mate_icons, _has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons
 
+	_has_mate_icons = _default_theme.has_icon('battery-caution-charging') and \
+						_default_theme.has_icon('battery-full-charged')
 	_has_mint_icons = _default_theme.has_icon('battery-good-symbolic')
 	_has_gpm_icons = _default_theme.has_icon('gpm-battery-020-charging')
 	_has_oxygen_icons = _default_theme.has_icon('battery-charging-caution') and \
@@ -101,10 +104,10 @@ def _init_icon_paths():
 	_has_elementary_icons = _default_theme.has_icon('battery-020-charging')
 
 	if _log.isEnabledFor(_DEBUG):
-		_log.debug("detected icon sets: Mint %s, gpm %s, oxygen %s, gnome %s, elementary %s",
-						_has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons)
+		_log.debug("detected icon sets: mate %s, Mint %s, gpm %s, oxygen %s, gnome %s, elementary %s",
+						_has_mate_icons, _has_mint_icons, _has_gpm_icons, _has_oxygen_icons, _has_gnome_icons, _has_elementary_icons)
 
-	if (not _has_mint_icons and not _has_gpm_icons and not _has_oxygen_icons and
+	if (not _has_mate_icons and not _has_mint_icons and not _has_gpm_icons and not _has_oxygen_icons and
 		not _has_gnome_icons and not _has_elementary_icons):
 		_log.warning("failed to detect a known icon set")
 
@@ -132,6 +135,14 @@ def _battery_icon_name(level, charging):
 
 	level_approx = 20 * ((level  + 10) // 20)
 
+	if _has_mate_icons:
+		if level == 100 and charging:
+			return 'battery-full-charged'
+		if level_approx == 0 and charging:
+			return 'battery-caution-charging'
+		level_name = ('empty', 'caution', 'low', 'good', 'good', 'full')[level_approx // 20]
+		return 'battery-%s%s' % (level_name, '-charging' if charging else '')
+
 	if _has_mint_icons:
 		if level == 0:
 			return 'battery-empty%s-symbolic' % ('-charging' if charging else '')
```

**Comment by pfps** [comment] 2020-01-18 13:03
A fix for the icon selection might be in the works.  See PR #548 
If you have suggestions on how icon selection should be improved you might want to comment there, particularly if you know how it is usually done.  One problem is, I think, that different themes use (or used to use) different icon names.

**Comment by raveit65** [comment] 2020-01-18 14:41
I tried this PR but it gives me only errors.
To much linuxmint for my taste.
Honestly , i am happy that you have fixed this PR.
The icon style isn't really important for me.
Thanks again.

**Closed** 2020-01-21 03:11 UTC
Labels: bug

**Comment by dougK44883** [comment] 2020-05-18 19:47
```
**
Gtk:ERROR:../../../../gtk/gtkcellrenderer.c:1796:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
Bail out! Gtk:ERROR:../../../../gtk/gtkcellrenderer.c:1796:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
Aborted
```
I'm currently struggling with is exact same issue when I click on anything other than about... or quit (which terminates)
``solaar 1.0.1``
``MATE Desktop Environment 1.24.0``
I don't use meta theme - [bluebird-gtk-theme](https://packages.debian.org/bullseye/bluebird-gtk-theme) although I have clicked on Appearance | Theme > Customize >  Controls > BlueMenta 

I have never seen solaar work any more than this one several machines I have, (1) K830 (2) K400.   It almost seems it just doesn't work on mate-desktop?  Have never seen an icon for the receiver either, sometimes, in the tray it's solaar's icon, other times it's a battery.  

Power Stats suggest battery is around 50% and solaar show an exclamation and red battery.
Sometimes my keyboard wakes my system... other times it won't?

**Comment by pfps** [comment] 2020-05-18 19:49
I think these are fixed in the current version of Solaar in this repository.

**Comment by dougK44883** [comment] 2020-05-18 20:07
> I think these are fixed in the current version of Solaar in this repository.

I noticed ``release 1.0.2rc3`` but it's not available as a package or _installabale_ anywhere.  (End users don't usually build or "try" to manually install and hope for the best)

I do hope it's released soon someday, I realize this is a free and open application and appericate all the work everyone has contributed of their own time. --thanks

**Comment by pfps** [comment] 2020-05-18 20:13
If you have 1.0.1 installed and are using python3 then downloading and running from this repository should be as easy as
```
git clone https://github.com/pwr-Solaar/Solaar.git
./Solaar/bin/solaar
```
YMMV of course.

**Comment by pfps** [comment] 2020-05-18 20:19
You should also be able to install and run a recent version of Solaar via
```
pip install --user solaar==1.0.2rc3
~/.local/bin/solaar
```

**Comment by dougK44883** [comment] 2020-05-18 21:24
THANKS!  It didn't look overly complex, and that looks even easier.  
Although I'm not a developer, I'm well beyond beginner... I've just stumbled over hurdles for things that are suppose to be straight forward all too often :(

**Comment by dougK44883** [comment] 2020-05-18 22:21
pfps you rock!  pip install [not user] was/is painless  I never knew just how truly awesome solaar is!!  Greatest... I get my Fx keys back with the swap switch (can't say how much a linux user misses Fx keys and how useless the "special" keys are)  

Again, thanks to all who contributed to this project!
