### ISSUE TITLE
OSError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by supermaz** [pwr-Solaar/Solaar#1605] opened 2022-05-16 11:45 UTC
Hi,

I'm using Gentoo and I wanted to configure my new Bolt Receiver which came with my new Lift Mouse.

But Solaar is unable to open the device:

```
workstation ~ $ LC_ALL=C solaar -d
13:42:52,349    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path='/dev/hidraw7', vendor_id='046D', product_id='C548', serial='', release=None, manufacturer=None, product=None, interface=2, driver='hid-generic', bus_id=3, isDevice=None)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/logitech_receiver/receiver.py", line 389, in open
    handle = _base.open_path(device_info.path)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 161, in open_path
    return _hid.open_path(path)
  File "/usr/lib/python3.9/site-packages/hidapi/udev.py", line 294, in open_path
    return _os.open(device_path, _os.O_RDWR | _os.O_SYNC)
OSError: [Errno 16] Device or resource busy: '/dev/hidraw7'
13:42:52,350  WARNING [MainThread] solaar.listener: failed to open DeviceInfo(path='/dev/hidraw7', vendor_id='046D', product_id='C548', serial='', release=None, manufacturer=None, product=None, interface=2, driver='hid-generic', bus_id=3, isDevice=None)
```

Do you have any idea why the hidraw device is blocked? I tried with lsof but couldn't find anything.

Same when running with sudo.

Kernel 5.17.8, Solaar 1.1.3

**Comment by supermaz** [comment] 2022-05-16 19:07
```
workstation ~ $ LC_ALL=C solaar -d show
21:06:07,127    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path='/dev/hidraw7', vendor_id='046D', product_id='C548', serial='', release=None, manufacturer=None, product=None, interface=2, driver='hid-generic', bus_id=3, isDevice=None)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/logitech_receiver/receiver.py", line 389, in open
    handle = _base.open_path(device_info.path)
  File "/usr/lib/python3.9/site-packages/logitech_receiver/base.py", line 161, in open_path
    return _hid.open_path(path)
  File "/usr/lib/python3.9/site-packages/hidapi/udev.py", line 294, in open_path
    return _os.open(device_path, _os.O_RDWR | _os.O_SYNC)
OSError: [Errno 16] Device or resource busy: '/dev/hidraw7'
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 201, in run
    raise Exception('No devices found')
Exception: No devices found
```
Nothing that helps me. Indeed, lsof doesn't show anything. Do you have HIDPP enabled in the kernel?

**Comment by pfps** [comment] 2022-05-16 19:24
Strange.   Can you use your Lift Mouse at all connected through the Bolt receiver?

I don't think that the kernel itself knows much about HID++ (or HIDPP).   There is an hid_logitech_hidpp driver that implements a few HID++ things (including name, serial, battery, scroll wheel resolution, and force feedback) but Solaar doesn't need that driver running to work.

Try unplugging the receiver and replugging it again and see what kernel messages are printed (`journalctl -f` before you unplug the receiver).

**Comment by supermaz** [comment] 2022-05-17 12:10
I paired the mouse using a Windows PC that I need to use sometimes, so the mouse is working fine.
I thought maybe the hid_logitech_hidpp driver is taken control of the hidraw device. I might compile it out and see if that makes any difference. Unplugging/Plugging das make any difference, tried that couple of times before.

**Comment by pfps** [comment] 2022-05-17 12:14
The driver shouldn't take control of the device.  On the contrary, the driver should make the device available.

The problem might be a timing issue.  You could try having Solaar running before the receiver is inserted, if this is possible on your system.   Or you could try running Solaar only after the receiver is inserted.

**Comment by pfps** [comment] 2022-05-17 12:59
If you've tried every combination then I don't know what is going on.

Can you connect your mouse via Bluetooth?  If so, try that.
If you have access to another kind of Logitech receiver, you could try that.

**Comment by pfps** [comment] 2022-05-17 13:09
Another thing you could do is to try to write to the device directly.  Try something like `cat - > /dev/hidraw7` and see whether that produces an error message.

Solaar includes the hidconsole tool.   Clone Solaar and run `./tools/hidconsole /dev/hidraw7` from the cloned directory and see whether that produces an error.

**Comment by supermaz** [comment] 2022-05-18 05:47
Its hidraw 5 - 7.
5 can be read, but no output, 6 is the mouse and can be read, 7 cannot, device busy.

**Comment by pfps** [comment] 2022-05-18 11:08
I see the exact same kernel messages with my Bolt receiver.  Solaar uses the device node that on your system is /dev/hidraw7.

So something is going wrong with /dev/hidraw7 before Solaar is involved.   I don't know what this could be.   Two possibilities are that some driver is misbehaving or some program is locking the device.

Further investigation is going to require expertise that I don't have.

**Comment by squadramunter** [comment] 2022-05-23 16:30
@pfps I assume you did unplug and replug the receiver already? This is what solved the problem for my Unify Receiver and it's working fine for me. Since the message says busy it means Solaar can't lock on that device. When unplugging the receiver it may reconnect properly and Solaar should take care of it.

**Comment by pfps** [comment] 2022-06-29 19:16
It sure looks as if something is going wrong before Solaar starts.  Given that the problem also affects `solaar show` I don't see that there is any way that the Solaar GUI startup or thread stuff could be involved.

One thing to try is to run `solaar -ddd` and post the output.  This will help show where in Solaar's startup the problem occurs.  If it is very early then there is way that Solaar is involved.

**Comment by supermaz** [comment] 2022-06-29 19:18
Nothing of interest there. The file is already in use after startup, before solaar is started. So I don't think it is solaar's fault, I just hoped that you guys know which other software or kernel options blocks access.

**Comment by pfps** [comment] 2022-06-29 19:23
No, no further information from here.  I'm going to close this issue.  If you find out the cause you can post to the issue even if it is closed.

**Closed by pfps** 2022-06-29 19:23 UTC
