### ISSUE TITLE
val_to_string error in solaar show

### ISSUE THREAD

**Issue by skitt** [pwr-Solaar/Solaar#1790] opened 2022-10-13 10:44 UTC
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.5
- Distribution: Ubuntu 22.10
- Kernel version (ex. `uname -srmo`): 5.19.0-19-generic
- Output of `solaar show`:

<details>

```
Solaar version 1.1.5

Unifying Receiver
  Device path : /dev/hidraw3
  USB id : 046d:C52B
  Serial : 538E9E94
    Firmware : 12.10.B0032
    Bootloader : 02.14
    Other : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 2=213

  1: Wireless Touch Keyboard K400
     Device path : /dev/hidraw4
     WPID : 4024
     Codename : K400
     Kind : keyboard
     Protocol : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: AF35CB44
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

  2: MX Master 3 Wireless Mouse
     Device path : /dev/hidraw5
     WPID : 4082
     Codename : MX Master 3
     Kind : mouse
     Protocol : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 78D9E28A
     Model ID: B02340820000
     Unit ID: 78D9E28A
        Bootloader: BOT 95.00.B0013
          Firmware: MPM 19.01.B0015
             Other:
     The power switch is located on the base.
     Supports 34 HID++ 2.0 features:
         0: ROOT {0000} V0
         1: FEATURE SET {0001} V0
         2: DEVICE FW VERSION {0003} V3
            Firmware: Bootloader BOT 95.00.B0013 0000D8279515
            Firmware: Firmware MPM 19.01.B0015 40826A9CA89D
            Firmware: Other
            Unit ID: 78D9E28A Model ID: B02340820000 Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME {0005} V0
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0
         5: RESET {0020} V0
         6: CRYPTO ID {0021} V1
         7: DEVICE FRIENDLY NAME {0007} V0
            Friendly Name: MX Master 3
         8: BATTERY STATUS {1000} V1
            Battery: 50%, discharging, next level 20%.
         9: REPROG CONTROLS V4 {1B04} V4
            Azioni tasto/pulsante (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Azioni tasto/pulsante : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 210, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 293, in run
    _print_device(dev)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 232, in _print_device
    v = setting.val_to_string(setting._device.persister.get(setting.name))
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 237, in val_to_string
    return self._validator.to_string(value)
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 1085, in to_string
    return '{' + ', '.join([element_to_string(k, value[k]) for k in sorted(value)]) + '}'
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

N/A

- Errors or warrnings from Solaar:

**Describe the bug**
`solaar show` terminates with an error. This isn’t the same line as handled by https://github.com/pwr-Solaar/Solaar/commit/3a6b479e8b7faa1d0dcc02b79864fc08674eef0a

**To Reproduce**
1. Run `solaar show` (with the same devices as the reporter)

**Screenshots**

**Additional context**

This is forwarded from https://bugs.launchpad.net/ubuntu/+source/solaar/+bug/1992589

**Comment by pfps** [comment] 2022-10-13 11:13
The problem is caused by an incorrect conversion of information in the user's ~/.config/solaar/config.yaml file.   The incorrect conversion was fixed in https://github.com/pwr-Solaar/Solaar/commit/193e280e879131105039956e6b9adf3b57973a43 The bad entries are removed by https://github.com/pwr-Solaar/Solaar/commit/be81013704c81c23088c739bb45c23223f84350a  Neither of these commits are in any released version of Solaar.

To fix the problem without these patches edit ~/.config/solaar/config.yaml file to remove string keys in the divert-keys setting.  Alternatively remove the entire divert keys setting.  Alternatively remove the entire file.  In the first two cases the user may have to redo the divert-keys setting.  In the last case the user will have to redo all their settings.

**Closed by pfps** 2022-10-13 11:13 UTC
Labels: bug

**Comment by skitt** [comment] 2022-10-13 11:40
Thanks for the info!
