### ISSUE TITLE
MX Vertical not picked up.

### ISSUE THREAD

**Issue by AgoodFriendOfSatan** [pwr-Solaar/Solaar#1224] opened 2021-08-09 01:31 UTC
I'm not sure exactly if I did something wrong, but I don't think Solaar has picked-up my MX Vertical. At least I don't see in the GUI.

Is there something that I would need to do that would be better in command line?

Details of my system information and what I got from command line are below.

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-25-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10870H CPU @ 2.20GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics

bugger@bugger-Gazelle:~$ sudo add-apt-repository ppa:solaar-unifying/stable
sudo apt-get update
[sudo] password for bugger: 
Repository: 'deb http://ppa.launchpad.net/solaar-unifying/stable/ubuntu/ hirsute main'
More info: https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/solaar-unifying-ubuntu-stable-hirsute.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/solaar-unifying-ubuntu-stable-hirsute.list
Adding key to /etc/apt/trusted.gpg.d/solaar-unifying-ubuntu-stable.gpg with fingerprint 643FF34AF9151DC814DD3A1B2303D595EE907473
Get:1 file:/var/lib/preinstalled-pool focal InRelease
Ign:1 file:/var/lib/preinstalled-pool focal InRelease
Get:2 file:/var/lib/preinstalled-pool focal Release
Err:2 file:/var/lib/preinstalled-pool focal Release
  File not found - /var/lib/preinstalled-pool/dists/focal/Release (2: No such file or directory)
Hit:3 http://us.archive.ubuntu.com/ubuntu hirsute InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]                                                 
Hit:5 http://security.ubuntu.com/ubuntu hirsute-security InRelease                                                           
Hit:6 https://packages.teejeetech.com/aptik/0/LjR3HfKiNh/ubuntu/focal/amd64 stable InRelease                                 
Ign:7 http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute InRelease                              
Hit:8 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu hirsute InRelease                     
Hit:9 https://repo.protonvpn.com/debian stable InRelease                                                 
Get:10 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]    
Get:11 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages [302 kB]
Hit:12 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute InRelease
Hit:13 http://ppa.launchpad.net/solaar-unifying/ppa/ubuntu hirsute InRelease       
Get:14 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu hirsute InRelease [18.1 kB]
Err:15 http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute Release
  404  Not Found [IP: 91.189.95.85 80]
Get:16 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu hirsute/main amd64 Packages [624 B]
Get:17 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu hirsute/main i386 Packages [624 B]
Get:18 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu hirsute/main Translation-en [284 B]
Reading package lists... Done                        
E: The repository 'file:/var/lib/preinstalled-pool focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Get:1 file:/var/lib/preinstalled-pool focal InRelease
Ign:1 file:/var/lib/preinstalled-pool focal InRelease
Get:2 file:/var/lib/preinstalled-pool focal Release
Err:2 file:/var/lib/preinstalled-pool focal Release
  File not found - /var/lib/preinstalled-pool/dists/focal/Release (2: No such file or directory)
Hit:3 http://us.archive.ubuntu.com/ubuntu hirsute InRelease
Hit:4 http://security.ubuntu.com/ubuntu hirsute-security InRelease                                                           
Hit:5 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease                                                          
Get:6 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]                                               
Ign:7 http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute InRelease                              
Hit:8 https://packages.teejeetech.com/aptik/0/LjR3HfKiNh/ubuntu/focal/amd64 stable InRelease        
Hit:9 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu hirsute InRelease                      
Hit:10 https://repo.protonvpn.com/debian stable InRelease
Hit:11 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute InRelease
Hit:12 http://ppa.launchpad.net/solaar-unifying/ppa/ubuntu hirsute InRelease
Hit:13 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu hirsute InRelease
Err:14 http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
E: The repository 'file:/var/lib/preinstalled-pool focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by pfps** [comment] 2021-08-09 11:20
Please provide the information asked for by the bug template.  What version of Solaar are you running and what is the output of `solaar show`.

I don't know whether your downloading from the PPA worked.  There appears to be some errors there.  You might want to try to download directly from this repository.

**Comment by AgoodFriendOfSatan** [comment] 2021-08-10 04:55
uninstalled and reinstalled.

`$ solaar show
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 203, in run
    raise Exception('No devices found')
Exception: No devices found

Also endered solaar --window=show but got ERROR: Solaar depends on a udev file that is not present.

Also during installation I got:

Err:2 file:/var/lib/preinstalled-pool focal Release
  File not found - /var/lib/preinstalled-pool/dists/focal/Release (2: No such file or directory)

and

  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
E: The repository 'file:/var/lib/preinstalled-pool focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/appgrid/stable/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by pfps** [comment] 2021-08-10 11:55
I need the version of Solaar from `solaar --version`.

If the version is not  1.0.6 I  suggest you clone Solaar from this repository and run it.

**Comment by AgoodFriendOfSatan** [comment] 2021-08-10 12:41
Sorry, I forgot to add that. Long night.
1.0.6

**Comment by pfps** [comment] 2021-08-10 14:17
1.0.6 should handle an MX vertical.  It does for me.  If the device isn't active it won't show up.

The  error is probably caused by the fact that the Ubuntu PPA puts the Solaar udev rule in a different place than Solaar expects.  Solaar should still work fine.  If you just installed Solaar you may need to get the rule used.  One way to do this is to reboot.

Solaar adds permissions for the device nodes for the mouse.  Please provide output of `ls -l /dev/hidraw*` to check that this is done correctly.  Also provide output of `lsusb` to see where the mouse is connected, if you are connecting via a receiver or USB.  If you are connecting via bluetooth, use `bt-device -l`.

**Comment by AgoodFriendOfSatan** [comment] 2021-08-11 01:13
These are the output. I just came home, so I just fired up my computer. The mouse is connected by USB.

bugger@bugger-Gazelle:~$ ls -l /dev/hidraw*
crw------- 1 root root 241, 0 Aug 10 17:52 /dev/hidraw0
bugger@bugger-Gazelle:~$ lsusb
Bus 002 Device 003: ID 0bc2:ac1a Seagate RSS LLC Ultra Touch HDD
Bus 002 Device 002: ID 2109:0813 VIA Labs, Inc. VL813 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 5986:9102 Acer, Inc BisonCam,NB Pro
Bus 001 Device 004: ID 8087:0026 Intel Corp. 
Bus 001 Device 002: ID 2109:2813 VIA Labs, Inc. VL813 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by pfps** [comment] 2021-08-11 09:34
The output doesn't show the mouse or a receiver.  Was the mouse connected and active at the time?

There should be one or more lines in the output of `ls -l /dev/hidraw*` that have a `'` in them, indicating that the Solaar udev rule has added special permissions to interact directly with the mouse, as in
```
crw-rw----+ 1 root root 240, 3 Aug 11 05:25 /dev/hidraw3
```

There should be a line in the output of `lsusb` showing the mouse or its receiver, indicating the connection to the mouse, as in
```
Bus 003 Device 116: ID 046d:c52b Logitech, Inc. Unifying Receiver
```
or 
```
Bus 003 Device 117: ID 046d:c08d Logitech, Inc. G502 LIGHTSPEED Wireless Gaming Mouse
```

If the mouse is attached via BlueTooth, then `bt-device -l` should list it, as in 
```
Device CA:91:D3:D1:50:05 MX Master 3
```

**Comment by AgoodFriendOfSatan** [comment] 2021-08-14 15:49
Ok. So I suspected something might have been happening with the OS installation. After reinstalling I did another `solaar show`

This is now what I get:

solaar show
/usr/share/solaar/lib/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 195, in run
    raise Exception('No devices found')
Exception: No devices found

The mouse again, is plugged in by USB.

**Comment by pfps** [comment] 2021-08-14 20:45
The `lsusb` output you provided above didn't list the mouse.  If the mouse isn't active then Solaar isn't going to find it.

Try moving the mouse around until the cursor follows the mouse, then run Solaar.

**Comment by AgoodFriendOfSatan** [comment] 2021-08-15 15:36
Oof! I thought it was. But having another look at your list, I think you are correct. I'm sorry I wasted your time. But I am greatful that you have helped me.

**Comment by pfps** [comment] 2021-08-15 17:47
OK, I'll close this issue, assuming that all is well.

**Closed by pfps** 2021-08-15 17:47 UTC
