### ISSUE TITLE
KDE blurry tray icon on Plasma 5

### ISSUE THREAD

**Issue by emandret** [pwr-Solaar/Solaar#510] opened 2019-03-18 09:01 UTC
I just noticed the tray icon is blurry on KDE running Plasma 5. Rather strange considering the three tray icons are SVG in the application sources.

![Screenshot_20190318_100119](https://user-images.githubusercontent.com/16176054/54518539-ce682600-4964-11e9-9245-0e7caa98a349.png)

**Comment by cryptomilk** [comment] 2019-07-30 16:14
Also the battery shown is dark grey and on a dark theme is it more or less invisible ...

**Comment by pfps** [comment] 2020-01-13 00:28
The Solaar icons are not very good for the dark theme, I agree.   New icons would be useful.  Is anyone interested in working on this?

**Comment by pfps** [comment] 2020-03-14 18:59
The grey icon in the original comment is by design.  
The battery icons that Solaar uses are a different issue.  If this is still a problem please open a new issue for them.

Closing this issue as not really a bug.

**Closed by pfps** 2020-03-14 18:59 UTC
